// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package query

import (
	"context"
	"database/sql"

	"gorm.io/gorm"
	"gorm.io/gorm/clause"
	"gorm.io/gorm/schema"

	"gorm.io/gen"
	"gorm.io/gen/field"

	"gorm.io/plugin/dbresolver"

	"backend-go/internal/model"
)

func newInfraJobLog(db *gorm.DB, opts ...gen.DOOption) infraJobLog {
	_infraJobLog := infraJobLog{}

	_infraJobLog.infraJobLogDo.UseDB(db, opts...)
	_infraJobLog.infraJobLogDo.UseModel(&model.InfraJobLog{})

	tableName := _infraJobLog.infraJobLogDo.TableName()
	_infraJobLog.ALL = field.NewAsterisk(tableName)
	_infraJobLog.ID = field.NewInt64(tableName, "id")
	_infraJobLog.JobID = field.NewInt64(tableName, "job_id")
	_infraJobLog.HandlerName = field.NewString(tableName, "handler_name")
	_infraJobLog.HandlerParam = field.NewString(tableName, "handler_param")
	_infraJobLog.ExecuteIndex = field.NewInt(tableName, "execute_index")
	_infraJobLog.BeginTime = field.NewTime(tableName, "begin_time")
	_infraJobLog.EndTime = field.NewTime(tableName, "end_time")
	_infraJobLog.Duration = field.NewInt(tableName, "duration")
	_infraJobLog.Status = field.NewInt(tableName, "status")
	_infraJobLog.Result = field.NewString(tableName, "result")
	_infraJobLog.Creator = field.NewString(tableName, "creator")
	_infraJobLog.Updater = field.NewString(tableName, "updater")
	_infraJobLog.CreatedAt = field.NewTime(tableName, "create_time")
	_infraJobLog.UpdatedAt = field.NewTime(tableName, "update_time")
	_infraJobLog.DeletedAt = field.NewField(tableName, "deleted")

	_infraJobLog.fillFieldMap()

	return _infraJobLog
}

type infraJobLog struct {
	infraJobLogDo infraJobLogDo

	ALL          field.Asterisk
	ID           field.Int64  // 日志编号
	JobID        field.Int64  // 任务编号
	HandlerName  field.String // 处理器的名字
	HandlerParam field.String // 处理器的参数
	ExecuteIndex field.Int    // 第几次执行
	BeginTime    field.Time   // 开始执行时间
	EndTime      field.Time   // 结束执行时间
	Duration     field.Int    // 执行时长，单位：毫秒
	Status       field.Int    // 任务状态
	Result       field.String // 结果数据
	Creator      field.String // 创建者
	Updater      field.String // 更新者
	CreatedAt    field.Time   // 创建时间
	UpdatedAt    field.Time   // 更新时间
	DeletedAt    field.Field  // 是否删除

	fieldMap map[string]field.Expr
}

func (i infraJobLog) Table(newTableName string) *infraJobLog {
	i.infraJobLogDo.UseTable(newTableName)
	return i.updateTableName(newTableName)
}

func (i infraJobLog) As(alias string) *infraJobLog {
	i.infraJobLogDo.DO = *(i.infraJobLogDo.As(alias).(*gen.DO))
	return i.updateTableName(alias)
}

func (i *infraJobLog) updateTableName(table string) *infraJobLog {
	i.ALL = field.NewAsterisk(table)
	i.ID = field.NewInt64(table, "id")
	i.JobID = field.NewInt64(table, "job_id")
	i.HandlerName = field.NewString(table, "handler_name")
	i.HandlerParam = field.NewString(table, "handler_param")
	i.ExecuteIndex = field.NewInt(table, "execute_index")
	i.BeginTime = field.NewTime(table, "begin_time")
	i.EndTime = field.NewTime(table, "end_time")
	i.Duration = field.NewInt(table, "duration")
	i.Status = field.NewInt(table, "status")
	i.Result = field.NewString(table, "result")
	i.Creator = field.NewString(table, "creator")
	i.Updater = field.NewString(table, "updater")
	i.CreatedAt = field.NewTime(table, "create_time")
	i.UpdatedAt = field.NewTime(table, "update_time")
	i.DeletedAt = field.NewField(table, "deleted")

	i.fillFieldMap()

	return i
}

func (i *infraJobLog) WithContext(ctx context.Context) IInfraJobLogDo {
	return i.infraJobLogDo.WithContext(ctx)
}

func (i infraJobLog) TableName() string { return i.infraJobLogDo.TableName() }

func (i infraJobLog) Alias() string { return i.infraJobLogDo.Alias() }

func (i infraJobLog) Columns(cols ...field.Expr) gen.Columns { return i.infraJobLogDo.Columns(cols...) }

func (i *infraJobLog) GetFieldByName(fieldName string) (field.OrderExpr, bool) {
	_f, ok := i.fieldMap[fieldName]
	if !ok || _f == nil {
		return nil, false
	}
	_oe, ok := _f.(field.OrderExpr)
	return _oe, ok
}

func (i *infraJobLog) fillFieldMap() {
	i.fieldMap = make(map[string]field.Expr, 15)
	i.fieldMap["id"] = i.ID
	i.fieldMap["job_id"] = i.JobID
	i.fieldMap["handler_name"] = i.HandlerName
	i.fieldMap["handler_param"] = i.HandlerParam
	i.fieldMap["execute_index"] = i.ExecuteIndex
	i.fieldMap["begin_time"] = i.BeginTime
	i.fieldMap["end_time"] = i.EndTime
	i.fieldMap["duration"] = i.Duration
	i.fieldMap["status"] = i.Status
	i.fieldMap["result"] = i.Result
	i.fieldMap["creator"] = i.Creator
	i.fieldMap["updater"] = i.Updater
	i.fieldMap["create_time"] = i.CreatedAt
	i.fieldMap["update_time"] = i.UpdatedAt
	i.fieldMap["deleted"] = i.DeletedAt
}

func (i infraJobLog) clone(db *gorm.DB) infraJobLog {
	i.infraJobLogDo.ReplaceConnPool(db.Statement.ConnPool)
	return i
}

func (i infraJobLog) replaceDB(db *gorm.DB) infraJobLog {
	i.infraJobLogDo.ReplaceDB(db)
	return i
}

type infraJobLogDo struct{ gen.DO }

type IInfraJobLogDo interface {
	gen.SubQuery
	Debug() IInfraJobLogDo
	WithContext(ctx context.Context) IInfraJobLogDo
	WithResult(fc func(tx gen.Dao)) gen.ResultInfo
	ReplaceDB(db *gorm.DB)
	ReadDB() IInfraJobLogDo
	WriteDB() IInfraJobLogDo
	As(alias string) gen.Dao
	Session(config *gorm.Session) IInfraJobLogDo
	Columns(cols ...field.Expr) gen.Columns
	Clauses(conds ...clause.Expression) IInfraJobLogDo
	Not(conds ...gen.Condition) IInfraJobLogDo
	Or(conds ...gen.Condition) IInfraJobLogDo
	Select(conds ...field.Expr) IInfraJobLogDo
	Where(conds ...gen.Condition) IInfraJobLogDo
	Order(conds ...field.Expr) IInfraJobLogDo
	Distinct(cols ...field.Expr) IInfraJobLogDo
	Omit(cols ...field.Expr) IInfraJobLogDo
	Join(table schema.Tabler, on ...field.Expr) IInfraJobLogDo
	LeftJoin(table schema.Tabler, on ...field.Expr) IInfraJobLogDo
	RightJoin(table schema.Tabler, on ...field.Expr) IInfraJobLogDo
	Group(cols ...field.Expr) IInfraJobLogDo
	Having(conds ...gen.Condition) IInfraJobLogDo
	Limit(limit int) IInfraJobLogDo
	Offset(offset int) IInfraJobLogDo
	Count() (count int64, err error)
	Scopes(funcs ...func(gen.Dao) gen.Dao) IInfraJobLogDo
	Unscoped() IInfraJobLogDo
	Create(values ...*model.InfraJobLog) error
	CreateInBatches(values []*model.InfraJobLog, batchSize int) error
	Save(values ...*model.InfraJobLog) error
	First() (*model.InfraJobLog, error)
	Take() (*model.InfraJobLog, error)
	Last() (*model.InfraJobLog, error)
	Find() ([]*model.InfraJobLog, error)
	FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.InfraJobLog, err error)
	FindInBatches(result *[]*model.InfraJobLog, batchSize int, fc func(tx gen.Dao, batch int) error) error
	Pluck(column field.Expr, dest interface{}) error
	Delete(...*model.InfraJobLog) (info gen.ResultInfo, err error)
	Update(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	Updates(value interface{}) (info gen.ResultInfo, err error)
	UpdateColumn(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateColumnSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	UpdateColumns(value interface{}) (info gen.ResultInfo, err error)
	UpdateFrom(q gen.SubQuery) gen.Dao
	Attrs(attrs ...field.AssignExpr) IInfraJobLogDo
	Assign(attrs ...field.AssignExpr) IInfraJobLogDo
	Joins(fields ...field.RelationField) IInfraJobLogDo
	Preload(fields ...field.RelationField) IInfraJobLogDo
	FirstOrInit() (*model.InfraJobLog, error)
	FirstOrCreate() (*model.InfraJobLog, error)
	FindByPage(offset int, limit int) (result []*model.InfraJobLog, count int64, err error)
	ScanByPage(result interface{}, offset int, limit int) (count int64, err error)
	Rows() (*sql.Rows, error)
	Row() *sql.Row
	Scan(result interface{}) (err error)
	Returning(value interface{}, columns ...string) IInfraJobLogDo
	UnderlyingDB() *gorm.DB
	schema.Tabler
}

func (i infraJobLogDo) Debug() IInfraJobLogDo {
	return i.withDO(i.DO.Debug())
}

func (i infraJobLogDo) WithContext(ctx context.Context) IInfraJobLogDo {
	return i.withDO(i.DO.WithContext(ctx))
}

func (i infraJobLogDo) ReadDB() IInfraJobLogDo {
	return i.Clauses(dbresolver.Read)
}

func (i infraJobLogDo) WriteDB() IInfraJobLogDo {
	return i.Clauses(dbresolver.Write)
}

func (i infraJobLogDo) Session(config *gorm.Session) IInfraJobLogDo {
	return i.withDO(i.DO.Session(config))
}

func (i infraJobLogDo) Clauses(conds ...clause.Expression) IInfraJobLogDo {
	return i.withDO(i.DO.Clauses(conds...))
}

func (i infraJobLogDo) Returning(value interface{}, columns ...string) IInfraJobLogDo {
	return i.withDO(i.DO.Returning(value, columns...))
}

func (i infraJobLogDo) Not(conds ...gen.Condition) IInfraJobLogDo {
	return i.withDO(i.DO.Not(conds...))
}

func (i infraJobLogDo) Or(conds ...gen.Condition) IInfraJobLogDo {
	return i.withDO(i.DO.Or(conds...))
}

func (i infraJobLogDo) Select(conds ...field.Expr) IInfraJobLogDo {
	return i.withDO(i.DO.Select(conds...))
}

func (i infraJobLogDo) Where(conds ...gen.Condition) IInfraJobLogDo {
	return i.withDO(i.DO.Where(conds...))
}

func (i infraJobLogDo) Order(conds ...field.Expr) IInfraJobLogDo {
	return i.withDO(i.DO.Order(conds...))
}

func (i infraJobLogDo) Distinct(cols ...field.Expr) IInfraJobLogDo {
	return i.withDO(i.DO.Distinct(cols...))
}

func (i infraJobLogDo) Omit(cols ...field.Expr) IInfraJobLogDo {
	return i.withDO(i.DO.Omit(cols...))
}

func (i infraJobLogDo) Join(table schema.Tabler, on ...field.Expr) IInfraJobLogDo {
	return i.withDO(i.DO.Join(table, on...))
}

func (i infraJobLogDo) LeftJoin(table schema.Tabler, on ...field.Expr) IInfraJobLogDo {
	return i.withDO(i.DO.LeftJoin(table, on...))
}

func (i infraJobLogDo) RightJoin(table schema.Tabler, on ...field.Expr) IInfraJobLogDo {
	return i.withDO(i.DO.RightJoin(table, on...))
}

func (i infraJobLogDo) Group(cols ...field.Expr) IInfraJobLogDo {
	return i.withDO(i.DO.Group(cols...))
}

func (i infraJobLogDo) Having(conds ...gen.Condition) IInfraJobLogDo {
	return i.withDO(i.DO.Having(conds...))
}

func (i infraJobLogDo) Limit(limit int) IInfraJobLogDo {
	return i.withDO(i.DO.Limit(limit))
}

func (i infraJobLogDo) Offset(offset int) IInfraJobLogDo {
	return i.withDO(i.DO.Offset(offset))
}

func (i infraJobLogDo) Scopes(funcs ...func(gen.Dao) gen.Dao) IInfraJobLogDo {
	return i.withDO(i.DO.Scopes(funcs...))
}

func (i infraJobLogDo) Unscoped() IInfraJobLogDo {
	return i.withDO(i.DO.Unscoped())
}

func (i infraJobLogDo) Create(values ...*model.InfraJobLog) error {
	if len(values) == 0 {
		return nil
	}
	return i.DO.Create(values)
}

func (i infraJobLogDo) CreateInBatches(values []*model.InfraJobLog, batchSize int) error {
	return i.DO.CreateInBatches(values, batchSize)
}

// Save : !!! underlying implementation is different with GORM
// The method is equivalent to executing the statement: db.Clauses(clause.OnConflict{UpdateAll: true}).Create(values)
func (i infraJobLogDo) Save(values ...*model.InfraJobLog) error {
	if len(values) == 0 {
		return nil
	}
	return i.DO.Save(values)
}

func (i infraJobLogDo) First() (*model.InfraJobLog, error) {
	if result, err := i.DO.First(); err != nil {
		return nil, err
	} else {
		return result.(*model.InfraJobLog), nil
	}
}

func (i infraJobLogDo) Take() (*model.InfraJobLog, error) {
	if result, err := i.DO.Take(); err != nil {
		return nil, err
	} else {
		return result.(*model.InfraJobLog), nil
	}
}

func (i infraJobLogDo) Last() (*model.InfraJobLog, error) {
	if result, err := i.DO.Last(); err != nil {
		return nil, err
	} else {
		return result.(*model.InfraJobLog), nil
	}
}

func (i infraJobLogDo) Find() ([]*model.InfraJobLog, error) {
	result, err := i.DO.Find()
	return result.([]*model.InfraJobLog), err
}

func (i infraJobLogDo) FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.InfraJobLog, err error) {
	buf := make([]*model.InfraJobLog, 0, batchSize)
	err = i.DO.FindInBatches(&buf, batchSize, func(tx gen.Dao, batch int) error {
		defer func() { results = append(results, buf...) }()
		return fc(tx, batch)
	})
	return results, err
}

func (i infraJobLogDo) FindInBatches(result *[]*model.InfraJobLog, batchSize int, fc func(tx gen.Dao, batch int) error) error {
	return i.DO.FindInBatches(result, batchSize, fc)
}

func (i infraJobLogDo) Attrs(attrs ...field.AssignExpr) IInfraJobLogDo {
	return i.withDO(i.DO.Attrs(attrs...))
}

func (i infraJobLogDo) Assign(attrs ...field.AssignExpr) IInfraJobLogDo {
	return i.withDO(i.DO.Assign(attrs...))
}

func (i infraJobLogDo) Joins(fields ...field.RelationField) IInfraJobLogDo {
	for _, _f := range fields {
		i = *i.withDO(i.DO.Joins(_f))
	}
	return &i
}

func (i infraJobLogDo) Preload(fields ...field.RelationField) IInfraJobLogDo {
	for _, _f := range fields {
		i = *i.withDO(i.DO.Preload(_f))
	}
	return &i
}

func (i infraJobLogDo) FirstOrInit() (*model.InfraJobLog, error) {
	if result, err := i.DO.FirstOrInit(); err != nil {
		return nil, err
	} else {
		return result.(*model.InfraJobLog), nil
	}
}

func (i infraJobLogDo) FirstOrCreate() (*model.InfraJobLog, error) {
	if result, err := i.DO.FirstOrCreate(); err != nil {
		return nil, err
	} else {
		return result.(*model.InfraJobLog), nil
	}
}

func (i infraJobLogDo) FindByPage(offset int, limit int) (result []*model.InfraJobLog, count int64, err error) {
	result, err = i.Offset(offset).Limit(limit).Find()
	if err != nil {
		return
	}

	if size := len(result); 0 < limit && 0 < size && size < limit {
		count = int64(size + offset)
		return
	}

	count, err = i.Offset(-1).Limit(-1).Count()
	return
}

func (i infraJobLogDo) ScanByPage(result interface{}, offset int, limit int) (count int64, err error) {
	count, err = i.Count()
	if err != nil {
		return
	}

	err = i.Offset(offset).Limit(limit).Scan(result)
	return
}

func (i infraJobLogDo) Scan(result interface{}) (err error) {
	return i.DO.Scan(result)
}

func (i infraJobLogDo) Delete(models ...*model.InfraJobLog) (result gen.ResultInfo, err error) {
	return i.DO.Delete(models)
}

func (i *infraJobLogDo) withDO(do gen.Dao) *infraJobLogDo {
	i.DO = *do.(*gen.DO)
	return i
}
