// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package query

import (
	"context"
	"database/sql"

	"gorm.io/gorm"
	"gorm.io/gorm/clause"
	"gorm.io/gorm/schema"

	"gorm.io/gen"
	"gorm.io/gen/field"

	"gorm.io/plugin/dbresolver"

	"backend-go/internal/model"
)

func newInfraApiErrorLog(db *gorm.DB, opts ...gen.DOOption) infraApiErrorLog {
	_infraApiErrorLog := infraApiErrorLog{}

	_infraApiErrorLog.infraApiErrorLogDo.UseDB(db, opts...)
	_infraApiErrorLog.infraApiErrorLogDo.UseModel(&model.InfraApiErrorLog{})

	tableName := _infraApiErrorLog.infraApiErrorLogDo.TableName()
	_infraApiErrorLog.ALL = field.NewAsterisk(tableName)
	_infraApiErrorLog.ID = field.NewInt64(tableName, "id")
	_infraApiErrorLog.TraceID = field.NewString(tableName, "trace_id")
	_infraApiErrorLog.UserID = field.NewInt64(tableName, "user_id")
	_infraApiErrorLog.UserType = field.NewInt(tableName, "user_type")
	_infraApiErrorLog.ApplicationName = field.NewString(tableName, "application_name")
	_infraApiErrorLog.RequestMethod = field.NewString(tableName, "request_method")
	_infraApiErrorLog.RequestURL = field.NewString(tableName, "request_url")
	_infraApiErrorLog.RequestParams = field.NewString(tableName, "request_params")
	_infraApiErrorLog.UserIP = field.NewString(tableName, "user_ip")
	_infraApiErrorLog.UserAgent = field.NewString(tableName, "user_agent")
	_infraApiErrorLog.ExceptionTime = field.NewTime(tableName, "exception_time")
	_infraApiErrorLog.ExceptionName = field.NewString(tableName, "exception_name")
	_infraApiErrorLog.ExceptionMessage = field.NewString(tableName, "exception_message")
	_infraApiErrorLog.ExceptionRootCauseMessage = field.NewString(tableName, "exception_root_cause_message")
	_infraApiErrorLog.ExceptionStackTrace = field.NewString(tableName, "exception_stack_trace")
	_infraApiErrorLog.ExceptionClassName = field.NewString(tableName, "exception_class_name")
	_infraApiErrorLog.ExceptionFileName = field.NewString(tableName, "exception_file_name")
	_infraApiErrorLog.ExceptionMethodName = field.NewString(tableName, "exception_method_name")
	_infraApiErrorLog.ExceptionLineNumber = field.NewInt(tableName, "exception_line_number")
	_infraApiErrorLog.ProcessStatus = field.NewInt(tableName, "process_status")
	_infraApiErrorLog.ProcessTime = field.NewTime(tableName, "process_time")
	_infraApiErrorLog.ProcessUserID = field.NewInt64(tableName, "process_user_id")
	_infraApiErrorLog.Creator = field.NewString(tableName, "creator")
	_infraApiErrorLog.Updater = field.NewString(tableName, "updater")
	_infraApiErrorLog.CreatedAt = field.NewTime(tableName, "create_time")
	_infraApiErrorLog.UpdatedAt = field.NewTime(tableName, "update_time")
	_infraApiErrorLog.DeletedAt = field.NewField(tableName, "deleted")

	_infraApiErrorLog.fillFieldMap()

	return _infraApiErrorLog
}

type infraApiErrorLog struct {
	infraApiErrorLogDo infraApiErrorLogDo

	ALL                       field.Asterisk
	ID                        field.Int64  // 日志编号
	TraceID                   field.String // 链路追踪编号
	UserID                    field.Int64  // 用户编号
	UserType                  field.Int    // 用户类型
	ApplicationName           field.String // 应用名
	RequestMethod             field.String // 请求方法名
	RequestURL                field.String // 请求地址
	RequestParams             field.String // 请求参数
	UserIP                    field.String // 用户IP
	UserAgent                 field.String // 浏览器UA
	ExceptionTime             field.Time   // 异常发生时间
	ExceptionName             field.String // 异常名
	ExceptionMessage          field.String // 异常导致的消息
	ExceptionRootCauseMessage field.String // 异常导致的根消息
	ExceptionStackTrace       field.String // 异常的栈轨迹
	ExceptionClassName        field.String // 异常发生的类全名
	ExceptionFileName         field.String // 异常发生的类文件
	ExceptionMethodName       field.String // 异常发生的方法名
	ExceptionLineNumber       field.Int    // 异常发生的方法所在行
	ProcessStatus             field.Int    // 处理状态
	ProcessTime               field.Time   // 处理时间
	ProcessUserID             field.Int64  // 处理用户编号
	Creator                   field.String // 创建者
	Updater                   field.String // 更新者
	CreatedAt                 field.Time   // 创建时间
	UpdatedAt                 field.Time   // 更新时间
	DeletedAt                 field.Field  // 是否删除

	fieldMap map[string]field.Expr
}

func (i infraApiErrorLog) Table(newTableName string) *infraApiErrorLog {
	i.infraApiErrorLogDo.UseTable(newTableName)
	return i.updateTableName(newTableName)
}

func (i infraApiErrorLog) As(alias string) *infraApiErrorLog {
	i.infraApiErrorLogDo.DO = *(i.infraApiErrorLogDo.As(alias).(*gen.DO))
	return i.updateTableName(alias)
}

func (i *infraApiErrorLog) updateTableName(table string) *infraApiErrorLog {
	i.ALL = field.NewAsterisk(table)
	i.ID = field.NewInt64(table, "id")
	i.TraceID = field.NewString(table, "trace_id")
	i.UserID = field.NewInt64(table, "user_id")
	i.UserType = field.NewInt(table, "user_type")
	i.ApplicationName = field.NewString(table, "application_name")
	i.RequestMethod = field.NewString(table, "request_method")
	i.RequestURL = field.NewString(table, "request_url")
	i.RequestParams = field.NewString(table, "request_params")
	i.UserIP = field.NewString(table, "user_ip")
	i.UserAgent = field.NewString(table, "user_agent")
	i.ExceptionTime = field.NewTime(table, "exception_time")
	i.ExceptionName = field.NewString(table, "exception_name")
	i.ExceptionMessage = field.NewString(table, "exception_message")
	i.ExceptionRootCauseMessage = field.NewString(table, "exception_root_cause_message")
	i.ExceptionStackTrace = field.NewString(table, "exception_stack_trace")
	i.ExceptionClassName = field.NewString(table, "exception_class_name")
	i.ExceptionFileName = field.NewString(table, "exception_file_name")
	i.ExceptionMethodName = field.NewString(table, "exception_method_name")
	i.ExceptionLineNumber = field.NewInt(table, "exception_line_number")
	i.ProcessStatus = field.NewInt(table, "process_status")
	i.ProcessTime = field.NewTime(table, "process_time")
	i.ProcessUserID = field.NewInt64(table, "process_user_id")
	i.Creator = field.NewString(table, "creator")
	i.Updater = field.NewString(table, "updater")
	i.CreatedAt = field.NewTime(table, "create_time")
	i.UpdatedAt = field.NewTime(table, "update_time")
	i.DeletedAt = field.NewField(table, "deleted")

	i.fillFieldMap()

	return i
}

func (i *infraApiErrorLog) WithContext(ctx context.Context) IInfraApiErrorLogDo {
	return i.infraApiErrorLogDo.WithContext(ctx)
}

func (i infraApiErrorLog) TableName() string { return i.infraApiErrorLogDo.TableName() }

func (i infraApiErrorLog) Alias() string { return i.infraApiErrorLogDo.Alias() }

func (i infraApiErrorLog) Columns(cols ...field.Expr) gen.Columns {
	return i.infraApiErrorLogDo.Columns(cols...)
}

func (i *infraApiErrorLog) GetFieldByName(fieldName string) (field.OrderExpr, bool) {
	_f, ok := i.fieldMap[fieldName]
	if !ok || _f == nil {
		return nil, false
	}
	_oe, ok := _f.(field.OrderExpr)
	return _oe, ok
}

func (i *infraApiErrorLog) fillFieldMap() {
	i.fieldMap = make(map[string]field.Expr, 27)
	i.fieldMap["id"] = i.ID
	i.fieldMap["trace_id"] = i.TraceID
	i.fieldMap["user_id"] = i.UserID
	i.fieldMap["user_type"] = i.UserType
	i.fieldMap["application_name"] = i.ApplicationName
	i.fieldMap["request_method"] = i.RequestMethod
	i.fieldMap["request_url"] = i.RequestURL
	i.fieldMap["request_params"] = i.RequestParams
	i.fieldMap["user_ip"] = i.UserIP
	i.fieldMap["user_agent"] = i.UserAgent
	i.fieldMap["exception_time"] = i.ExceptionTime
	i.fieldMap["exception_name"] = i.ExceptionName
	i.fieldMap["exception_message"] = i.ExceptionMessage
	i.fieldMap["exception_root_cause_message"] = i.ExceptionRootCauseMessage
	i.fieldMap["exception_stack_trace"] = i.ExceptionStackTrace
	i.fieldMap["exception_class_name"] = i.ExceptionClassName
	i.fieldMap["exception_file_name"] = i.ExceptionFileName
	i.fieldMap["exception_method_name"] = i.ExceptionMethodName
	i.fieldMap["exception_line_number"] = i.ExceptionLineNumber
	i.fieldMap["process_status"] = i.ProcessStatus
	i.fieldMap["process_time"] = i.ProcessTime
	i.fieldMap["process_user_id"] = i.ProcessUserID
	i.fieldMap["creator"] = i.Creator
	i.fieldMap["updater"] = i.Updater
	i.fieldMap["create_time"] = i.CreatedAt
	i.fieldMap["update_time"] = i.UpdatedAt
	i.fieldMap["deleted"] = i.DeletedAt
}

func (i infraApiErrorLog) clone(db *gorm.DB) infraApiErrorLog {
	i.infraApiErrorLogDo.ReplaceConnPool(db.Statement.ConnPool)
	return i
}

func (i infraApiErrorLog) replaceDB(db *gorm.DB) infraApiErrorLog {
	i.infraApiErrorLogDo.ReplaceDB(db)
	return i
}

type infraApiErrorLogDo struct{ gen.DO }

type IInfraApiErrorLogDo interface {
	gen.SubQuery
	Debug() IInfraApiErrorLogDo
	WithContext(ctx context.Context) IInfraApiErrorLogDo
	WithResult(fc func(tx gen.Dao)) gen.ResultInfo
	ReplaceDB(db *gorm.DB)
	ReadDB() IInfraApiErrorLogDo
	WriteDB() IInfraApiErrorLogDo
	As(alias string) gen.Dao
	Session(config *gorm.Session) IInfraApiErrorLogDo
	Columns(cols ...field.Expr) gen.Columns
	Clauses(conds ...clause.Expression) IInfraApiErrorLogDo
	Not(conds ...gen.Condition) IInfraApiErrorLogDo
	Or(conds ...gen.Condition) IInfraApiErrorLogDo
	Select(conds ...field.Expr) IInfraApiErrorLogDo
	Where(conds ...gen.Condition) IInfraApiErrorLogDo
	Order(conds ...field.Expr) IInfraApiErrorLogDo
	Distinct(cols ...field.Expr) IInfraApiErrorLogDo
	Omit(cols ...field.Expr) IInfraApiErrorLogDo
	Join(table schema.Tabler, on ...field.Expr) IInfraApiErrorLogDo
	LeftJoin(table schema.Tabler, on ...field.Expr) IInfraApiErrorLogDo
	RightJoin(table schema.Tabler, on ...field.Expr) IInfraApiErrorLogDo
	Group(cols ...field.Expr) IInfraApiErrorLogDo
	Having(conds ...gen.Condition) IInfraApiErrorLogDo
	Limit(limit int) IInfraApiErrorLogDo
	Offset(offset int) IInfraApiErrorLogDo
	Count() (count int64, err error)
	Scopes(funcs ...func(gen.Dao) gen.Dao) IInfraApiErrorLogDo
	Unscoped() IInfraApiErrorLogDo
	Create(values ...*model.InfraApiErrorLog) error
	CreateInBatches(values []*model.InfraApiErrorLog, batchSize int) error
	Save(values ...*model.InfraApiErrorLog) error
	First() (*model.InfraApiErrorLog, error)
	Take() (*model.InfraApiErrorLog, error)
	Last() (*model.InfraApiErrorLog, error)
	Find() ([]*model.InfraApiErrorLog, error)
	FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.InfraApiErrorLog, err error)
	FindInBatches(result *[]*model.InfraApiErrorLog, batchSize int, fc func(tx gen.Dao, batch int) error) error
	Pluck(column field.Expr, dest interface{}) error
	Delete(...*model.InfraApiErrorLog) (info gen.ResultInfo, err error)
	Update(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	Updates(value interface{}) (info gen.ResultInfo, err error)
	UpdateColumn(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateColumnSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	UpdateColumns(value interface{}) (info gen.ResultInfo, err error)
	UpdateFrom(q gen.SubQuery) gen.Dao
	Attrs(attrs ...field.AssignExpr) IInfraApiErrorLogDo
	Assign(attrs ...field.AssignExpr) IInfraApiErrorLogDo
	Joins(fields ...field.RelationField) IInfraApiErrorLogDo
	Preload(fields ...field.RelationField) IInfraApiErrorLogDo
	FirstOrInit() (*model.InfraApiErrorLog, error)
	FirstOrCreate() (*model.InfraApiErrorLog, error)
	FindByPage(offset int, limit int) (result []*model.InfraApiErrorLog, count int64, err error)
	ScanByPage(result interface{}, offset int, limit int) (count int64, err error)
	Rows() (*sql.Rows, error)
	Row() *sql.Row
	Scan(result interface{}) (err error)
	Returning(value interface{}, columns ...string) IInfraApiErrorLogDo
	UnderlyingDB() *gorm.DB
	schema.Tabler
}

func (i infraApiErrorLogDo) Debug() IInfraApiErrorLogDo {
	return i.withDO(i.DO.Debug())
}

func (i infraApiErrorLogDo) WithContext(ctx context.Context) IInfraApiErrorLogDo {
	return i.withDO(i.DO.WithContext(ctx))
}

func (i infraApiErrorLogDo) ReadDB() IInfraApiErrorLogDo {
	return i.Clauses(dbresolver.Read)
}

func (i infraApiErrorLogDo) WriteDB() IInfraApiErrorLogDo {
	return i.Clauses(dbresolver.Write)
}

func (i infraApiErrorLogDo) Session(config *gorm.Session) IInfraApiErrorLogDo {
	return i.withDO(i.DO.Session(config))
}

func (i infraApiErrorLogDo) Clauses(conds ...clause.Expression) IInfraApiErrorLogDo {
	return i.withDO(i.DO.Clauses(conds...))
}

func (i infraApiErrorLogDo) Returning(value interface{}, columns ...string) IInfraApiErrorLogDo {
	return i.withDO(i.DO.Returning(value, columns...))
}

func (i infraApiErrorLogDo) Not(conds ...gen.Condition) IInfraApiErrorLogDo {
	return i.withDO(i.DO.Not(conds...))
}

func (i infraApiErrorLogDo) Or(conds ...gen.Condition) IInfraApiErrorLogDo {
	return i.withDO(i.DO.Or(conds...))
}

func (i infraApiErrorLogDo) Select(conds ...field.Expr) IInfraApiErrorLogDo {
	return i.withDO(i.DO.Select(conds...))
}

func (i infraApiErrorLogDo) Where(conds ...gen.Condition) IInfraApiErrorLogDo {
	return i.withDO(i.DO.Where(conds...))
}

func (i infraApiErrorLogDo) Order(conds ...field.Expr) IInfraApiErrorLogDo {
	return i.withDO(i.DO.Order(conds...))
}

func (i infraApiErrorLogDo) Distinct(cols ...field.Expr) IInfraApiErrorLogDo {
	return i.withDO(i.DO.Distinct(cols...))
}

func (i infraApiErrorLogDo) Omit(cols ...field.Expr) IInfraApiErrorLogDo {
	return i.withDO(i.DO.Omit(cols...))
}

func (i infraApiErrorLogDo) Join(table schema.Tabler, on ...field.Expr) IInfraApiErrorLogDo {
	return i.withDO(i.DO.Join(table, on...))
}

func (i infraApiErrorLogDo) LeftJoin(table schema.Tabler, on ...field.Expr) IInfraApiErrorLogDo {
	return i.withDO(i.DO.LeftJoin(table, on...))
}

func (i infraApiErrorLogDo) RightJoin(table schema.Tabler, on ...field.Expr) IInfraApiErrorLogDo {
	return i.withDO(i.DO.RightJoin(table, on...))
}

func (i infraApiErrorLogDo) Group(cols ...field.Expr) IInfraApiErrorLogDo {
	return i.withDO(i.DO.Group(cols...))
}

func (i infraApiErrorLogDo) Having(conds ...gen.Condition) IInfraApiErrorLogDo {
	return i.withDO(i.DO.Having(conds...))
}

func (i infraApiErrorLogDo) Limit(limit int) IInfraApiErrorLogDo {
	return i.withDO(i.DO.Limit(limit))
}

func (i infraApiErrorLogDo) Offset(offset int) IInfraApiErrorLogDo {
	return i.withDO(i.DO.Offset(offset))
}

func (i infraApiErrorLogDo) Scopes(funcs ...func(gen.Dao) gen.Dao) IInfraApiErrorLogDo {
	return i.withDO(i.DO.Scopes(funcs...))
}

func (i infraApiErrorLogDo) Unscoped() IInfraApiErrorLogDo {
	return i.withDO(i.DO.Unscoped())
}

func (i infraApiErrorLogDo) Create(values ...*model.InfraApiErrorLog) error {
	if len(values) == 0 {
		return nil
	}
	return i.DO.Create(values)
}

func (i infraApiErrorLogDo) CreateInBatches(values []*model.InfraApiErrorLog, batchSize int) error {
	return i.DO.CreateInBatches(values, batchSize)
}

// Save : !!! underlying implementation is different with GORM
// The method is equivalent to executing the statement: db.Clauses(clause.OnConflict{UpdateAll: true}).Create(values)
func (i infraApiErrorLogDo) Save(values ...*model.InfraApiErrorLog) error {
	if len(values) == 0 {
		return nil
	}
	return i.DO.Save(values)
}

func (i infraApiErrorLogDo) First() (*model.InfraApiErrorLog, error) {
	if result, err := i.DO.First(); err != nil {
		return nil, err
	} else {
		return result.(*model.InfraApiErrorLog), nil
	}
}

func (i infraApiErrorLogDo) Take() (*model.InfraApiErrorLog, error) {
	if result, err := i.DO.Take(); err != nil {
		return nil, err
	} else {
		return result.(*model.InfraApiErrorLog), nil
	}
}

func (i infraApiErrorLogDo) Last() (*model.InfraApiErrorLog, error) {
	if result, err := i.DO.Last(); err != nil {
		return nil, err
	} else {
		return result.(*model.InfraApiErrorLog), nil
	}
}

func (i infraApiErrorLogDo) Find() ([]*model.InfraApiErrorLog, error) {
	result, err := i.DO.Find()
	return result.([]*model.InfraApiErrorLog), err
}

func (i infraApiErrorLogDo) FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.InfraApiErrorLog, err error) {
	buf := make([]*model.InfraApiErrorLog, 0, batchSize)
	err = i.DO.FindInBatches(&buf, batchSize, func(tx gen.Dao, batch int) error {
		defer func() { results = append(results, buf...) }()
		return fc(tx, batch)
	})
	return results, err
}

func (i infraApiErrorLogDo) FindInBatches(result *[]*model.InfraApiErrorLog, batchSize int, fc func(tx gen.Dao, batch int) error) error {
	return i.DO.FindInBatches(result, batchSize, fc)
}

func (i infraApiErrorLogDo) Attrs(attrs ...field.AssignExpr) IInfraApiErrorLogDo {
	return i.withDO(i.DO.Attrs(attrs...))
}

func (i infraApiErrorLogDo) Assign(attrs ...field.AssignExpr) IInfraApiErrorLogDo {
	return i.withDO(i.DO.Assign(attrs...))
}

func (i infraApiErrorLogDo) Joins(fields ...field.RelationField) IInfraApiErrorLogDo {
	for _, _f := range fields {
		i = *i.withDO(i.DO.Joins(_f))
	}
	return &i
}

func (i infraApiErrorLogDo) Preload(fields ...field.RelationField) IInfraApiErrorLogDo {
	for _, _f := range fields {
		i = *i.withDO(i.DO.Preload(_f))
	}
	return &i
}

func (i infraApiErrorLogDo) FirstOrInit() (*model.InfraApiErrorLog, error) {
	if result, err := i.DO.FirstOrInit(); err != nil {
		return nil, err
	} else {
		return result.(*model.InfraApiErrorLog), nil
	}
}

func (i infraApiErrorLogDo) FirstOrCreate() (*model.InfraApiErrorLog, error) {
	if result, err := i.DO.FirstOrCreate(); err != nil {
		return nil, err
	} else {
		return result.(*model.InfraApiErrorLog), nil
	}
}

func (i infraApiErrorLogDo) FindByPage(offset int, limit int) (result []*model.InfraApiErrorLog, count int64, err error) {
	result, err = i.Offset(offset).Limit(limit).Find()
	if err != nil {
		return
	}

	if size := len(result); 0 < limit && 0 < size && size < limit {
		count = int64(size + offset)
		return
	}

	count, err = i.Offset(-1).Limit(-1).Count()
	return
}

func (i infraApiErrorLogDo) ScanByPage(result interface{}, offset int, limit int) (count int64, err error) {
	count, err = i.Count()
	if err != nil {
		return
	}

	err = i.Offset(offset).Limit(limit).Scan(result)
	return
}

func (i infraApiErrorLogDo) Scan(result interface{}) (err error) {
	return i.DO.Scan(result)
}

func (i infraApiErrorLogDo) Delete(models ...*model.InfraApiErrorLog) (result gen.ResultInfo, err error) {
	return i.DO.Delete(models)
}

func (i *infraApiErrorLogDo) withDO(do gen.Dao) *infraApiErrorLogDo {
	i.DO = *do.(*gen.DO)
	return i
}
