// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package query

import (
	"context"
	"database/sql"

	"gorm.io/gorm"
	"gorm.io/gorm/clause"
	"gorm.io/gorm/schema"

	"gorm.io/gen"
	"gorm.io/gen/field"

	"gorm.io/plugin/dbresolver"

	"backend-go/internal/model"
)

func newInfraFileConfig(db *gorm.DB, opts ...gen.DOOption) infraFileConfig {
	_infraFileConfig := infraFileConfig{}

	_infraFileConfig.infraFileConfigDo.UseDB(db, opts...)
	_infraFileConfig.infraFileConfigDo.UseModel(&model.InfraFileConfig{})

	tableName := _infraFileConfig.infraFileConfigDo.TableName()
	_infraFileConfig.ALL = field.NewAsterisk(tableName)
	_infraFileConfig.ID = field.NewInt64(tableName, "id")
	_infraFileConfig.Name = field.NewString(tableName, "name")
	_infraFileConfig.Storage = field.NewInt32(tableName, "storage")
	_infraFileConfig.Master = field.NewField(tableName, "master")
	_infraFileConfig.Config = field.NewBytes(tableName, "config")
	_infraFileConfig.Remark = field.NewString(tableName, "remark")
	_infraFileConfig.Creator = field.NewString(tableName, "creator")
	_infraFileConfig.Updater = field.NewString(tableName, "updater")
	_infraFileConfig.CreatedAt = field.NewTime(tableName, "create_time")
	_infraFileConfig.UpdatedAt = field.NewTime(tableName, "update_time")
	_infraFileConfig.Deleted = field.NewField(tableName, "deleted")

	_infraFileConfig.fillFieldMap()

	return _infraFileConfig
}

type infraFileConfig struct {
	infraFileConfigDo infraFileConfigDo

	ALL       field.Asterisk
	ID        field.Int64  // 配置编号
	Name      field.String // 配置名
	Storage   field.Int32  // 存储器
	Master    field.Field  // 是否为主配置
	Config    field.Bytes  // 支付渠道配置
	Remark    field.String // 备注
	Creator   field.String // 创建者
	Updater   field.String // 更新者
	CreatedAt field.Time   // 创建时间
	UpdatedAt field.Time   // 更新时间
	Deleted   field.Field  // 是否删除

	fieldMap map[string]field.Expr
}

func (i infraFileConfig) Table(newTableName string) *infraFileConfig {
	i.infraFileConfigDo.UseTable(newTableName)
	return i.updateTableName(newTableName)
}

func (i infraFileConfig) As(alias string) *infraFileConfig {
	i.infraFileConfigDo.DO = *(i.infraFileConfigDo.As(alias).(*gen.DO))
	return i.updateTableName(alias)
}

func (i *infraFileConfig) updateTableName(table string) *infraFileConfig {
	i.ALL = field.NewAsterisk(table)
	i.ID = field.NewInt64(table, "id")
	i.Name = field.NewString(table, "name")
	i.Storage = field.NewInt32(table, "storage")
	i.Master = field.NewField(table, "master")
	i.Config = field.NewBytes(table, "config")
	i.Remark = field.NewString(table, "remark")
	i.Creator = field.NewString(table, "creator")
	i.Updater = field.NewString(table, "updater")
	i.CreatedAt = field.NewTime(table, "create_time")
	i.UpdatedAt = field.NewTime(table, "update_time")
	i.Deleted = field.NewField(table, "deleted")

	i.fillFieldMap()

	return i
}

func (i *infraFileConfig) WithContext(ctx context.Context) IInfraFileConfigDo {
	return i.infraFileConfigDo.WithContext(ctx)
}

func (i infraFileConfig) TableName() string { return i.infraFileConfigDo.TableName() }

func (i infraFileConfig) Alias() string { return i.infraFileConfigDo.Alias() }

func (i infraFileConfig) Columns(cols ...field.Expr) gen.Columns {
	return i.infraFileConfigDo.Columns(cols...)
}

func (i *infraFileConfig) GetFieldByName(fieldName string) (field.OrderExpr, bool) {
	_f, ok := i.fieldMap[fieldName]
	if !ok || _f == nil {
		return nil, false
	}
	_oe, ok := _f.(field.OrderExpr)
	return _oe, ok
}

func (i *infraFileConfig) fillFieldMap() {
	i.fieldMap = make(map[string]field.Expr, 11)
	i.fieldMap["id"] = i.ID
	i.fieldMap["name"] = i.Name
	i.fieldMap["storage"] = i.Storage
	i.fieldMap["master"] = i.Master
	i.fieldMap["config"] = i.Config
	i.fieldMap["remark"] = i.Remark
	i.fieldMap["creator"] = i.Creator
	i.fieldMap["updater"] = i.Updater
	i.fieldMap["create_time"] = i.CreatedAt
	i.fieldMap["update_time"] = i.UpdatedAt
	i.fieldMap["deleted"] = i.Deleted
}

func (i infraFileConfig) clone(db *gorm.DB) infraFileConfig {
	i.infraFileConfigDo.ReplaceConnPool(db.Statement.ConnPool)
	return i
}

func (i infraFileConfig) replaceDB(db *gorm.DB) infraFileConfig {
	i.infraFileConfigDo.ReplaceDB(db)
	return i
}

type infraFileConfigDo struct{ gen.DO }

type IInfraFileConfigDo interface {
	gen.SubQuery
	Debug() IInfraFileConfigDo
	WithContext(ctx context.Context) IInfraFileConfigDo
	WithResult(fc func(tx gen.Dao)) gen.ResultInfo
	ReplaceDB(db *gorm.DB)
	ReadDB() IInfraFileConfigDo
	WriteDB() IInfraFileConfigDo
	As(alias string) gen.Dao
	Session(config *gorm.Session) IInfraFileConfigDo
	Columns(cols ...field.Expr) gen.Columns
	Clauses(conds ...clause.Expression) IInfraFileConfigDo
	Not(conds ...gen.Condition) IInfraFileConfigDo
	Or(conds ...gen.Condition) IInfraFileConfigDo
	Select(conds ...field.Expr) IInfraFileConfigDo
	Where(conds ...gen.Condition) IInfraFileConfigDo
	Order(conds ...field.Expr) IInfraFileConfigDo
	Distinct(cols ...field.Expr) IInfraFileConfigDo
	Omit(cols ...field.Expr) IInfraFileConfigDo
	Join(table schema.Tabler, on ...field.Expr) IInfraFileConfigDo
	LeftJoin(table schema.Tabler, on ...field.Expr) IInfraFileConfigDo
	RightJoin(table schema.Tabler, on ...field.Expr) IInfraFileConfigDo
	Group(cols ...field.Expr) IInfraFileConfigDo
	Having(conds ...gen.Condition) IInfraFileConfigDo
	Limit(limit int) IInfraFileConfigDo
	Offset(offset int) IInfraFileConfigDo
	Count() (count int64, err error)
	Scopes(funcs ...func(gen.Dao) gen.Dao) IInfraFileConfigDo
	Unscoped() IInfraFileConfigDo
	Create(values ...*model.InfraFileConfig) error
	CreateInBatches(values []*model.InfraFileConfig, batchSize int) error
	Save(values ...*model.InfraFileConfig) error
	First() (*model.InfraFileConfig, error)
	Take() (*model.InfraFileConfig, error)
	Last() (*model.InfraFileConfig, error)
	Find() ([]*model.InfraFileConfig, error)
	FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.InfraFileConfig, err error)
	FindInBatches(result *[]*model.InfraFileConfig, batchSize int, fc func(tx gen.Dao, batch int) error) error
	Pluck(column field.Expr, dest interface{}) error
	Delete(...*model.InfraFileConfig) (info gen.ResultInfo, err error)
	Update(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	Updates(value interface{}) (info gen.ResultInfo, err error)
	UpdateColumn(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateColumnSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	UpdateColumns(value interface{}) (info gen.ResultInfo, err error)
	UpdateFrom(q gen.SubQuery) gen.Dao
	Attrs(attrs ...field.AssignExpr) IInfraFileConfigDo
	Assign(attrs ...field.AssignExpr) IInfraFileConfigDo
	Joins(fields ...field.RelationField) IInfraFileConfigDo
	Preload(fields ...field.RelationField) IInfraFileConfigDo
	FirstOrInit() (*model.InfraFileConfig, error)
	FirstOrCreate() (*model.InfraFileConfig, error)
	FindByPage(offset int, limit int) (result []*model.InfraFileConfig, count int64, err error)
	ScanByPage(result interface{}, offset int, limit int) (count int64, err error)
	Rows() (*sql.Rows, error)
	Row() *sql.Row
	Scan(result interface{}) (err error)
	Returning(value interface{}, columns ...string) IInfraFileConfigDo
	UnderlyingDB() *gorm.DB
	schema.Tabler
}

func (i infraFileConfigDo) Debug() IInfraFileConfigDo {
	return i.withDO(i.DO.Debug())
}

func (i infraFileConfigDo) WithContext(ctx context.Context) IInfraFileConfigDo {
	return i.withDO(i.DO.WithContext(ctx))
}

func (i infraFileConfigDo) ReadDB() IInfraFileConfigDo {
	return i.Clauses(dbresolver.Read)
}

func (i infraFileConfigDo) WriteDB() IInfraFileConfigDo {
	return i.Clauses(dbresolver.Write)
}

func (i infraFileConfigDo) Session(config *gorm.Session) IInfraFileConfigDo {
	return i.withDO(i.DO.Session(config))
}

func (i infraFileConfigDo) Clauses(conds ...clause.Expression) IInfraFileConfigDo {
	return i.withDO(i.DO.Clauses(conds...))
}

func (i infraFileConfigDo) Returning(value interface{}, columns ...string) IInfraFileConfigDo {
	return i.withDO(i.DO.Returning(value, columns...))
}

func (i infraFileConfigDo) Not(conds ...gen.Condition) IInfraFileConfigDo {
	return i.withDO(i.DO.Not(conds...))
}

func (i infraFileConfigDo) Or(conds ...gen.Condition) IInfraFileConfigDo {
	return i.withDO(i.DO.Or(conds...))
}

func (i infraFileConfigDo) Select(conds ...field.Expr) IInfraFileConfigDo {
	return i.withDO(i.DO.Select(conds...))
}

func (i infraFileConfigDo) Where(conds ...gen.Condition) IInfraFileConfigDo {
	return i.withDO(i.DO.Where(conds...))
}

func (i infraFileConfigDo) Order(conds ...field.Expr) IInfraFileConfigDo {
	return i.withDO(i.DO.Order(conds...))
}

func (i infraFileConfigDo) Distinct(cols ...field.Expr) IInfraFileConfigDo {
	return i.withDO(i.DO.Distinct(cols...))
}

func (i infraFileConfigDo) Omit(cols ...field.Expr) IInfraFileConfigDo {
	return i.withDO(i.DO.Omit(cols...))
}

func (i infraFileConfigDo) Join(table schema.Tabler, on ...field.Expr) IInfraFileConfigDo {
	return i.withDO(i.DO.Join(table, on...))
}

func (i infraFileConfigDo) LeftJoin(table schema.Tabler, on ...field.Expr) IInfraFileConfigDo {
	return i.withDO(i.DO.LeftJoin(table, on...))
}

func (i infraFileConfigDo) RightJoin(table schema.Tabler, on ...field.Expr) IInfraFileConfigDo {
	return i.withDO(i.DO.RightJoin(table, on...))
}

func (i infraFileConfigDo) Group(cols ...field.Expr) IInfraFileConfigDo {
	return i.withDO(i.DO.Group(cols...))
}

func (i infraFileConfigDo) Having(conds ...gen.Condition) IInfraFileConfigDo {
	return i.withDO(i.DO.Having(conds...))
}

func (i infraFileConfigDo) Limit(limit int) IInfraFileConfigDo {
	return i.withDO(i.DO.Limit(limit))
}

func (i infraFileConfigDo) Offset(offset int) IInfraFileConfigDo {
	return i.withDO(i.DO.Offset(offset))
}

func (i infraFileConfigDo) Scopes(funcs ...func(gen.Dao) gen.Dao) IInfraFileConfigDo {
	return i.withDO(i.DO.Scopes(funcs...))
}

func (i infraFileConfigDo) Unscoped() IInfraFileConfigDo {
	return i.withDO(i.DO.Unscoped())
}

func (i infraFileConfigDo) Create(values ...*model.InfraFileConfig) error {
	if len(values) == 0 {
		return nil
	}
	return i.DO.Create(values)
}

func (i infraFileConfigDo) CreateInBatches(values []*model.InfraFileConfig, batchSize int) error {
	return i.DO.CreateInBatches(values, batchSize)
}

// Save : !!! underlying implementation is different with GORM
// The method is equivalent to executing the statement: db.Clauses(clause.OnConflict{UpdateAll: true}).Create(values)
func (i infraFileConfigDo) Save(values ...*model.InfraFileConfig) error {
	if len(values) == 0 {
		return nil
	}
	return i.DO.Save(values)
}

func (i infraFileConfigDo) First() (*model.InfraFileConfig, error) {
	if result, err := i.DO.First(); err != nil {
		return nil, err
	} else {
		return result.(*model.InfraFileConfig), nil
	}
}

func (i infraFileConfigDo) Take() (*model.InfraFileConfig, error) {
	if result, err := i.DO.Take(); err != nil {
		return nil, err
	} else {
		return result.(*model.InfraFileConfig), nil
	}
}

func (i infraFileConfigDo) Last() (*model.InfraFileConfig, error) {
	if result, err := i.DO.Last(); err != nil {
		return nil, err
	} else {
		return result.(*model.InfraFileConfig), nil
	}
}

func (i infraFileConfigDo) Find() ([]*model.InfraFileConfig, error) {
	result, err := i.DO.Find()
	return result.([]*model.InfraFileConfig), err
}

func (i infraFileConfigDo) FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.InfraFileConfig, err error) {
	buf := make([]*model.InfraFileConfig, 0, batchSize)
	err = i.DO.FindInBatches(&buf, batchSize, func(tx gen.Dao, batch int) error {
		defer func() { results = append(results, buf...) }()
		return fc(tx, batch)
	})
	return results, err
}

func (i infraFileConfigDo) FindInBatches(result *[]*model.InfraFileConfig, batchSize int, fc func(tx gen.Dao, batch int) error) error {
	return i.DO.FindInBatches(result, batchSize, fc)
}

func (i infraFileConfigDo) Attrs(attrs ...field.AssignExpr) IInfraFileConfigDo {
	return i.withDO(i.DO.Attrs(attrs...))
}

func (i infraFileConfigDo) Assign(attrs ...field.AssignExpr) IInfraFileConfigDo {
	return i.withDO(i.DO.Assign(attrs...))
}

func (i infraFileConfigDo) Joins(fields ...field.RelationField) IInfraFileConfigDo {
	for _, _f := range fields {
		i = *i.withDO(i.DO.Joins(_f))
	}
	return &i
}

func (i infraFileConfigDo) Preload(fields ...field.RelationField) IInfraFileConfigDo {
	for _, _f := range fields {
		i = *i.withDO(i.DO.Preload(_f))
	}
	return &i
}

func (i infraFileConfigDo) FirstOrInit() (*model.InfraFileConfig, error) {
	if result, err := i.DO.FirstOrInit(); err != nil {
		return nil, err
	} else {
		return result.(*model.InfraFileConfig), nil
	}
}

func (i infraFileConfigDo) FirstOrCreate() (*model.InfraFileConfig, error) {
	if result, err := i.DO.FirstOrCreate(); err != nil {
		return nil, err
	} else {
		return result.(*model.InfraFileConfig), nil
	}
}

func (i infraFileConfigDo) FindByPage(offset int, limit int) (result []*model.InfraFileConfig, count int64, err error) {
	result, err = i.Offset(offset).Limit(limit).Find()
	if err != nil {
		return
	}

	if size := len(result); 0 < limit && 0 < size && size < limit {
		count = int64(size + offset)
		return
	}

	count, err = i.Offset(-1).Limit(-1).Count()
	return
}

func (i infraFileConfigDo) ScanByPage(result interface{}, offset int, limit int) (count int64, err error) {
	count, err = i.Count()
	if err != nil {
		return
	}

	err = i.Offset(offset).Limit(limit).Scan(result)
	return
}

func (i infraFileConfigDo) Scan(result interface{}) (err error) {
	return i.DO.Scan(result)
}

func (i infraFileConfigDo) Delete(models ...*model.InfraFileConfig) (result gen.ResultInfo, err error) {
	return i.DO.Delete(models)
}

func (i *infraFileConfigDo) withDO(do gen.Dao) *infraFileConfigDo {
	i.DO = *do.(*gen.DO)
	return i
}
