// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package query

import (
	"context"
	"database/sql"

	"gorm.io/gorm"
	"gorm.io/gorm/clause"
	"gorm.io/gorm/schema"

	"gorm.io/gen"
	"gorm.io/gen/field"

	"gorm.io/plugin/dbresolver"

	"backend-go/internal/model"
)

func newInfraApiAccessLog(db *gorm.DB, opts ...gen.DOOption) infraApiAccessLog {
	_infraApiAccessLog := infraApiAccessLog{}

	_infraApiAccessLog.infraApiAccessLogDo.UseDB(db, opts...)
	_infraApiAccessLog.infraApiAccessLogDo.UseModel(&model.InfraApiAccessLog{})

	tableName := _infraApiAccessLog.infraApiAccessLogDo.TableName()
	_infraApiAccessLog.ALL = field.NewAsterisk(tableName)
	_infraApiAccessLog.ID = field.NewInt64(tableName, "id")
	_infraApiAccessLog.TraceID = field.NewString(tableName, "trace_id")
	_infraApiAccessLog.UserID = field.NewInt64(tableName, "user_id")
	_infraApiAccessLog.UserType = field.NewInt(tableName, "user_type")
	_infraApiAccessLog.ApplicationName = field.NewString(tableName, "application_name")
	_infraApiAccessLog.RequestMethod = field.NewString(tableName, "request_method")
	_infraApiAccessLog.RequestURL = field.NewString(tableName, "request_url")
	_infraApiAccessLog.RequestParams = field.NewString(tableName, "request_params")
	_infraApiAccessLog.ResponseBody = field.NewString(tableName, "response_body")
	_infraApiAccessLog.UserIP = field.NewString(tableName, "user_ip")
	_infraApiAccessLog.UserAgent = field.NewString(tableName, "user_agent")
	_infraApiAccessLog.OperateModule = field.NewString(tableName, "operate_module")
	_infraApiAccessLog.OperateName = field.NewString(tableName, "operate_name")
	_infraApiAccessLog.OperateType = field.NewInt(tableName, "operate_type")
	_infraApiAccessLog.BeginTime = field.NewTime(tableName, "begin_time")
	_infraApiAccessLog.EndTime = field.NewTime(tableName, "end_time")
	_infraApiAccessLog.Duration = field.NewInt(tableName, "duration")
	_infraApiAccessLog.ResultCode = field.NewInt(tableName, "result_code")
	_infraApiAccessLog.ResultMsg = field.NewString(tableName, "result_msg")
	_infraApiAccessLog.Creator = field.NewString(tableName, "creator")
	_infraApiAccessLog.Updater = field.NewString(tableName, "updater")
	_infraApiAccessLog.CreatedAt = field.NewTime(tableName, "create_time")
	_infraApiAccessLog.UpdatedAt = field.NewTime(tableName, "update_time")
	_infraApiAccessLog.DeletedAt = field.NewField(tableName, "deleted")

	_infraApiAccessLog.fillFieldMap()

	return _infraApiAccessLog
}

type infraApiAccessLog struct {
	infraApiAccessLogDo infraApiAccessLogDo

	ALL             field.Asterisk
	ID              field.Int64  // 日志编号
	TraceID         field.String // 链路追踪编号
	UserID          field.Int64  // 用户编号
	UserType        field.Int    // 用户类型
	ApplicationName field.String // 应用名
	RequestMethod   field.String // 请求方法名
	RequestURL      field.String // 请求地址
	RequestParams   field.String // 请求参数
	ResponseBody    field.String // 响应结果
	UserIP          field.String // 用户IP
	UserAgent       field.String // 浏览器UA
	OperateModule   field.String // 操作模块
	OperateName     field.String // 操作名
	OperateType     field.Int    // 操作分类
	BeginTime       field.Time   // 开始请求时间
	EndTime         field.Time   // 结束请求时间
	Duration        field.Int    // 执行时长
	ResultCode      field.Int    // 结果码
	ResultMsg       field.String // 结果提示
	Creator         field.String // 创建者
	Updater         field.String // 更新者
	CreatedAt       field.Time   // 创建时间
	UpdatedAt       field.Time   // 更新时间
	DeletedAt       field.Field  // 是否删除

	fieldMap map[string]field.Expr
}

func (i infraApiAccessLog) Table(newTableName string) *infraApiAccessLog {
	i.infraApiAccessLogDo.UseTable(newTableName)
	return i.updateTableName(newTableName)
}

func (i infraApiAccessLog) As(alias string) *infraApiAccessLog {
	i.infraApiAccessLogDo.DO = *(i.infraApiAccessLogDo.As(alias).(*gen.DO))
	return i.updateTableName(alias)
}

func (i *infraApiAccessLog) updateTableName(table string) *infraApiAccessLog {
	i.ALL = field.NewAsterisk(table)
	i.ID = field.NewInt64(table, "id")
	i.TraceID = field.NewString(table, "trace_id")
	i.UserID = field.NewInt64(table, "user_id")
	i.UserType = field.NewInt(table, "user_type")
	i.ApplicationName = field.NewString(table, "application_name")
	i.RequestMethod = field.NewString(table, "request_method")
	i.RequestURL = field.NewString(table, "request_url")
	i.RequestParams = field.NewString(table, "request_params")
	i.ResponseBody = field.NewString(table, "response_body")
	i.UserIP = field.NewString(table, "user_ip")
	i.UserAgent = field.NewString(table, "user_agent")
	i.OperateModule = field.NewString(table, "operate_module")
	i.OperateName = field.NewString(table, "operate_name")
	i.OperateType = field.NewInt(table, "operate_type")
	i.BeginTime = field.NewTime(table, "begin_time")
	i.EndTime = field.NewTime(table, "end_time")
	i.Duration = field.NewInt(table, "duration")
	i.ResultCode = field.NewInt(table, "result_code")
	i.ResultMsg = field.NewString(table, "result_msg")
	i.Creator = field.NewString(table, "creator")
	i.Updater = field.NewString(table, "updater")
	i.CreatedAt = field.NewTime(table, "create_time")
	i.UpdatedAt = field.NewTime(table, "update_time")
	i.DeletedAt = field.NewField(table, "deleted")

	i.fillFieldMap()

	return i
}

func (i *infraApiAccessLog) WithContext(ctx context.Context) IInfraApiAccessLogDo {
	return i.infraApiAccessLogDo.WithContext(ctx)
}

func (i infraApiAccessLog) TableName() string { return i.infraApiAccessLogDo.TableName() }

func (i infraApiAccessLog) Alias() string { return i.infraApiAccessLogDo.Alias() }

func (i infraApiAccessLog) Columns(cols ...field.Expr) gen.Columns {
	return i.infraApiAccessLogDo.Columns(cols...)
}

func (i *infraApiAccessLog) GetFieldByName(fieldName string) (field.OrderExpr, bool) {
	_f, ok := i.fieldMap[fieldName]
	if !ok || _f == nil {
		return nil, false
	}
	_oe, ok := _f.(field.OrderExpr)
	return _oe, ok
}

func (i *infraApiAccessLog) fillFieldMap() {
	i.fieldMap = make(map[string]field.Expr, 24)
	i.fieldMap["id"] = i.ID
	i.fieldMap["trace_id"] = i.TraceID
	i.fieldMap["user_id"] = i.UserID
	i.fieldMap["user_type"] = i.UserType
	i.fieldMap["application_name"] = i.ApplicationName
	i.fieldMap["request_method"] = i.RequestMethod
	i.fieldMap["request_url"] = i.RequestURL
	i.fieldMap["request_params"] = i.RequestParams
	i.fieldMap["response_body"] = i.ResponseBody
	i.fieldMap["user_ip"] = i.UserIP
	i.fieldMap["user_agent"] = i.UserAgent
	i.fieldMap["operate_module"] = i.OperateModule
	i.fieldMap["operate_name"] = i.OperateName
	i.fieldMap["operate_type"] = i.OperateType
	i.fieldMap["begin_time"] = i.BeginTime
	i.fieldMap["end_time"] = i.EndTime
	i.fieldMap["duration"] = i.Duration
	i.fieldMap["result_code"] = i.ResultCode
	i.fieldMap["result_msg"] = i.ResultMsg
	i.fieldMap["creator"] = i.Creator
	i.fieldMap["updater"] = i.Updater
	i.fieldMap["create_time"] = i.CreatedAt
	i.fieldMap["update_time"] = i.UpdatedAt
	i.fieldMap["deleted"] = i.DeletedAt
}

func (i infraApiAccessLog) clone(db *gorm.DB) infraApiAccessLog {
	i.infraApiAccessLogDo.ReplaceConnPool(db.Statement.ConnPool)
	return i
}

func (i infraApiAccessLog) replaceDB(db *gorm.DB) infraApiAccessLog {
	i.infraApiAccessLogDo.ReplaceDB(db)
	return i
}

type infraApiAccessLogDo struct{ gen.DO }

type IInfraApiAccessLogDo interface {
	gen.SubQuery
	Debug() IInfraApiAccessLogDo
	WithContext(ctx context.Context) IInfraApiAccessLogDo
	WithResult(fc func(tx gen.Dao)) gen.ResultInfo
	ReplaceDB(db *gorm.DB)
	ReadDB() IInfraApiAccessLogDo
	WriteDB() IInfraApiAccessLogDo
	As(alias string) gen.Dao
	Session(config *gorm.Session) IInfraApiAccessLogDo
	Columns(cols ...field.Expr) gen.Columns
	Clauses(conds ...clause.Expression) IInfraApiAccessLogDo
	Not(conds ...gen.Condition) IInfraApiAccessLogDo
	Or(conds ...gen.Condition) IInfraApiAccessLogDo
	Select(conds ...field.Expr) IInfraApiAccessLogDo
	Where(conds ...gen.Condition) IInfraApiAccessLogDo
	Order(conds ...field.Expr) IInfraApiAccessLogDo
	Distinct(cols ...field.Expr) IInfraApiAccessLogDo
	Omit(cols ...field.Expr) IInfraApiAccessLogDo
	Join(table schema.Tabler, on ...field.Expr) IInfraApiAccessLogDo
	LeftJoin(table schema.Tabler, on ...field.Expr) IInfraApiAccessLogDo
	RightJoin(table schema.Tabler, on ...field.Expr) IInfraApiAccessLogDo
	Group(cols ...field.Expr) IInfraApiAccessLogDo
	Having(conds ...gen.Condition) IInfraApiAccessLogDo
	Limit(limit int) IInfraApiAccessLogDo
	Offset(offset int) IInfraApiAccessLogDo
	Count() (count int64, err error)
	Scopes(funcs ...func(gen.Dao) gen.Dao) IInfraApiAccessLogDo
	Unscoped() IInfraApiAccessLogDo
	Create(values ...*model.InfraApiAccessLog) error
	CreateInBatches(values []*model.InfraApiAccessLog, batchSize int) error
	Save(values ...*model.InfraApiAccessLog) error
	First() (*model.InfraApiAccessLog, error)
	Take() (*model.InfraApiAccessLog, error)
	Last() (*model.InfraApiAccessLog, error)
	Find() ([]*model.InfraApiAccessLog, error)
	FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.InfraApiAccessLog, err error)
	FindInBatches(result *[]*model.InfraApiAccessLog, batchSize int, fc func(tx gen.Dao, batch int) error) error
	Pluck(column field.Expr, dest interface{}) error
	Delete(...*model.InfraApiAccessLog) (info gen.ResultInfo, err error)
	Update(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	Updates(value interface{}) (info gen.ResultInfo, err error)
	UpdateColumn(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateColumnSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	UpdateColumns(value interface{}) (info gen.ResultInfo, err error)
	UpdateFrom(q gen.SubQuery) gen.Dao
	Attrs(attrs ...field.AssignExpr) IInfraApiAccessLogDo
	Assign(attrs ...field.AssignExpr) IInfraApiAccessLogDo
	Joins(fields ...field.RelationField) IInfraApiAccessLogDo
	Preload(fields ...field.RelationField) IInfraApiAccessLogDo
	FirstOrInit() (*model.InfraApiAccessLog, error)
	FirstOrCreate() (*model.InfraApiAccessLog, error)
	FindByPage(offset int, limit int) (result []*model.InfraApiAccessLog, count int64, err error)
	ScanByPage(result interface{}, offset int, limit int) (count int64, err error)
	Rows() (*sql.Rows, error)
	Row() *sql.Row
	Scan(result interface{}) (err error)
	Returning(value interface{}, columns ...string) IInfraApiAccessLogDo
	UnderlyingDB() *gorm.DB
	schema.Tabler
}

func (i infraApiAccessLogDo) Debug() IInfraApiAccessLogDo {
	return i.withDO(i.DO.Debug())
}

func (i infraApiAccessLogDo) WithContext(ctx context.Context) IInfraApiAccessLogDo {
	return i.withDO(i.DO.WithContext(ctx))
}

func (i infraApiAccessLogDo) ReadDB() IInfraApiAccessLogDo {
	return i.Clauses(dbresolver.Read)
}

func (i infraApiAccessLogDo) WriteDB() IInfraApiAccessLogDo {
	return i.Clauses(dbresolver.Write)
}

func (i infraApiAccessLogDo) Session(config *gorm.Session) IInfraApiAccessLogDo {
	return i.withDO(i.DO.Session(config))
}

func (i infraApiAccessLogDo) Clauses(conds ...clause.Expression) IInfraApiAccessLogDo {
	return i.withDO(i.DO.Clauses(conds...))
}

func (i infraApiAccessLogDo) Returning(value interface{}, columns ...string) IInfraApiAccessLogDo {
	return i.withDO(i.DO.Returning(value, columns...))
}

func (i infraApiAccessLogDo) Not(conds ...gen.Condition) IInfraApiAccessLogDo {
	return i.withDO(i.DO.Not(conds...))
}

func (i infraApiAccessLogDo) Or(conds ...gen.Condition) IInfraApiAccessLogDo {
	return i.withDO(i.DO.Or(conds...))
}

func (i infraApiAccessLogDo) Select(conds ...field.Expr) IInfraApiAccessLogDo {
	return i.withDO(i.DO.Select(conds...))
}

func (i infraApiAccessLogDo) Where(conds ...gen.Condition) IInfraApiAccessLogDo {
	return i.withDO(i.DO.Where(conds...))
}

func (i infraApiAccessLogDo) Order(conds ...field.Expr) IInfraApiAccessLogDo {
	return i.withDO(i.DO.Order(conds...))
}

func (i infraApiAccessLogDo) Distinct(cols ...field.Expr) IInfraApiAccessLogDo {
	return i.withDO(i.DO.Distinct(cols...))
}

func (i infraApiAccessLogDo) Omit(cols ...field.Expr) IInfraApiAccessLogDo {
	return i.withDO(i.DO.Omit(cols...))
}

func (i infraApiAccessLogDo) Join(table schema.Tabler, on ...field.Expr) IInfraApiAccessLogDo {
	return i.withDO(i.DO.Join(table, on...))
}

func (i infraApiAccessLogDo) LeftJoin(table schema.Tabler, on ...field.Expr) IInfraApiAccessLogDo {
	return i.withDO(i.DO.LeftJoin(table, on...))
}

func (i infraApiAccessLogDo) RightJoin(table schema.Tabler, on ...field.Expr) IInfraApiAccessLogDo {
	return i.withDO(i.DO.RightJoin(table, on...))
}

func (i infraApiAccessLogDo) Group(cols ...field.Expr) IInfraApiAccessLogDo {
	return i.withDO(i.DO.Group(cols...))
}

func (i infraApiAccessLogDo) Having(conds ...gen.Condition) IInfraApiAccessLogDo {
	return i.withDO(i.DO.Having(conds...))
}

func (i infraApiAccessLogDo) Limit(limit int) IInfraApiAccessLogDo {
	return i.withDO(i.DO.Limit(limit))
}

func (i infraApiAccessLogDo) Offset(offset int) IInfraApiAccessLogDo {
	return i.withDO(i.DO.Offset(offset))
}

func (i infraApiAccessLogDo) Scopes(funcs ...func(gen.Dao) gen.Dao) IInfraApiAccessLogDo {
	return i.withDO(i.DO.Scopes(funcs...))
}

func (i infraApiAccessLogDo) Unscoped() IInfraApiAccessLogDo {
	return i.withDO(i.DO.Unscoped())
}

func (i infraApiAccessLogDo) Create(values ...*model.InfraApiAccessLog) error {
	if len(values) == 0 {
		return nil
	}
	return i.DO.Create(values)
}

func (i infraApiAccessLogDo) CreateInBatches(values []*model.InfraApiAccessLog, batchSize int) error {
	return i.DO.CreateInBatches(values, batchSize)
}

// Save : !!! underlying implementation is different with GORM
// The method is equivalent to executing the statement: db.Clauses(clause.OnConflict{UpdateAll: true}).Create(values)
func (i infraApiAccessLogDo) Save(values ...*model.InfraApiAccessLog) error {
	if len(values) == 0 {
		return nil
	}
	return i.DO.Save(values)
}

func (i infraApiAccessLogDo) First() (*model.InfraApiAccessLog, error) {
	if result, err := i.DO.First(); err != nil {
		return nil, err
	} else {
		return result.(*model.InfraApiAccessLog), nil
	}
}

func (i infraApiAccessLogDo) Take() (*model.InfraApiAccessLog, error) {
	if result, err := i.DO.Take(); err != nil {
		return nil, err
	} else {
		return result.(*model.InfraApiAccessLog), nil
	}
}

func (i infraApiAccessLogDo) Last() (*model.InfraApiAccessLog, error) {
	if result, err := i.DO.Last(); err != nil {
		return nil, err
	} else {
		return result.(*model.InfraApiAccessLog), nil
	}
}

func (i infraApiAccessLogDo) Find() ([]*model.InfraApiAccessLog, error) {
	result, err := i.DO.Find()
	return result.([]*model.InfraApiAccessLog), err
}

func (i infraApiAccessLogDo) FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.InfraApiAccessLog, err error) {
	buf := make([]*model.InfraApiAccessLog, 0, batchSize)
	err = i.DO.FindInBatches(&buf, batchSize, func(tx gen.Dao, batch int) error {
		defer func() { results = append(results, buf...) }()
		return fc(tx, batch)
	})
	return results, err
}

func (i infraApiAccessLogDo) FindInBatches(result *[]*model.InfraApiAccessLog, batchSize int, fc func(tx gen.Dao, batch int) error) error {
	return i.DO.FindInBatches(result, batchSize, fc)
}

func (i infraApiAccessLogDo) Attrs(attrs ...field.AssignExpr) IInfraApiAccessLogDo {
	return i.withDO(i.DO.Attrs(attrs...))
}

func (i infraApiAccessLogDo) Assign(attrs ...field.AssignExpr) IInfraApiAccessLogDo {
	return i.withDO(i.DO.Assign(attrs...))
}

func (i infraApiAccessLogDo) Joins(fields ...field.RelationField) IInfraApiAccessLogDo {
	for _, _f := range fields {
		i = *i.withDO(i.DO.Joins(_f))
	}
	return &i
}

func (i infraApiAccessLogDo) Preload(fields ...field.RelationField) IInfraApiAccessLogDo {
	for _, _f := range fields {
		i = *i.withDO(i.DO.Preload(_f))
	}
	return &i
}

func (i infraApiAccessLogDo) FirstOrInit() (*model.InfraApiAccessLog, error) {
	if result, err := i.DO.FirstOrInit(); err != nil {
		return nil, err
	} else {
		return result.(*model.InfraApiAccessLog), nil
	}
}

func (i infraApiAccessLogDo) FirstOrCreate() (*model.InfraApiAccessLog, error) {
	if result, err := i.DO.FirstOrCreate(); err != nil {
		return nil, err
	} else {
		return result.(*model.InfraApiAccessLog), nil
	}
}

func (i infraApiAccessLogDo) FindByPage(offset int, limit int) (result []*model.InfraApiAccessLog, count int64, err error) {
	result, err = i.Offset(offset).Limit(limit).Find()
	if err != nil {
		return
	}

	if size := len(result); 0 < limit && 0 < size && size < limit {
		count = int64(size + offset)
		return
	}

	count, err = i.Offset(-1).Limit(-1).Count()
	return
}

func (i infraApiAccessLogDo) ScanByPage(result interface{}, offset int, limit int) (count int64, err error) {
	count, err = i.Count()
	if err != nil {
		return
	}

	err = i.Offset(offset).Limit(limit).Scan(result)
	return
}

func (i infraApiAccessLogDo) Scan(result interface{}) (err error) {
	return i.DO.Scan(result)
}

func (i infraApiAccessLogDo) Delete(models ...*model.InfraApiAccessLog) (result gen.ResultInfo, err error) {
	return i.DO.Delete(models)
}

func (i *infraApiAccessLogDo) withDO(do gen.Dao) *infraApiAccessLogDo {
	i.DO = *do.(*gen.DO)
	return i
}
