// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package query

import (
	"context"
	"database/sql"

	"gorm.io/gorm"
	"gorm.io/gorm/clause"
	"gorm.io/gorm/schema"

	"gorm.io/gen"
	"gorm.io/gen/field"

	"gorm.io/plugin/dbresolver"

	"backend-go/internal/model"
)

func newInfraJob(db *gorm.DB, opts ...gen.DOOption) infraJob {
	_infraJob := infraJob{}

	_infraJob.infraJobDo.UseDB(db, opts...)
	_infraJob.infraJobDo.UseModel(&model.InfraJob{})

	tableName := _infraJob.infraJobDo.TableName()
	_infraJob.ALL = field.NewAsterisk(tableName)
	_infraJob.ID = field.NewInt64(tableName, "id")
	_infraJob.Name = field.NewString(tableName, "name")
	_infraJob.Status = field.NewInt(tableName, "status")
	_infraJob.HandlerName = field.NewString(tableName, "handler_name")
	_infraJob.HandlerParam = field.NewString(tableName, "handler_param")
	_infraJob.CronExpression = field.NewString(tableName, "cron_expression")
	_infraJob.RetryCount = field.NewInt(tableName, "retry_count")
	_infraJob.RetryInterval = field.NewInt(tableName, "retry_interval")
	_infraJob.MonitorTimeout = field.NewInt(tableName, "monitor_timeout")
	_infraJob.Creator = field.NewString(tableName, "creator")
	_infraJob.Updater = field.NewString(tableName, "updater")
	_infraJob.CreatedAt = field.NewTime(tableName, "create_time")
	_infraJob.UpdatedAt = field.NewTime(tableName, "update_time")
	_infraJob.DeletedAt = field.NewField(tableName, "deleted")

	_infraJob.fillFieldMap()

	return _infraJob
}

type infraJob struct {
	infraJobDo infraJobDo

	ALL            field.Asterisk
	ID             field.Int64  // 任务编号
	Name           field.String // 任务名称
	Status         field.Int    // 任务状态
	HandlerName    field.String // 处理器的名字
	HandlerParam   field.String // 处理器的参数
	CronExpression field.String // CRON 表达式
	RetryCount     field.Int    // 重试次数
	RetryInterval  field.Int    // 重试间隔，单位：毫秒
	MonitorTimeout field.Int    // 监控超时时间，单位：毫秒
	Creator        field.String // 创建者
	Updater        field.String // 更新者
	CreatedAt      field.Time   // 创建时间
	UpdatedAt      field.Time   // 更新时间
	DeletedAt      field.Field  // 是否删除

	fieldMap map[string]field.Expr
}

func (i infraJob) Table(newTableName string) *infraJob {
	i.infraJobDo.UseTable(newTableName)
	return i.updateTableName(newTableName)
}

func (i infraJob) As(alias string) *infraJob {
	i.infraJobDo.DO = *(i.infraJobDo.As(alias).(*gen.DO))
	return i.updateTableName(alias)
}

func (i *infraJob) updateTableName(table string) *infraJob {
	i.ALL = field.NewAsterisk(table)
	i.ID = field.NewInt64(table, "id")
	i.Name = field.NewString(table, "name")
	i.Status = field.NewInt(table, "status")
	i.HandlerName = field.NewString(table, "handler_name")
	i.HandlerParam = field.NewString(table, "handler_param")
	i.CronExpression = field.NewString(table, "cron_expression")
	i.RetryCount = field.NewInt(table, "retry_count")
	i.RetryInterval = field.NewInt(table, "retry_interval")
	i.MonitorTimeout = field.NewInt(table, "monitor_timeout")
	i.Creator = field.NewString(table, "creator")
	i.Updater = field.NewString(table, "updater")
	i.CreatedAt = field.NewTime(table, "create_time")
	i.UpdatedAt = field.NewTime(table, "update_time")
	i.DeletedAt = field.NewField(table, "deleted")

	i.fillFieldMap()

	return i
}

func (i *infraJob) WithContext(ctx context.Context) IInfraJobDo { return i.infraJobDo.WithContext(ctx) }

func (i infraJob) TableName() string { return i.infraJobDo.TableName() }

func (i infraJob) Alias() string { return i.infraJobDo.Alias() }

func (i infraJob) Columns(cols ...field.Expr) gen.Columns { return i.infraJobDo.Columns(cols...) }

func (i *infraJob) GetFieldByName(fieldName string) (field.OrderExpr, bool) {
	_f, ok := i.fieldMap[fieldName]
	if !ok || _f == nil {
		return nil, false
	}
	_oe, ok := _f.(field.OrderExpr)
	return _oe, ok
}

func (i *infraJob) fillFieldMap() {
	i.fieldMap = make(map[string]field.Expr, 14)
	i.fieldMap["id"] = i.ID
	i.fieldMap["name"] = i.Name
	i.fieldMap["status"] = i.Status
	i.fieldMap["handler_name"] = i.HandlerName
	i.fieldMap["handler_param"] = i.HandlerParam
	i.fieldMap["cron_expression"] = i.CronExpression
	i.fieldMap["retry_count"] = i.RetryCount
	i.fieldMap["retry_interval"] = i.RetryInterval
	i.fieldMap["monitor_timeout"] = i.MonitorTimeout
	i.fieldMap["creator"] = i.Creator
	i.fieldMap["updater"] = i.Updater
	i.fieldMap["create_time"] = i.CreatedAt
	i.fieldMap["update_time"] = i.UpdatedAt
	i.fieldMap["deleted"] = i.DeletedAt
}

func (i infraJob) clone(db *gorm.DB) infraJob {
	i.infraJobDo.ReplaceConnPool(db.Statement.ConnPool)
	return i
}

func (i infraJob) replaceDB(db *gorm.DB) infraJob {
	i.infraJobDo.ReplaceDB(db)
	return i
}

type infraJobDo struct{ gen.DO }

type IInfraJobDo interface {
	gen.SubQuery
	Debug() IInfraJobDo
	WithContext(ctx context.Context) IInfraJobDo
	WithResult(fc func(tx gen.Dao)) gen.ResultInfo
	ReplaceDB(db *gorm.DB)
	ReadDB() IInfraJobDo
	WriteDB() IInfraJobDo
	As(alias string) gen.Dao
	Session(config *gorm.Session) IInfraJobDo
	Columns(cols ...field.Expr) gen.Columns
	Clauses(conds ...clause.Expression) IInfraJobDo
	Not(conds ...gen.Condition) IInfraJobDo
	Or(conds ...gen.Condition) IInfraJobDo
	Select(conds ...field.Expr) IInfraJobDo
	Where(conds ...gen.Condition) IInfraJobDo
	Order(conds ...field.Expr) IInfraJobDo
	Distinct(cols ...field.Expr) IInfraJobDo
	Omit(cols ...field.Expr) IInfraJobDo
	Join(table schema.Tabler, on ...field.Expr) IInfraJobDo
	LeftJoin(table schema.Tabler, on ...field.Expr) IInfraJobDo
	RightJoin(table schema.Tabler, on ...field.Expr) IInfraJobDo
	Group(cols ...field.Expr) IInfraJobDo
	Having(conds ...gen.Condition) IInfraJobDo
	Limit(limit int) IInfraJobDo
	Offset(offset int) IInfraJobDo
	Count() (count int64, err error)
	Scopes(funcs ...func(gen.Dao) gen.Dao) IInfraJobDo
	Unscoped() IInfraJobDo
	Create(values ...*model.InfraJob) error
	CreateInBatches(values []*model.InfraJob, batchSize int) error
	Save(values ...*model.InfraJob) error
	First() (*model.InfraJob, error)
	Take() (*model.InfraJob, error)
	Last() (*model.InfraJob, error)
	Find() ([]*model.InfraJob, error)
	FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.InfraJob, err error)
	FindInBatches(result *[]*model.InfraJob, batchSize int, fc func(tx gen.Dao, batch int) error) error
	Pluck(column field.Expr, dest interface{}) error
	Delete(...*model.InfraJob) (info gen.ResultInfo, err error)
	Update(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	Updates(value interface{}) (info gen.ResultInfo, err error)
	UpdateColumn(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateColumnSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	UpdateColumns(value interface{}) (info gen.ResultInfo, err error)
	UpdateFrom(q gen.SubQuery) gen.Dao
	Attrs(attrs ...field.AssignExpr) IInfraJobDo
	Assign(attrs ...field.AssignExpr) IInfraJobDo
	Joins(fields ...field.RelationField) IInfraJobDo
	Preload(fields ...field.RelationField) IInfraJobDo
	FirstOrInit() (*model.InfraJob, error)
	FirstOrCreate() (*model.InfraJob, error)
	FindByPage(offset int, limit int) (result []*model.InfraJob, count int64, err error)
	ScanByPage(result interface{}, offset int, limit int) (count int64, err error)
	Rows() (*sql.Rows, error)
	Row() *sql.Row
	Scan(result interface{}) (err error)
	Returning(value interface{}, columns ...string) IInfraJobDo
	UnderlyingDB() *gorm.DB
	schema.Tabler
}

func (i infraJobDo) Debug() IInfraJobDo {
	return i.withDO(i.DO.Debug())
}

func (i infraJobDo) WithContext(ctx context.Context) IInfraJobDo {
	return i.withDO(i.DO.WithContext(ctx))
}

func (i infraJobDo) ReadDB() IInfraJobDo {
	return i.Clauses(dbresolver.Read)
}

func (i infraJobDo) WriteDB() IInfraJobDo {
	return i.Clauses(dbresolver.Write)
}

func (i infraJobDo) Session(config *gorm.Session) IInfraJobDo {
	return i.withDO(i.DO.Session(config))
}

func (i infraJobDo) Clauses(conds ...clause.Expression) IInfraJobDo {
	return i.withDO(i.DO.Clauses(conds...))
}

func (i infraJobDo) Returning(value interface{}, columns ...string) IInfraJobDo {
	return i.withDO(i.DO.Returning(value, columns...))
}

func (i infraJobDo) Not(conds ...gen.Condition) IInfraJobDo {
	return i.withDO(i.DO.Not(conds...))
}

func (i infraJobDo) Or(conds ...gen.Condition) IInfraJobDo {
	return i.withDO(i.DO.Or(conds...))
}

func (i infraJobDo) Select(conds ...field.Expr) IInfraJobDo {
	return i.withDO(i.DO.Select(conds...))
}

func (i infraJobDo) Where(conds ...gen.Condition) IInfraJobDo {
	return i.withDO(i.DO.Where(conds...))
}

func (i infraJobDo) Order(conds ...field.Expr) IInfraJobDo {
	return i.withDO(i.DO.Order(conds...))
}

func (i infraJobDo) Distinct(cols ...field.Expr) IInfraJobDo {
	return i.withDO(i.DO.Distinct(cols...))
}

func (i infraJobDo) Omit(cols ...field.Expr) IInfraJobDo {
	return i.withDO(i.DO.Omit(cols...))
}

func (i infraJobDo) Join(table schema.Tabler, on ...field.Expr) IInfraJobDo {
	return i.withDO(i.DO.Join(table, on...))
}

func (i infraJobDo) LeftJoin(table schema.Tabler, on ...field.Expr) IInfraJobDo {
	return i.withDO(i.DO.LeftJoin(table, on...))
}

func (i infraJobDo) RightJoin(table schema.Tabler, on ...field.Expr) IInfraJobDo {
	return i.withDO(i.DO.RightJoin(table, on...))
}

func (i infraJobDo) Group(cols ...field.Expr) IInfraJobDo {
	return i.withDO(i.DO.Group(cols...))
}

func (i infraJobDo) Having(conds ...gen.Condition) IInfraJobDo {
	return i.withDO(i.DO.Having(conds...))
}

func (i infraJobDo) Limit(limit int) IInfraJobDo {
	return i.withDO(i.DO.Limit(limit))
}

func (i infraJobDo) Offset(offset int) IInfraJobDo {
	return i.withDO(i.DO.Offset(offset))
}

func (i infraJobDo) Scopes(funcs ...func(gen.Dao) gen.Dao) IInfraJobDo {
	return i.withDO(i.DO.Scopes(funcs...))
}

func (i infraJobDo) Unscoped() IInfraJobDo {
	return i.withDO(i.DO.Unscoped())
}

func (i infraJobDo) Create(values ...*model.InfraJob) error {
	if len(values) == 0 {
		return nil
	}
	return i.DO.Create(values)
}

func (i infraJobDo) CreateInBatches(values []*model.InfraJob, batchSize int) error {
	return i.DO.CreateInBatches(values, batchSize)
}

// Save : !!! underlying implementation is different with GORM
// The method is equivalent to executing the statement: db.Clauses(clause.OnConflict{UpdateAll: true}).Create(values)
func (i infraJobDo) Save(values ...*model.InfraJob) error {
	if len(values) == 0 {
		return nil
	}
	return i.DO.Save(values)
}

func (i infraJobDo) First() (*model.InfraJob, error) {
	if result, err := i.DO.First(); err != nil {
		return nil, err
	} else {
		return result.(*model.InfraJob), nil
	}
}

func (i infraJobDo) Take() (*model.InfraJob, error) {
	if result, err := i.DO.Take(); err != nil {
		return nil, err
	} else {
		return result.(*model.InfraJob), nil
	}
}

func (i infraJobDo) Last() (*model.InfraJob, error) {
	if result, err := i.DO.Last(); err != nil {
		return nil, err
	} else {
		return result.(*model.InfraJob), nil
	}
}

func (i infraJobDo) Find() ([]*model.InfraJob, error) {
	result, err := i.DO.Find()
	return result.([]*model.InfraJob), err
}

func (i infraJobDo) FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.InfraJob, err error) {
	buf := make([]*model.InfraJob, 0, batchSize)
	err = i.DO.FindInBatches(&buf, batchSize, func(tx gen.Dao, batch int) error {
		defer func() { results = append(results, buf...) }()
		return fc(tx, batch)
	})
	return results, err
}

func (i infraJobDo) FindInBatches(result *[]*model.InfraJob, batchSize int, fc func(tx gen.Dao, batch int) error) error {
	return i.DO.FindInBatches(result, batchSize, fc)
}

func (i infraJobDo) Attrs(attrs ...field.AssignExpr) IInfraJobDo {
	return i.withDO(i.DO.Attrs(attrs...))
}

func (i infraJobDo) Assign(attrs ...field.AssignExpr) IInfraJobDo {
	return i.withDO(i.DO.Assign(attrs...))
}

func (i infraJobDo) Joins(fields ...field.RelationField) IInfraJobDo {
	for _, _f := range fields {
		i = *i.withDO(i.DO.Joins(_f))
	}
	return &i
}

func (i infraJobDo) Preload(fields ...field.RelationField) IInfraJobDo {
	for _, _f := range fields {
		i = *i.withDO(i.DO.Preload(_f))
	}
	return &i
}

func (i infraJobDo) FirstOrInit() (*model.InfraJob, error) {
	if result, err := i.DO.FirstOrInit(); err != nil {
		return nil, err
	} else {
		return result.(*model.InfraJob), nil
	}
}

func (i infraJobDo) FirstOrCreate() (*model.InfraJob, error) {
	if result, err := i.DO.FirstOrCreate(); err != nil {
		return nil, err
	} else {
		return result.(*model.InfraJob), nil
	}
}

func (i infraJobDo) FindByPage(offset int, limit int) (result []*model.InfraJob, count int64, err error) {
	result, err = i.Offset(offset).Limit(limit).Find()
	if err != nil {
		return
	}

	if size := len(result); 0 < limit && 0 < size && size < limit {
		count = int64(size + offset)
		return
	}

	count, err = i.Offset(-1).Limit(-1).Count()
	return
}

func (i infraJobDo) ScanByPage(result interface{}, offset int, limit int) (count int64, err error) {
	count, err = i.Count()
	if err != nil {
		return
	}

	err = i.Offset(offset).Limit(limit).Scan(result)
	return
}

func (i infraJobDo) Scan(result interface{}) (err error) {
	return i.DO.Scan(result)
}

func (i infraJobDo) Delete(models ...*model.InfraJob) (result gen.ResultInfo, err error) {
	return i.DO.Delete(models)
}

func (i *infraJobDo) withDO(do gen.Dao) *infraJobDo {
	i.DO = *do.(*gen.DO)
	return i
}
