// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package query

import (
	"context"
	"database/sql"

	"gorm.io/gorm"
	"gorm.io/gorm/clause"
	"gorm.io/gorm/schema"

	"gorm.io/gen"
	"gorm.io/gen/field"

	"gorm.io/plugin/dbresolver"

	"backend-go/internal/model"
)

func newInfraFile(db *gorm.DB, opts ...gen.DOOption) infraFile {
	_infraFile := infraFile{}

	_infraFile.infraFileDo.UseDB(db, opts...)
	_infraFile.infraFileDo.UseModel(&model.InfraFile{})

	tableName := _infraFile.infraFileDo.TableName()
	_infraFile.ALL = field.NewAsterisk(tableName)
	_infraFile.ID = field.NewInt64(tableName, "id")
	_infraFile.ConfigId = field.NewInt64(tableName, "config_id")
	_infraFile.Name = field.NewString(tableName, "name")
	_infraFile.Path = field.NewString(tableName, "path")
	_infraFile.Url = field.NewString(tableName, "url")
	_infraFile.Type = field.NewString(tableName, "type")
	_infraFile.Size = field.NewInt(tableName, "size")
	_infraFile.Creator = field.NewString(tableName, "creator")
	_infraFile.Updater = field.NewString(tableName, "updater")
	_infraFile.CreatedAt = field.NewTime(tableName, "create_time")
	_infraFile.UpdatedAt = field.NewTime(tableName, "update_time")
	_infraFile.Deleted = field.NewField(tableName, "deleted")

	_infraFile.fillFieldMap()

	return _infraFile
}

type infraFile struct {
	infraFileDo infraFileDo

	ALL       field.Asterisk
	ID        field.Int64  // 文件编号
	ConfigId  field.Int64  // 配置编号
	Name      field.String // 原文件名
	Path      field.String // 路径
	Url       field.String // 访问地址
	Type      field.String // 文件类型
	Size      field.Int    // 文件大小
	Creator   field.String // 创建者
	Updater   field.String // 更新者
	CreatedAt field.Time   // 创建时间
	UpdatedAt field.Time   // 更新时间
	Deleted   field.Field  // 是否删除

	fieldMap map[string]field.Expr
}

func (i infraFile) Table(newTableName string) *infraFile {
	i.infraFileDo.UseTable(newTableName)
	return i.updateTableName(newTableName)
}

func (i infraFile) As(alias string) *infraFile {
	i.infraFileDo.DO = *(i.infraFileDo.As(alias).(*gen.DO))
	return i.updateTableName(alias)
}

func (i *infraFile) updateTableName(table string) *infraFile {
	i.ALL = field.NewAsterisk(table)
	i.ID = field.NewInt64(table, "id")
	i.ConfigId = field.NewInt64(table, "config_id")
	i.Name = field.NewString(table, "name")
	i.Path = field.NewString(table, "path")
	i.Url = field.NewString(table, "url")
	i.Type = field.NewString(table, "type")
	i.Size = field.NewInt(table, "size")
	i.Creator = field.NewString(table, "creator")
	i.Updater = field.NewString(table, "updater")
	i.CreatedAt = field.NewTime(table, "create_time")
	i.UpdatedAt = field.NewTime(table, "update_time")
	i.Deleted = field.NewField(table, "deleted")

	i.fillFieldMap()

	return i
}

func (i *infraFile) WithContext(ctx context.Context) IInfraFileDo {
	return i.infraFileDo.WithContext(ctx)
}

func (i infraFile) TableName() string { return i.infraFileDo.TableName() }

func (i infraFile) Alias() string { return i.infraFileDo.Alias() }

func (i infraFile) Columns(cols ...field.Expr) gen.Columns { return i.infraFileDo.Columns(cols...) }

func (i *infraFile) GetFieldByName(fieldName string) (field.OrderExpr, bool) {
	_f, ok := i.fieldMap[fieldName]
	if !ok || _f == nil {
		return nil, false
	}
	_oe, ok := _f.(field.OrderExpr)
	return _oe, ok
}

func (i *infraFile) fillFieldMap() {
	i.fieldMap = make(map[string]field.Expr, 12)
	i.fieldMap["id"] = i.ID
	i.fieldMap["config_id"] = i.ConfigId
	i.fieldMap["name"] = i.Name
	i.fieldMap["path"] = i.Path
	i.fieldMap["url"] = i.Url
	i.fieldMap["type"] = i.Type
	i.fieldMap["size"] = i.Size
	i.fieldMap["creator"] = i.Creator
	i.fieldMap["updater"] = i.Updater
	i.fieldMap["create_time"] = i.CreatedAt
	i.fieldMap["update_time"] = i.UpdatedAt
	i.fieldMap["deleted"] = i.Deleted
}

func (i infraFile) clone(db *gorm.DB) infraFile {
	i.infraFileDo.ReplaceConnPool(db.Statement.ConnPool)
	return i
}

func (i infraFile) replaceDB(db *gorm.DB) infraFile {
	i.infraFileDo.ReplaceDB(db)
	return i
}

type infraFileDo struct{ gen.DO }

type IInfraFileDo interface {
	gen.SubQuery
	Debug() IInfraFileDo
	WithContext(ctx context.Context) IInfraFileDo
	WithResult(fc func(tx gen.Dao)) gen.ResultInfo
	ReplaceDB(db *gorm.DB)
	ReadDB() IInfraFileDo
	WriteDB() IInfraFileDo
	As(alias string) gen.Dao
	Session(config *gorm.Session) IInfraFileDo
	Columns(cols ...field.Expr) gen.Columns
	Clauses(conds ...clause.Expression) IInfraFileDo
	Not(conds ...gen.Condition) IInfraFileDo
	Or(conds ...gen.Condition) IInfraFileDo
	Select(conds ...field.Expr) IInfraFileDo
	Where(conds ...gen.Condition) IInfraFileDo
	Order(conds ...field.Expr) IInfraFileDo
	Distinct(cols ...field.Expr) IInfraFileDo
	Omit(cols ...field.Expr) IInfraFileDo
	Join(table schema.Tabler, on ...field.Expr) IInfraFileDo
	LeftJoin(table schema.Tabler, on ...field.Expr) IInfraFileDo
	RightJoin(table schema.Tabler, on ...field.Expr) IInfraFileDo
	Group(cols ...field.Expr) IInfraFileDo
	Having(conds ...gen.Condition) IInfraFileDo
	Limit(limit int) IInfraFileDo
	Offset(offset int) IInfraFileDo
	Count() (count int64, err error)
	Scopes(funcs ...func(gen.Dao) gen.Dao) IInfraFileDo
	Unscoped() IInfraFileDo
	Create(values ...*model.InfraFile) error
	CreateInBatches(values []*model.InfraFile, batchSize int) error
	Save(values ...*model.InfraFile) error
	First() (*model.InfraFile, error)
	Take() (*model.InfraFile, error)
	Last() (*model.InfraFile, error)
	Find() ([]*model.InfraFile, error)
	FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.InfraFile, err error)
	FindInBatches(result *[]*model.InfraFile, batchSize int, fc func(tx gen.Dao, batch int) error) error
	Pluck(column field.Expr, dest interface{}) error
	Delete(...*model.InfraFile) (info gen.ResultInfo, err error)
	Update(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	Updates(value interface{}) (info gen.ResultInfo, err error)
	UpdateColumn(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateColumnSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	UpdateColumns(value interface{}) (info gen.ResultInfo, err error)
	UpdateFrom(q gen.SubQuery) gen.Dao
	Attrs(attrs ...field.AssignExpr) IInfraFileDo
	Assign(attrs ...field.AssignExpr) IInfraFileDo
	Joins(fields ...field.RelationField) IInfraFileDo
	Preload(fields ...field.RelationField) IInfraFileDo
	FirstOrInit() (*model.InfraFile, error)
	FirstOrCreate() (*model.InfraFile, error)
	FindByPage(offset int, limit int) (result []*model.InfraFile, count int64, err error)
	ScanByPage(result interface{}, offset int, limit int) (count int64, err error)
	Rows() (*sql.Rows, error)
	Row() *sql.Row
	Scan(result interface{}) (err error)
	Returning(value interface{}, columns ...string) IInfraFileDo
	UnderlyingDB() *gorm.DB
	schema.Tabler
}

func (i infraFileDo) Debug() IInfraFileDo {
	return i.withDO(i.DO.Debug())
}

func (i infraFileDo) WithContext(ctx context.Context) IInfraFileDo {
	return i.withDO(i.DO.WithContext(ctx))
}

func (i infraFileDo) ReadDB() IInfraFileDo {
	return i.Clauses(dbresolver.Read)
}

func (i infraFileDo) WriteDB() IInfraFileDo {
	return i.Clauses(dbresolver.Write)
}

func (i infraFileDo) Session(config *gorm.Session) IInfraFileDo {
	return i.withDO(i.DO.Session(config))
}

func (i infraFileDo) Clauses(conds ...clause.Expression) IInfraFileDo {
	return i.withDO(i.DO.Clauses(conds...))
}

func (i infraFileDo) Returning(value interface{}, columns ...string) IInfraFileDo {
	return i.withDO(i.DO.Returning(value, columns...))
}

func (i infraFileDo) Not(conds ...gen.Condition) IInfraFileDo {
	return i.withDO(i.DO.Not(conds...))
}

func (i infraFileDo) Or(conds ...gen.Condition) IInfraFileDo {
	return i.withDO(i.DO.Or(conds...))
}

func (i infraFileDo) Select(conds ...field.Expr) IInfraFileDo {
	return i.withDO(i.DO.Select(conds...))
}

func (i infraFileDo) Where(conds ...gen.Condition) IInfraFileDo {
	return i.withDO(i.DO.Where(conds...))
}

func (i infraFileDo) Order(conds ...field.Expr) IInfraFileDo {
	return i.withDO(i.DO.Order(conds...))
}

func (i infraFileDo) Distinct(cols ...field.Expr) IInfraFileDo {
	return i.withDO(i.DO.Distinct(cols...))
}

func (i infraFileDo) Omit(cols ...field.Expr) IInfraFileDo {
	return i.withDO(i.DO.Omit(cols...))
}

func (i infraFileDo) Join(table schema.Tabler, on ...field.Expr) IInfraFileDo {
	return i.withDO(i.DO.Join(table, on...))
}

func (i infraFileDo) LeftJoin(table schema.Tabler, on ...field.Expr) IInfraFileDo {
	return i.withDO(i.DO.LeftJoin(table, on...))
}

func (i infraFileDo) RightJoin(table schema.Tabler, on ...field.Expr) IInfraFileDo {
	return i.withDO(i.DO.RightJoin(table, on...))
}

func (i infraFileDo) Group(cols ...field.Expr) IInfraFileDo {
	return i.withDO(i.DO.Group(cols...))
}

func (i infraFileDo) Having(conds ...gen.Condition) IInfraFileDo {
	return i.withDO(i.DO.Having(conds...))
}

func (i infraFileDo) Limit(limit int) IInfraFileDo {
	return i.withDO(i.DO.Limit(limit))
}

func (i infraFileDo) Offset(offset int) IInfraFileDo {
	return i.withDO(i.DO.Offset(offset))
}

func (i infraFileDo) Scopes(funcs ...func(gen.Dao) gen.Dao) IInfraFileDo {
	return i.withDO(i.DO.Scopes(funcs...))
}

func (i infraFileDo) Unscoped() IInfraFileDo {
	return i.withDO(i.DO.Unscoped())
}

func (i infraFileDo) Create(values ...*model.InfraFile) error {
	if len(values) == 0 {
		return nil
	}
	return i.DO.Create(values)
}

func (i infraFileDo) CreateInBatches(values []*model.InfraFile, batchSize int) error {
	return i.DO.CreateInBatches(values, batchSize)
}

// Save : !!! underlying implementation is different with GORM
// The method is equivalent to executing the statement: db.Clauses(clause.OnConflict{UpdateAll: true}).Create(values)
func (i infraFileDo) Save(values ...*model.InfraFile) error {
	if len(values) == 0 {
		return nil
	}
	return i.DO.Save(values)
}

func (i infraFileDo) First() (*model.InfraFile, error) {
	if result, err := i.DO.First(); err != nil {
		return nil, err
	} else {
		return result.(*model.InfraFile), nil
	}
}

func (i infraFileDo) Take() (*model.InfraFile, error) {
	if result, err := i.DO.Take(); err != nil {
		return nil, err
	} else {
		return result.(*model.InfraFile), nil
	}
}

func (i infraFileDo) Last() (*model.InfraFile, error) {
	if result, err := i.DO.Last(); err != nil {
		return nil, err
	} else {
		return result.(*model.InfraFile), nil
	}
}

func (i infraFileDo) Find() ([]*model.InfraFile, error) {
	result, err := i.DO.Find()
	return result.([]*model.InfraFile), err
}

func (i infraFileDo) FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.InfraFile, err error) {
	buf := make([]*model.InfraFile, 0, batchSize)
	err = i.DO.FindInBatches(&buf, batchSize, func(tx gen.Dao, batch int) error {
		defer func() { results = append(results, buf...) }()
		return fc(tx, batch)
	})
	return results, err
}

func (i infraFileDo) FindInBatches(result *[]*model.InfraFile, batchSize int, fc func(tx gen.Dao, batch int) error) error {
	return i.DO.FindInBatches(result, batchSize, fc)
}

func (i infraFileDo) Attrs(attrs ...field.AssignExpr) IInfraFileDo {
	return i.withDO(i.DO.Attrs(attrs...))
}

func (i infraFileDo) Assign(attrs ...field.AssignExpr) IInfraFileDo {
	return i.withDO(i.DO.Assign(attrs...))
}

func (i infraFileDo) Joins(fields ...field.RelationField) IInfraFileDo {
	for _, _f := range fields {
		i = *i.withDO(i.DO.Joins(_f))
	}
	return &i
}

func (i infraFileDo) Preload(fields ...field.RelationField) IInfraFileDo {
	for _, _f := range fields {
		i = *i.withDO(i.DO.Preload(_f))
	}
	return &i
}

func (i infraFileDo) FirstOrInit() (*model.InfraFile, error) {
	if result, err := i.DO.FirstOrInit(); err != nil {
		return nil, err
	} else {
		return result.(*model.InfraFile), nil
	}
}

func (i infraFileDo) FirstOrCreate() (*model.InfraFile, error) {
	if result, err := i.DO.FirstOrCreate(); err != nil {
		return nil, err
	} else {
		return result.(*model.InfraFile), nil
	}
}

func (i infraFileDo) FindByPage(offset int, limit int) (result []*model.InfraFile, count int64, err error) {
	result, err = i.Offset(offset).Limit(limit).Find()
	if err != nil {
		return
	}

	if size := len(result); 0 < limit && 0 < size && size < limit {
		count = int64(size + offset)
		return
	}

	count, err = i.Offset(-1).Limit(-1).Count()
	return
}

func (i infraFileDo) ScanByPage(result interface{}, offset int, limit int) (count int64, err error) {
	count, err = i.Count()
	if err != nil {
		return
	}

	err = i.Offset(offset).Limit(limit).Scan(result)
	return
}

func (i infraFileDo) Scan(result interface{}) (err error) {
	return i.DO.Scan(result)
}

func (i infraFileDo) Delete(models ...*model.InfraFile) (result gen.ResultInfo, err error) {
	return i.DO.Delete(models)
}

func (i *infraFileDo) withDO(do gen.Dao) *infraFileDo {
	i.DO = *do.(*gen.DO)
	return i
}
