// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package query

import (
	"backend-go/internal/model/product"
	"context"
	"database/sql"

	"gorm.io/gorm"
	"gorm.io/gorm/clause"
	"gorm.io/gorm/schema"

	"gorm.io/gen"
	"gorm.io/gen/field"

	"gorm.io/plugin/dbresolver"
)

func newProductFavorite(db *gorm.DB, opts ...gen.DOOption) productFavorite {
	_productFavorite := productFavorite{}

	_productFavorite.productFavoriteDo.UseDB(db, opts...)
	_productFavorite.productFavoriteDo.UseModel(&product.ProductFavorite{})

	tableName := _productFavorite.productFavoriteDo.TableName()
	_productFavorite.ALL = field.NewAsterisk(tableName)
	_productFavorite.ID = field.NewInt64(tableName, "id")
	_productFavorite.UserID = field.NewInt64(tableName, "user_id")
	_productFavorite.SpuID = field.NewInt64(tableName, "spu_id")
	_productFavorite.CreatedAt = field.NewTime(tableName, "created_at")
	_productFavorite.UpdatedAt = field.NewTime(tableName, "updated_at")
	_productFavorite.DeletedAt = field.NewInt64(tableName, "deleted_at")
	_productFavorite.Deleted = field.NewBool(tableName, "deleted")

	_productFavorite.fillFieldMap()

	return _productFavorite
}

type productFavorite struct {
	productFavoriteDo productFavoriteDo

	ALL       field.Asterisk
	ID        field.Int64 // 编号
	UserID    field.Int64 // 用户编号
	SpuID     field.Int64 // 商品 SPU 编号
	CreatedAt field.Time  // 创建时间
	UpdatedAt field.Time  // 更新时间
	DeletedAt field.Int64 // 删除时间
	Deleted   field.Bool  // 是否删除

	fieldMap map[string]field.Expr
}

func (p productFavorite) Table(newTableName string) *productFavorite {
	p.productFavoriteDo.UseTable(newTableName)
	return p.updateTableName(newTableName)
}

func (p productFavorite) As(alias string) *productFavorite {
	p.productFavoriteDo.DO = *(p.productFavoriteDo.As(alias).(*gen.DO))
	return p.updateTableName(alias)
}

func (p *productFavorite) updateTableName(table string) *productFavorite {
	p.ALL = field.NewAsterisk(table)
	p.ID = field.NewInt64(table, "id")
	p.UserID = field.NewInt64(table, "user_id")
	p.SpuID = field.NewInt64(table, "spu_id")
	p.CreatedAt = field.NewTime(table, "created_at")
	p.UpdatedAt = field.NewTime(table, "updated_at")
	p.DeletedAt = field.NewInt64(table, "deleted_at")
	p.Deleted = field.NewBool(table, "deleted")

	p.fillFieldMap()

	return p
}

func (p *productFavorite) WithContext(ctx context.Context) IProductFavoriteDo {
	return p.productFavoriteDo.WithContext(ctx)
}

func (p productFavorite) TableName() string { return p.productFavoriteDo.TableName() }

func (p productFavorite) Alias() string { return p.productFavoriteDo.Alias() }

func (p productFavorite) Columns(cols ...field.Expr) gen.Columns {
	return p.productFavoriteDo.Columns(cols...)
}

func (p *productFavorite) GetFieldByName(fieldName string) (field.OrderExpr, bool) {
	_f, ok := p.fieldMap[fieldName]
	if !ok || _f == nil {
		return nil, false
	}
	_oe, ok := _f.(field.OrderExpr)
	return _oe, ok
}

func (p *productFavorite) fillFieldMap() {
	p.fieldMap = make(map[string]field.Expr, 7)
	p.fieldMap["id"] = p.ID
	p.fieldMap["user_id"] = p.UserID
	p.fieldMap["spu_id"] = p.SpuID
	p.fieldMap["created_at"] = p.CreatedAt
	p.fieldMap["updated_at"] = p.UpdatedAt
	p.fieldMap["deleted_at"] = p.DeletedAt
	p.fieldMap["deleted"] = p.Deleted
}

func (p productFavorite) clone(db *gorm.DB) productFavorite {
	p.productFavoriteDo.ReplaceConnPool(db.Statement.ConnPool)
	return p
}

func (p productFavorite) replaceDB(db *gorm.DB) productFavorite {
	p.productFavoriteDo.ReplaceDB(db)
	return p
}

type productFavoriteDo struct{ gen.DO }

type IProductFavoriteDo interface {
	gen.SubQuery
	Debug() IProductFavoriteDo
	WithContext(ctx context.Context) IProductFavoriteDo
	WithResult(fc func(tx gen.Dao)) gen.ResultInfo
	ReplaceDB(db *gorm.DB)
	ReadDB() IProductFavoriteDo
	WriteDB() IProductFavoriteDo
	As(alias string) gen.Dao
	Session(config *gorm.Session) IProductFavoriteDo
	Columns(cols ...field.Expr) gen.Columns
	Clauses(conds ...clause.Expression) IProductFavoriteDo
	Not(conds ...gen.Condition) IProductFavoriteDo
	Or(conds ...gen.Condition) IProductFavoriteDo
	Select(conds ...field.Expr) IProductFavoriteDo
	Where(conds ...gen.Condition) IProductFavoriteDo
	Order(conds ...field.Expr) IProductFavoriteDo
	Distinct(cols ...field.Expr) IProductFavoriteDo
	Omit(cols ...field.Expr) IProductFavoriteDo
	Join(table schema.Tabler, on ...field.Expr) IProductFavoriteDo
	LeftJoin(table schema.Tabler, on ...field.Expr) IProductFavoriteDo
	RightJoin(table schema.Tabler, on ...field.Expr) IProductFavoriteDo
	Group(cols ...field.Expr) IProductFavoriteDo
	Having(conds ...gen.Condition) IProductFavoriteDo
	Limit(limit int) IProductFavoriteDo
	Offset(offset int) IProductFavoriteDo
	Count() (count int64, err error)
	Scopes(funcs ...func(gen.Dao) gen.Dao) IProductFavoriteDo
	Unscoped() IProductFavoriteDo
	Create(values ...*product.ProductFavorite) error
	CreateInBatches(values []*product.ProductFavorite, batchSize int) error
	Save(values ...*product.ProductFavorite) error
	First() (*product.ProductFavorite, error)
	Take() (*product.ProductFavorite, error)
	Last() (*product.ProductFavorite, error)
	Find() ([]*product.ProductFavorite, error)
	FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*product.ProductFavorite, err error)
	FindInBatches(result *[]*product.ProductFavorite, batchSize int, fc func(tx gen.Dao, batch int) error) error
	Pluck(column field.Expr, dest interface{}) error
	Delete(...*product.ProductFavorite) (info gen.ResultInfo, err error)
	Update(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	Updates(value interface{}) (info gen.ResultInfo, err error)
	UpdateColumn(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateColumnSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	UpdateColumns(value interface{}) (info gen.ResultInfo, err error)
	UpdateFrom(q gen.SubQuery) gen.Dao
	Attrs(attrs ...field.AssignExpr) IProductFavoriteDo
	Assign(attrs ...field.AssignExpr) IProductFavoriteDo
	Joins(fields ...field.RelationField) IProductFavoriteDo
	Preload(fields ...field.RelationField) IProductFavoriteDo
	FirstOrInit() (*product.ProductFavorite, error)
	FirstOrCreate() (*product.ProductFavorite, error)
	FindByPage(offset int, limit int) (result []*product.ProductFavorite, count int64, err error)
	ScanByPage(result interface{}, offset int, limit int) (count int64, err error)
	Rows() (*sql.Rows, error)
	Row() *sql.Row
	Scan(result interface{}) (err error)
	Returning(value interface{}, columns ...string) IProductFavoriteDo
	UnderlyingDB() *gorm.DB
	schema.Tabler
}

func (p productFavoriteDo) Debug() IProductFavoriteDo {
	return p.withDO(p.DO.Debug())
}

func (p productFavoriteDo) WithContext(ctx context.Context) IProductFavoriteDo {
	return p.withDO(p.DO.WithContext(ctx))
}

func (p productFavoriteDo) ReadDB() IProductFavoriteDo {
	return p.Clauses(dbresolver.Read)
}

func (p productFavoriteDo) WriteDB() IProductFavoriteDo {
	return p.Clauses(dbresolver.Write)
}

func (p productFavoriteDo) Session(config *gorm.Session) IProductFavoriteDo {
	return p.withDO(p.DO.Session(config))
}

func (p productFavoriteDo) Clauses(conds ...clause.Expression) IProductFavoriteDo {
	return p.withDO(p.DO.Clauses(conds...))
}

func (p productFavoriteDo) Returning(value interface{}, columns ...string) IProductFavoriteDo {
	return p.withDO(p.DO.Returning(value, columns...))
}

func (p productFavoriteDo) Not(conds ...gen.Condition) IProductFavoriteDo {
	return p.withDO(p.DO.Not(conds...))
}

func (p productFavoriteDo) Or(conds ...gen.Condition) IProductFavoriteDo {
	return p.withDO(p.DO.Or(conds...))
}

func (p productFavoriteDo) Select(conds ...field.Expr) IProductFavoriteDo {
	return p.withDO(p.DO.Select(conds...))
}

func (p productFavoriteDo) Where(conds ...gen.Condition) IProductFavoriteDo {
	return p.withDO(p.DO.Where(conds...))
}

func (p productFavoriteDo) Order(conds ...field.Expr) IProductFavoriteDo {
	return p.withDO(p.DO.Order(conds...))
}

func (p productFavoriteDo) Distinct(cols ...field.Expr) IProductFavoriteDo {
	return p.withDO(p.DO.Distinct(cols...))
}

func (p productFavoriteDo) Omit(cols ...field.Expr) IProductFavoriteDo {
	return p.withDO(p.DO.Omit(cols...))
}

func (p productFavoriteDo) Join(table schema.Tabler, on ...field.Expr) IProductFavoriteDo {
	return p.withDO(p.DO.Join(table, on...))
}

func (p productFavoriteDo) LeftJoin(table schema.Tabler, on ...field.Expr) IProductFavoriteDo {
	return p.withDO(p.DO.LeftJoin(table, on...))
}

func (p productFavoriteDo) RightJoin(table schema.Tabler, on ...field.Expr) IProductFavoriteDo {
	return p.withDO(p.DO.RightJoin(table, on...))
}

func (p productFavoriteDo) Group(cols ...field.Expr) IProductFavoriteDo {
	return p.withDO(p.DO.Group(cols...))
}

func (p productFavoriteDo) Having(conds ...gen.Condition) IProductFavoriteDo {
	return p.withDO(p.DO.Having(conds...))
}

func (p productFavoriteDo) Limit(limit int) IProductFavoriteDo {
	return p.withDO(p.DO.Limit(limit))
}

func (p productFavoriteDo) Offset(offset int) IProductFavoriteDo {
	return p.withDO(p.DO.Offset(offset))
}

func (p productFavoriteDo) Scopes(funcs ...func(gen.Dao) gen.Dao) IProductFavoriteDo {
	return p.withDO(p.DO.Scopes(funcs...))
}

func (p productFavoriteDo) Unscoped() IProductFavoriteDo {
	return p.withDO(p.DO.Unscoped())
}

func (p productFavoriteDo) Create(values ...*product.ProductFavorite) error {
	if len(values) == 0 {
		return nil
	}
	return p.DO.Create(values)
}

func (p productFavoriteDo) CreateInBatches(values []*product.ProductFavorite, batchSize int) error {
	return p.DO.CreateInBatches(values, batchSize)
}

// Save : !!! underlying implementation is different with GORM
// The method is equivalent to executing the statement: db.Clauses(clause.OnConflict{UpdateAll: true}).Create(values)
func (p productFavoriteDo) Save(values ...*product.ProductFavorite) error {
	if len(values) == 0 {
		return nil
	}
	return p.DO.Save(values)
}

func (p productFavoriteDo) First() (*product.ProductFavorite, error) {
	if result, err := p.DO.First(); err != nil {
		return nil, err
	} else {
		return result.(*product.ProductFavorite), nil
	}
}

func (p productFavoriteDo) Take() (*product.ProductFavorite, error) {
	if result, err := p.DO.Take(); err != nil {
		return nil, err
	} else {
		return result.(*product.ProductFavorite), nil
	}
}

func (p productFavoriteDo) Last() (*product.ProductFavorite, error) {
	if result, err := p.DO.Last(); err != nil {
		return nil, err
	} else {
		return result.(*product.ProductFavorite), nil
	}
}

func (p productFavoriteDo) Find() ([]*product.ProductFavorite, error) {
	result, err := p.DO.Find()
	return result.([]*product.ProductFavorite), err
}

func (p productFavoriteDo) FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*product.ProductFavorite, err error) {
	buf := make([]*product.ProductFavorite, 0, batchSize)
	err = p.DO.FindInBatches(&buf, batchSize, func(tx gen.Dao, batch int) error {
		defer func() { results = append(results, buf...) }()
		return fc(tx, batch)
	})
	return results, err
}

func (p productFavoriteDo) FindInBatches(result *[]*product.ProductFavorite, batchSize int, fc func(tx gen.Dao, batch int) error) error {
	return p.DO.FindInBatches(result, batchSize, fc)
}

func (p productFavoriteDo) Attrs(attrs ...field.AssignExpr) IProductFavoriteDo {
	return p.withDO(p.DO.Attrs(attrs...))
}

func (p productFavoriteDo) Assign(attrs ...field.AssignExpr) IProductFavoriteDo {
	return p.withDO(p.DO.Assign(attrs...))
}

func (p productFavoriteDo) Joins(fields ...field.RelationField) IProductFavoriteDo {
	for _, _f := range fields {
		p = *p.withDO(p.DO.Joins(_f))
	}
	return &p
}

func (p productFavoriteDo) Preload(fields ...field.RelationField) IProductFavoriteDo {
	for _, _f := range fields {
		p = *p.withDO(p.DO.Preload(_f))
	}
	return &p
}

func (p productFavoriteDo) FirstOrInit() (*product.ProductFavorite, error) {
	if result, err := p.DO.FirstOrInit(); err != nil {
		return nil, err
	} else {
		return result.(*product.ProductFavorite), nil
	}
}

func (p productFavoriteDo) FirstOrCreate() (*product.ProductFavorite, error) {
	if result, err := p.DO.FirstOrCreate(); err != nil {
		return nil, err
	} else {
		return result.(*product.ProductFavorite), nil
	}
}

func (p productFavoriteDo) FindByPage(offset int, limit int) (result []*product.ProductFavorite, count int64, err error) {
	result, err = p.Offset(offset).Limit(limit).Find()
	if err != nil {
		return
	}

	if size := len(result); 0 < limit && 0 < size && size < limit {
		count = int64(size + offset)
		return
	}

	count, err = p.Offset(-1).Limit(-1).Count()
	return
}

func (p productFavoriteDo) ScanByPage(result interface{}, offset int, limit int) (count int64, err error) {
	count, err = p.Count()
	if err != nil {
		return
	}

	err = p.Offset(offset).Limit(limit).Scan(result)
	return
}

func (p productFavoriteDo) Scan(result interface{}) (err error) {
	return p.DO.Scan(result)
}

func (p productFavoriteDo) Delete(models ...*product.ProductFavorite) (result gen.ResultInfo, err error) {
	return p.DO.Delete(models)
}

func (p *productFavoriteDo) withDO(do gen.Dao) *productFavoriteDo {
	p.DO = *do.(*gen.DO)
	return p
}
