// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package query

import (
	"context"
	"database/sql"

	"gorm.io/gorm"
	"gorm.io/gorm/clause"
	"gorm.io/gorm/schema"

	"gorm.io/gen"
	"gorm.io/gen/field"

	"gorm.io/plugin/dbresolver"

	"backend-go/internal/model/product"
)

func newProductStatistics(db *gorm.DB, opts ...gen.DOOption) productStatistics {
	_productStatistics := productStatistics{}

	_productStatistics.productStatisticsDo.UseDB(db, opts...)
	_productStatistics.productStatisticsDo.UseModel(&product.ProductStatistics{})

	tableName := _productStatistics.productStatisticsDo.TableName()
	_productStatistics.ALL = field.NewAsterisk(tableName)
	_productStatistics.ID = field.NewInt64(tableName, "id")
	_productStatistics.Time = field.NewTime(tableName, "time")
	_productStatistics.SpuID = field.NewInt64(tableName, "spu_id")
	_productStatistics.BrowseCount = field.NewInt(tableName, "browse_count")
	_productStatistics.BrowseUserCount = field.NewInt(tableName, "browse_user_count")
	_productStatistics.FavoriteCount = field.NewInt(tableName, "favorite_count")
	_productStatistics.CartCount = field.NewInt(tableName, "cart_count")
	_productStatistics.OrderCount = field.NewInt(tableName, "order_count")
	_productStatistics.OrderPayCount = field.NewInt(tableName, "order_pay_count")
	_productStatistics.OrderPayPrice = field.NewInt(tableName, "order_pay_price")
	_productStatistics.AfterSaleCount = field.NewInt(tableName, "after_sale_count")
	_productStatistics.AfterSaleRefundPrice = field.NewInt(tableName, "after_sale_refund_price")
	_productStatistics.BrowseConvertPercent = field.NewInt(tableName, "browse_convert_percent")
	_productStatistics.Creator = field.NewString(tableName, "creator")
	_productStatistics.Updater = field.NewString(tableName, "updater")
	_productStatistics.CreatedAt = field.NewTime(tableName, "create_time")
	_productStatistics.UpdatedAt = field.NewTime(tableName, "update_time")
	_productStatistics.Deleted = field.NewBool(tableName, "deleted")

	_productStatistics.fillFieldMap()

	return _productStatistics
}

type productStatistics struct {
	productStatisticsDo productStatisticsDo

	ALL                  field.Asterisk
	ID                   field.Int64  // 编号
	Time                 field.Time   // 统计日期
	SpuID                field.Int64  // 商品SPU编号
	BrowseCount          field.Int    // 浏览量
	BrowseUserCount      field.Int    // 访客量
	FavoriteCount        field.Int    // 收藏数量
	CartCount            field.Int    // 加购数量
	OrderCount           field.Int    // 下单件数
	OrderPayCount        field.Int    // 支付件数
	OrderPayPrice        field.Int    // 支付金额(分)
	AfterSaleCount       field.Int    // 退款件数
	AfterSaleRefundPrice field.Int    // 退款金额(分)
	BrowseConvertPercent field.Int    // 访客支付转化率(百分比)
	Creator              field.String // 创建者
	Updater              field.String // 更新者
	CreatedAt            field.Time   // 创建时间
	UpdatedAt            field.Time   // 更新时间
	Deleted              field.Bool   // 是否删除

	fieldMap map[string]field.Expr
}

func (p productStatistics) Table(newTableName string) *productStatistics {
	p.productStatisticsDo.UseTable(newTableName)
	return p.updateTableName(newTableName)
}

func (p productStatistics) As(alias string) *productStatistics {
	p.productStatisticsDo.DO = *(p.productStatisticsDo.As(alias).(*gen.DO))
	return p.updateTableName(alias)
}

func (p *productStatistics) updateTableName(table string) *productStatistics {
	p.ALL = field.NewAsterisk(table)
	p.ID = field.NewInt64(table, "id")
	p.Time = field.NewTime(table, "time")
	p.SpuID = field.NewInt64(table, "spu_id")
	p.BrowseCount = field.NewInt(table, "browse_count")
	p.BrowseUserCount = field.NewInt(table, "browse_user_count")
	p.FavoriteCount = field.NewInt(table, "favorite_count")
	p.CartCount = field.NewInt(table, "cart_count")
	p.OrderCount = field.NewInt(table, "order_count")
	p.OrderPayCount = field.NewInt(table, "order_pay_count")
	p.OrderPayPrice = field.NewInt(table, "order_pay_price")
	p.AfterSaleCount = field.NewInt(table, "after_sale_count")
	p.AfterSaleRefundPrice = field.NewInt(table, "after_sale_refund_price")
	p.BrowseConvertPercent = field.NewInt(table, "browse_convert_percent")
	p.Creator = field.NewString(table, "creator")
	p.Updater = field.NewString(table, "updater")
	p.CreatedAt = field.NewTime(table, "create_time")
	p.UpdatedAt = field.NewTime(table, "update_time")
	p.Deleted = field.NewBool(table, "deleted")

	p.fillFieldMap()

	return p
}

func (p *productStatistics) WithContext(ctx context.Context) IProductStatisticsDo {
	return p.productStatisticsDo.WithContext(ctx)
}

func (p productStatistics) TableName() string { return p.productStatisticsDo.TableName() }

func (p productStatistics) Alias() string { return p.productStatisticsDo.Alias() }

func (p productStatistics) Columns(cols ...field.Expr) gen.Columns {
	return p.productStatisticsDo.Columns(cols...)
}

func (p *productStatistics) GetFieldByName(fieldName string) (field.OrderExpr, bool) {
	_f, ok := p.fieldMap[fieldName]
	if !ok || _f == nil {
		return nil, false
	}
	_oe, ok := _f.(field.OrderExpr)
	return _oe, ok
}

func (p *productStatistics) fillFieldMap() {
	p.fieldMap = make(map[string]field.Expr, 18)
	p.fieldMap["id"] = p.ID
	p.fieldMap["time"] = p.Time
	p.fieldMap["spu_id"] = p.SpuID
	p.fieldMap["browse_count"] = p.BrowseCount
	p.fieldMap["browse_user_count"] = p.BrowseUserCount
	p.fieldMap["favorite_count"] = p.FavoriteCount
	p.fieldMap["cart_count"] = p.CartCount
	p.fieldMap["order_count"] = p.OrderCount
	p.fieldMap["order_pay_count"] = p.OrderPayCount
	p.fieldMap["order_pay_price"] = p.OrderPayPrice
	p.fieldMap["after_sale_count"] = p.AfterSaleCount
	p.fieldMap["after_sale_refund_price"] = p.AfterSaleRefundPrice
	p.fieldMap["browse_convert_percent"] = p.BrowseConvertPercent
	p.fieldMap["creator"] = p.Creator
	p.fieldMap["updater"] = p.Updater
	p.fieldMap["create_time"] = p.CreatedAt
	p.fieldMap["update_time"] = p.UpdatedAt
	p.fieldMap["deleted"] = p.Deleted
}

func (p productStatistics) clone(db *gorm.DB) productStatistics {
	p.productStatisticsDo.ReplaceConnPool(db.Statement.ConnPool)
	return p
}

func (p productStatistics) replaceDB(db *gorm.DB) productStatistics {
	p.productStatisticsDo.ReplaceDB(db)
	return p
}

type productStatisticsDo struct{ gen.DO }

type IProductStatisticsDo interface {
	gen.SubQuery
	Debug() IProductStatisticsDo
	WithContext(ctx context.Context) IProductStatisticsDo
	WithResult(fc func(tx gen.Dao)) gen.ResultInfo
	ReplaceDB(db *gorm.DB)
	ReadDB() IProductStatisticsDo
	WriteDB() IProductStatisticsDo
	As(alias string) gen.Dao
	Session(config *gorm.Session) IProductStatisticsDo
	Columns(cols ...field.Expr) gen.Columns
	Clauses(conds ...clause.Expression) IProductStatisticsDo
	Not(conds ...gen.Condition) IProductStatisticsDo
	Or(conds ...gen.Condition) IProductStatisticsDo
	Select(conds ...field.Expr) IProductStatisticsDo
	Where(conds ...gen.Condition) IProductStatisticsDo
	Order(conds ...field.Expr) IProductStatisticsDo
	Distinct(cols ...field.Expr) IProductStatisticsDo
	Omit(cols ...field.Expr) IProductStatisticsDo
	Join(table schema.Tabler, on ...field.Expr) IProductStatisticsDo
	LeftJoin(table schema.Tabler, on ...field.Expr) IProductStatisticsDo
	RightJoin(table schema.Tabler, on ...field.Expr) IProductStatisticsDo
	Group(cols ...field.Expr) IProductStatisticsDo
	Having(conds ...gen.Condition) IProductStatisticsDo
	Limit(limit int) IProductStatisticsDo
	Offset(offset int) IProductStatisticsDo
	Count() (count int64, err error)
	Scopes(funcs ...func(gen.Dao) gen.Dao) IProductStatisticsDo
	Unscoped() IProductStatisticsDo
	Create(values ...*product.ProductStatistics) error
	CreateInBatches(values []*product.ProductStatistics, batchSize int) error
	Save(values ...*product.ProductStatistics) error
	First() (*product.ProductStatistics, error)
	Take() (*product.ProductStatistics, error)
	Last() (*product.ProductStatistics, error)
	Find() ([]*product.ProductStatistics, error)
	FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*product.ProductStatistics, err error)
	FindInBatches(result *[]*product.ProductStatistics, batchSize int, fc func(tx gen.Dao, batch int) error) error
	Pluck(column field.Expr, dest interface{}) error
	Delete(...*product.ProductStatistics) (info gen.ResultInfo, err error)
	Update(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	Updates(value interface{}) (info gen.ResultInfo, err error)
	UpdateColumn(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateColumnSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	UpdateColumns(value interface{}) (info gen.ResultInfo, err error)
	UpdateFrom(q gen.SubQuery) gen.Dao
	Attrs(attrs ...field.AssignExpr) IProductStatisticsDo
	Assign(attrs ...field.AssignExpr) IProductStatisticsDo
	Joins(fields ...field.RelationField) IProductStatisticsDo
	Preload(fields ...field.RelationField) IProductStatisticsDo
	FirstOrInit() (*product.ProductStatistics, error)
	FirstOrCreate() (*product.ProductStatistics, error)
	FindByPage(offset int, limit int) (result []*product.ProductStatistics, count int64, err error)
	ScanByPage(result interface{}, offset int, limit int) (count int64, err error)
	Rows() (*sql.Rows, error)
	Row() *sql.Row
	Scan(result interface{}) (err error)
	Returning(value interface{}, columns ...string) IProductStatisticsDo
	UnderlyingDB() *gorm.DB
	schema.Tabler
}

func (p productStatisticsDo) Debug() IProductStatisticsDo {
	return p.withDO(p.DO.Debug())
}

func (p productStatisticsDo) WithContext(ctx context.Context) IProductStatisticsDo {
	return p.withDO(p.DO.WithContext(ctx))
}

func (p productStatisticsDo) ReadDB() IProductStatisticsDo {
	return p.Clauses(dbresolver.Read)
}

func (p productStatisticsDo) WriteDB() IProductStatisticsDo {
	return p.Clauses(dbresolver.Write)
}

func (p productStatisticsDo) Session(config *gorm.Session) IProductStatisticsDo {
	return p.withDO(p.DO.Session(config))
}

func (p productStatisticsDo) Clauses(conds ...clause.Expression) IProductStatisticsDo {
	return p.withDO(p.DO.Clauses(conds...))
}

func (p productStatisticsDo) Returning(value interface{}, columns ...string) IProductStatisticsDo {
	return p.withDO(p.DO.Returning(value, columns...))
}

func (p productStatisticsDo) Not(conds ...gen.Condition) IProductStatisticsDo {
	return p.withDO(p.DO.Not(conds...))
}

func (p productStatisticsDo) Or(conds ...gen.Condition) IProductStatisticsDo {
	return p.withDO(p.DO.Or(conds...))
}

func (p productStatisticsDo) Select(conds ...field.Expr) IProductStatisticsDo {
	return p.withDO(p.DO.Select(conds...))
}

func (p productStatisticsDo) Where(conds ...gen.Condition) IProductStatisticsDo {
	return p.withDO(p.DO.Where(conds...))
}

func (p productStatisticsDo) Order(conds ...field.Expr) IProductStatisticsDo {
	return p.withDO(p.DO.Order(conds...))
}

func (p productStatisticsDo) Distinct(cols ...field.Expr) IProductStatisticsDo {
	return p.withDO(p.DO.Distinct(cols...))
}

func (p productStatisticsDo) Omit(cols ...field.Expr) IProductStatisticsDo {
	return p.withDO(p.DO.Omit(cols...))
}

func (p productStatisticsDo) Join(table schema.Tabler, on ...field.Expr) IProductStatisticsDo {
	return p.withDO(p.DO.Join(table, on...))
}

func (p productStatisticsDo) LeftJoin(table schema.Tabler, on ...field.Expr) IProductStatisticsDo {
	return p.withDO(p.DO.LeftJoin(table, on...))
}

func (p productStatisticsDo) RightJoin(table schema.Tabler, on ...field.Expr) IProductStatisticsDo {
	return p.withDO(p.DO.RightJoin(table, on...))
}

func (p productStatisticsDo) Group(cols ...field.Expr) IProductStatisticsDo {
	return p.withDO(p.DO.Group(cols...))
}

func (p productStatisticsDo) Having(conds ...gen.Condition) IProductStatisticsDo {
	return p.withDO(p.DO.Having(conds...))
}

func (p productStatisticsDo) Limit(limit int) IProductStatisticsDo {
	return p.withDO(p.DO.Limit(limit))
}

func (p productStatisticsDo) Offset(offset int) IProductStatisticsDo {
	return p.withDO(p.DO.Offset(offset))
}

func (p productStatisticsDo) Scopes(funcs ...func(gen.Dao) gen.Dao) IProductStatisticsDo {
	return p.withDO(p.DO.Scopes(funcs...))
}

func (p productStatisticsDo) Unscoped() IProductStatisticsDo {
	return p.withDO(p.DO.Unscoped())
}

func (p productStatisticsDo) Create(values ...*product.ProductStatistics) error {
	if len(values) == 0 {
		return nil
	}
	return p.DO.Create(values)
}

func (p productStatisticsDo) CreateInBatches(values []*product.ProductStatistics, batchSize int) error {
	return p.DO.CreateInBatches(values, batchSize)
}

// Save : !!! underlying implementation is different with GORM
// The method is equivalent to executing the statement: db.Clauses(clause.OnConflict{UpdateAll: true}).Create(values)
func (p productStatisticsDo) Save(values ...*product.ProductStatistics) error {
	if len(values) == 0 {
		return nil
	}
	return p.DO.Save(values)
}

func (p productStatisticsDo) First() (*product.ProductStatistics, error) {
	if result, err := p.DO.First(); err != nil {
		return nil, err
	} else {
		return result.(*product.ProductStatistics), nil
	}
}

func (p productStatisticsDo) Take() (*product.ProductStatistics, error) {
	if result, err := p.DO.Take(); err != nil {
		return nil, err
	} else {
		return result.(*product.ProductStatistics), nil
	}
}

func (p productStatisticsDo) Last() (*product.ProductStatistics, error) {
	if result, err := p.DO.Last(); err != nil {
		return nil, err
	} else {
		return result.(*product.ProductStatistics), nil
	}
}

func (p productStatisticsDo) Find() ([]*product.ProductStatistics, error) {
	result, err := p.DO.Find()
	return result.([]*product.ProductStatistics), err
}

func (p productStatisticsDo) FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*product.ProductStatistics, err error) {
	buf := make([]*product.ProductStatistics, 0, batchSize)
	err = p.DO.FindInBatches(&buf, batchSize, func(tx gen.Dao, batch int) error {
		defer func() { results = append(results, buf...) }()
		return fc(tx, batch)
	})
	return results, err
}

func (p productStatisticsDo) FindInBatches(result *[]*product.ProductStatistics, batchSize int, fc func(tx gen.Dao, batch int) error) error {
	return p.DO.FindInBatches(result, batchSize, fc)
}

func (p productStatisticsDo) Attrs(attrs ...field.AssignExpr) IProductStatisticsDo {
	return p.withDO(p.DO.Attrs(attrs...))
}

func (p productStatisticsDo) Assign(attrs ...field.AssignExpr) IProductStatisticsDo {
	return p.withDO(p.DO.Assign(attrs...))
}

func (p productStatisticsDo) Joins(fields ...field.RelationField) IProductStatisticsDo {
	for _, _f := range fields {
		p = *p.withDO(p.DO.Joins(_f))
	}
	return &p
}

func (p productStatisticsDo) Preload(fields ...field.RelationField) IProductStatisticsDo {
	for _, _f := range fields {
		p = *p.withDO(p.DO.Preload(_f))
	}
	return &p
}

func (p productStatisticsDo) FirstOrInit() (*product.ProductStatistics, error) {
	if result, err := p.DO.FirstOrInit(); err != nil {
		return nil, err
	} else {
		return result.(*product.ProductStatistics), nil
	}
}

func (p productStatisticsDo) FirstOrCreate() (*product.ProductStatistics, error) {
	if result, err := p.DO.FirstOrCreate(); err != nil {
		return nil, err
	} else {
		return result.(*product.ProductStatistics), nil
	}
}

func (p productStatisticsDo) FindByPage(offset int, limit int) (result []*product.ProductStatistics, count int64, err error) {
	result, err = p.Offset(offset).Limit(limit).Find()
	if err != nil {
		return
	}

	if size := len(result); 0 < limit && 0 < size && size < limit {
		count = int64(size + offset)
		return
	}

	count, err = p.Offset(-1).Limit(-1).Count()
	return
}

func (p productStatisticsDo) ScanByPage(result interface{}, offset int, limit int) (count int64, err error) {
	count, err = p.Count()
	if err != nil {
		return
	}

	err = p.Offset(offset).Limit(limit).Scan(result)
	return
}

func (p productStatisticsDo) Scan(result interface{}) (err error) {
	return p.DO.Scan(result)
}

func (p productStatisticsDo) Delete(models ...*product.ProductStatistics) (result gen.ResultInfo, err error) {
	return p.DO.Delete(models)
}

func (p *productStatisticsDo) withDO(do gen.Dao) *productStatisticsDo {
	p.DO = *do.(*gen.DO)
	return p
}
