// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package query

import (
	"backend-go/internal/model/product"
	"context"
	"database/sql"

	"gorm.io/gorm"
	"gorm.io/gorm/clause"
	"gorm.io/gorm/schema"

	"gorm.io/gen"
	"gorm.io/gen/field"

	"gorm.io/plugin/dbresolver"
)

func newProductBrowseHistory(db *gorm.DB, opts ...gen.DOOption) productBrowseHistory {
	_productBrowseHistory := productBrowseHistory{}

	_productBrowseHistory.productBrowseHistoryDo.UseDB(db, opts...)
	_productBrowseHistory.productBrowseHistoryDo.UseModel(&product.ProductBrowseHistory{})

	tableName := _productBrowseHistory.productBrowseHistoryDo.TableName()
	_productBrowseHistory.ALL = field.NewAsterisk(tableName)
	_productBrowseHistory.ID = field.NewInt64(tableName, "id")
	_productBrowseHistory.UserID = field.NewInt64(tableName, "user_id")
	_productBrowseHistory.SpuID = field.NewInt64(tableName, "spu_id")
	_productBrowseHistory.UserDeleted = field.NewBool(tableName, "user_deleted")
	_productBrowseHistory.CreatedAt = field.NewTime(tableName, "created_at")
	_productBrowseHistory.UpdatedAt = field.NewTime(tableName, "updated_at")
	_productBrowseHistory.DeletedAt = field.NewInt64(tableName, "deleted_at")
	_productBrowseHistory.Deleted = field.NewBool(tableName, "deleted")

	_productBrowseHistory.fillFieldMap()

	return _productBrowseHistory
}

type productBrowseHistory struct {
	productBrowseHistoryDo productBrowseHistoryDo

	ALL         field.Asterisk
	ID          field.Int64 // 记录编号
	UserID      field.Int64 // 用户编号
	SpuID       field.Int64 // 商品 SPU 编号
	UserDeleted field.Bool  // 用户是否删除
	CreatedAt   field.Time  // 创建时间
	UpdatedAt   field.Time  // 更新时间
	DeletedAt   field.Int64 // 删除时间
	Deleted     field.Bool  // 是否删除

	fieldMap map[string]field.Expr
}

func (p productBrowseHistory) Table(newTableName string) *productBrowseHistory {
	p.productBrowseHistoryDo.UseTable(newTableName)
	return p.updateTableName(newTableName)
}

func (p productBrowseHistory) As(alias string) *productBrowseHistory {
	p.productBrowseHistoryDo.DO = *(p.productBrowseHistoryDo.As(alias).(*gen.DO))
	return p.updateTableName(alias)
}

func (p *productBrowseHistory) updateTableName(table string) *productBrowseHistory {
	p.ALL = field.NewAsterisk(table)
	p.ID = field.NewInt64(table, "id")
	p.UserID = field.NewInt64(table, "user_id")
	p.SpuID = field.NewInt64(table, "spu_id")
	p.UserDeleted = field.NewBool(table, "user_deleted")
	p.CreatedAt = field.NewTime(table, "created_at")
	p.UpdatedAt = field.NewTime(table, "updated_at")
	p.DeletedAt = field.NewInt64(table, "deleted_at")
	p.Deleted = field.NewBool(table, "deleted")

	p.fillFieldMap()

	return p
}

func (p *productBrowseHistory) WithContext(ctx context.Context) IProductBrowseHistoryDo {
	return p.productBrowseHistoryDo.WithContext(ctx)
}

func (p productBrowseHistory) TableName() string { return p.productBrowseHistoryDo.TableName() }

func (p productBrowseHistory) Alias() string { return p.productBrowseHistoryDo.Alias() }

func (p productBrowseHistory) Columns(cols ...field.Expr) gen.Columns {
	return p.productBrowseHistoryDo.Columns(cols...)
}

func (p *productBrowseHistory) GetFieldByName(fieldName string) (field.OrderExpr, bool) {
	_f, ok := p.fieldMap[fieldName]
	if !ok || _f == nil {
		return nil, false
	}
	_oe, ok := _f.(field.OrderExpr)
	return _oe, ok
}

func (p *productBrowseHistory) fillFieldMap() {
	p.fieldMap = make(map[string]field.Expr, 8)
	p.fieldMap["id"] = p.ID
	p.fieldMap["user_id"] = p.UserID
	p.fieldMap["spu_id"] = p.SpuID
	p.fieldMap["user_deleted"] = p.UserDeleted
	p.fieldMap["created_at"] = p.CreatedAt
	p.fieldMap["updated_at"] = p.UpdatedAt
	p.fieldMap["deleted_at"] = p.DeletedAt
	p.fieldMap["deleted"] = p.Deleted
}

func (p productBrowseHistory) clone(db *gorm.DB) productBrowseHistory {
	p.productBrowseHistoryDo.ReplaceConnPool(db.Statement.ConnPool)
	return p
}

func (p productBrowseHistory) replaceDB(db *gorm.DB) productBrowseHistory {
	p.productBrowseHistoryDo.ReplaceDB(db)
	return p
}

type productBrowseHistoryDo struct{ gen.DO }

type IProductBrowseHistoryDo interface {
	gen.SubQuery
	Debug() IProductBrowseHistoryDo
	WithContext(ctx context.Context) IProductBrowseHistoryDo
	WithResult(fc func(tx gen.Dao)) gen.ResultInfo
	ReplaceDB(db *gorm.DB)
	ReadDB() IProductBrowseHistoryDo
	WriteDB() IProductBrowseHistoryDo
	As(alias string) gen.Dao
	Session(config *gorm.Session) IProductBrowseHistoryDo
	Columns(cols ...field.Expr) gen.Columns
	Clauses(conds ...clause.Expression) IProductBrowseHistoryDo
	Not(conds ...gen.Condition) IProductBrowseHistoryDo
	Or(conds ...gen.Condition) IProductBrowseHistoryDo
	Select(conds ...field.Expr) IProductBrowseHistoryDo
	Where(conds ...gen.Condition) IProductBrowseHistoryDo
	Order(conds ...field.Expr) IProductBrowseHistoryDo
	Distinct(cols ...field.Expr) IProductBrowseHistoryDo
	Omit(cols ...field.Expr) IProductBrowseHistoryDo
	Join(table schema.Tabler, on ...field.Expr) IProductBrowseHistoryDo
	LeftJoin(table schema.Tabler, on ...field.Expr) IProductBrowseHistoryDo
	RightJoin(table schema.Tabler, on ...field.Expr) IProductBrowseHistoryDo
	Group(cols ...field.Expr) IProductBrowseHistoryDo
	Having(conds ...gen.Condition) IProductBrowseHistoryDo
	Limit(limit int) IProductBrowseHistoryDo
	Offset(offset int) IProductBrowseHistoryDo
	Count() (count int64, err error)
	Scopes(funcs ...func(gen.Dao) gen.Dao) IProductBrowseHistoryDo
	Unscoped() IProductBrowseHistoryDo
	Create(values ...*product.ProductBrowseHistory) error
	CreateInBatches(values []*product.ProductBrowseHistory, batchSize int) error
	Save(values ...*product.ProductBrowseHistory) error
	First() (*product.ProductBrowseHistory, error)
	Take() (*product.ProductBrowseHistory, error)
	Last() (*product.ProductBrowseHistory, error)
	Find() ([]*product.ProductBrowseHistory, error)
	FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*product.ProductBrowseHistory, err error)
	FindInBatches(result *[]*product.ProductBrowseHistory, batchSize int, fc func(tx gen.Dao, batch int) error) error
	Pluck(column field.Expr, dest interface{}) error
	Delete(...*product.ProductBrowseHistory) (info gen.ResultInfo, err error)
	Update(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	Updates(value interface{}) (info gen.ResultInfo, err error)
	UpdateColumn(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateColumnSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	UpdateColumns(value interface{}) (info gen.ResultInfo, err error)
	UpdateFrom(q gen.SubQuery) gen.Dao
	Attrs(attrs ...field.AssignExpr) IProductBrowseHistoryDo
	Assign(attrs ...field.AssignExpr) IProductBrowseHistoryDo
	Joins(fields ...field.RelationField) IProductBrowseHistoryDo
	Preload(fields ...field.RelationField) IProductBrowseHistoryDo
	FirstOrInit() (*product.ProductBrowseHistory, error)
	FirstOrCreate() (*product.ProductBrowseHistory, error)
	FindByPage(offset int, limit int) (result []*product.ProductBrowseHistory, count int64, err error)
	ScanByPage(result interface{}, offset int, limit int) (count int64, err error)
	Rows() (*sql.Rows, error)
	Row() *sql.Row
	Scan(result interface{}) (err error)
	Returning(value interface{}, columns ...string) IProductBrowseHistoryDo
	UnderlyingDB() *gorm.DB
	schema.Tabler
}

func (p productBrowseHistoryDo) Debug() IProductBrowseHistoryDo {
	return p.withDO(p.DO.Debug())
}

func (p productBrowseHistoryDo) WithContext(ctx context.Context) IProductBrowseHistoryDo {
	return p.withDO(p.DO.WithContext(ctx))
}

func (p productBrowseHistoryDo) ReadDB() IProductBrowseHistoryDo {
	return p.Clauses(dbresolver.Read)
}

func (p productBrowseHistoryDo) WriteDB() IProductBrowseHistoryDo {
	return p.Clauses(dbresolver.Write)
}

func (p productBrowseHistoryDo) Session(config *gorm.Session) IProductBrowseHistoryDo {
	return p.withDO(p.DO.Session(config))
}

func (p productBrowseHistoryDo) Clauses(conds ...clause.Expression) IProductBrowseHistoryDo {
	return p.withDO(p.DO.Clauses(conds...))
}

func (p productBrowseHistoryDo) Returning(value interface{}, columns ...string) IProductBrowseHistoryDo {
	return p.withDO(p.DO.Returning(value, columns...))
}

func (p productBrowseHistoryDo) Not(conds ...gen.Condition) IProductBrowseHistoryDo {
	return p.withDO(p.DO.Not(conds...))
}

func (p productBrowseHistoryDo) Or(conds ...gen.Condition) IProductBrowseHistoryDo {
	return p.withDO(p.DO.Or(conds...))
}

func (p productBrowseHistoryDo) Select(conds ...field.Expr) IProductBrowseHistoryDo {
	return p.withDO(p.DO.Select(conds...))
}

func (p productBrowseHistoryDo) Where(conds ...gen.Condition) IProductBrowseHistoryDo {
	return p.withDO(p.DO.Where(conds...))
}

func (p productBrowseHistoryDo) Order(conds ...field.Expr) IProductBrowseHistoryDo {
	return p.withDO(p.DO.Order(conds...))
}

func (p productBrowseHistoryDo) Distinct(cols ...field.Expr) IProductBrowseHistoryDo {
	return p.withDO(p.DO.Distinct(cols...))
}

func (p productBrowseHistoryDo) Omit(cols ...field.Expr) IProductBrowseHistoryDo {
	return p.withDO(p.DO.Omit(cols...))
}

func (p productBrowseHistoryDo) Join(table schema.Tabler, on ...field.Expr) IProductBrowseHistoryDo {
	return p.withDO(p.DO.Join(table, on...))
}

func (p productBrowseHistoryDo) LeftJoin(table schema.Tabler, on ...field.Expr) IProductBrowseHistoryDo {
	return p.withDO(p.DO.LeftJoin(table, on...))
}

func (p productBrowseHistoryDo) RightJoin(table schema.Tabler, on ...field.Expr) IProductBrowseHistoryDo {
	return p.withDO(p.DO.RightJoin(table, on...))
}

func (p productBrowseHistoryDo) Group(cols ...field.Expr) IProductBrowseHistoryDo {
	return p.withDO(p.DO.Group(cols...))
}

func (p productBrowseHistoryDo) Having(conds ...gen.Condition) IProductBrowseHistoryDo {
	return p.withDO(p.DO.Having(conds...))
}

func (p productBrowseHistoryDo) Limit(limit int) IProductBrowseHistoryDo {
	return p.withDO(p.DO.Limit(limit))
}

func (p productBrowseHistoryDo) Offset(offset int) IProductBrowseHistoryDo {
	return p.withDO(p.DO.Offset(offset))
}

func (p productBrowseHistoryDo) Scopes(funcs ...func(gen.Dao) gen.Dao) IProductBrowseHistoryDo {
	return p.withDO(p.DO.Scopes(funcs...))
}

func (p productBrowseHistoryDo) Unscoped() IProductBrowseHistoryDo {
	return p.withDO(p.DO.Unscoped())
}

func (p productBrowseHistoryDo) Create(values ...*product.ProductBrowseHistory) error {
	if len(values) == 0 {
		return nil
	}
	return p.DO.Create(values)
}

func (p productBrowseHistoryDo) CreateInBatches(values []*product.ProductBrowseHistory, batchSize int) error {
	return p.DO.CreateInBatches(values, batchSize)
}

// Save : !!! underlying implementation is different with GORM
// The method is equivalent to executing the statement: db.Clauses(clause.OnConflict{UpdateAll: true}).Create(values)
func (p productBrowseHistoryDo) Save(values ...*product.ProductBrowseHistory) error {
	if len(values) == 0 {
		return nil
	}
	return p.DO.Save(values)
}

func (p productBrowseHistoryDo) First() (*product.ProductBrowseHistory, error) {
	if result, err := p.DO.First(); err != nil {
		return nil, err
	} else {
		return result.(*product.ProductBrowseHistory), nil
	}
}

func (p productBrowseHistoryDo) Take() (*product.ProductBrowseHistory, error) {
	if result, err := p.DO.Take(); err != nil {
		return nil, err
	} else {
		return result.(*product.ProductBrowseHistory), nil
	}
}

func (p productBrowseHistoryDo) Last() (*product.ProductBrowseHistory, error) {
	if result, err := p.DO.Last(); err != nil {
		return nil, err
	} else {
		return result.(*product.ProductBrowseHistory), nil
	}
}

func (p productBrowseHistoryDo) Find() ([]*product.ProductBrowseHistory, error) {
	result, err := p.DO.Find()
	return result.([]*product.ProductBrowseHistory), err
}

func (p productBrowseHistoryDo) FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*product.ProductBrowseHistory, err error) {
	buf := make([]*product.ProductBrowseHistory, 0, batchSize)
	err = p.DO.FindInBatches(&buf, batchSize, func(tx gen.Dao, batch int) error {
		defer func() { results = append(results, buf...) }()
		return fc(tx, batch)
	})
	return results, err
}

func (p productBrowseHistoryDo) FindInBatches(result *[]*product.ProductBrowseHistory, batchSize int, fc func(tx gen.Dao, batch int) error) error {
	return p.DO.FindInBatches(result, batchSize, fc)
}

func (p productBrowseHistoryDo) Attrs(attrs ...field.AssignExpr) IProductBrowseHistoryDo {
	return p.withDO(p.DO.Attrs(attrs...))
}

func (p productBrowseHistoryDo) Assign(attrs ...field.AssignExpr) IProductBrowseHistoryDo {
	return p.withDO(p.DO.Assign(attrs...))
}

func (p productBrowseHistoryDo) Joins(fields ...field.RelationField) IProductBrowseHistoryDo {
	for _, _f := range fields {
		p = *p.withDO(p.DO.Joins(_f))
	}
	return &p
}

func (p productBrowseHistoryDo) Preload(fields ...field.RelationField) IProductBrowseHistoryDo {
	for _, _f := range fields {
		p = *p.withDO(p.DO.Preload(_f))
	}
	return &p
}

func (p productBrowseHistoryDo) FirstOrInit() (*product.ProductBrowseHistory, error) {
	if result, err := p.DO.FirstOrInit(); err != nil {
		return nil, err
	} else {
		return result.(*product.ProductBrowseHistory), nil
	}
}

func (p productBrowseHistoryDo) FirstOrCreate() (*product.ProductBrowseHistory, error) {
	if result, err := p.DO.FirstOrCreate(); err != nil {
		return nil, err
	} else {
		return result.(*product.ProductBrowseHistory), nil
	}
}

func (p productBrowseHistoryDo) FindByPage(offset int, limit int) (result []*product.ProductBrowseHistory, count int64, err error) {
	result, err = p.Offset(offset).Limit(limit).Find()
	if err != nil {
		return
	}

	if size := len(result); 0 < limit && 0 < size && size < limit {
		count = int64(size + offset)
		return
	}

	count, err = p.Offset(-1).Limit(-1).Count()
	return
}

func (p productBrowseHistoryDo) ScanByPage(result interface{}, offset int, limit int) (count int64, err error) {
	count, err = p.Count()
	if err != nil {
		return
	}

	err = p.Offset(offset).Limit(limit).Scan(result)
	return
}

func (p productBrowseHistoryDo) Scan(result interface{}) (err error) {
	return p.DO.Scan(result)
}

func (p productBrowseHistoryDo) Delete(models ...*product.ProductBrowseHistory) (result gen.ResultInfo, err error) {
	return p.DO.Delete(models)
}

func (p *productBrowseHistoryDo) withDO(do gen.Dao) *productBrowseHistoryDo {
	p.DO = *do.(*gen.DO)
	return p
}
