// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package query

import (
	"context"
	"database/sql"

	"gorm.io/gorm"
	"gorm.io/gorm/clause"
	"gorm.io/gorm/schema"

	"gorm.io/gen"
	"gorm.io/gen/field"

	"gorm.io/plugin/dbresolver"

	"backend-go/internal/model/promotion"
)

func newPromotionKefuMessage(db *gorm.DB, opts ...gen.DOOption) promotionKefuMessage {
	_promotionKefuMessage := promotionKefuMessage{}

	_promotionKefuMessage.promotionKefuMessageDo.UseDB(db, opts...)
	_promotionKefuMessage.promotionKefuMessageDo.UseModel(&promotion.PromotionKefuMessage{})

	tableName := _promotionKefuMessage.promotionKefuMessageDo.TableName()
	_promotionKefuMessage.ALL = field.NewAsterisk(tableName)
	_promotionKefuMessage.ID = field.NewInt64(tableName, "id")
	_promotionKefuMessage.ConversationID = field.NewInt64(tableName, "conversation_id")
	_promotionKefuMessage.SenderID = field.NewInt64(tableName, "sender_id")
	_promotionKefuMessage.SenderType = field.NewInt(tableName, "sender_type")
	_promotionKefuMessage.ReceiverID = field.NewInt64(tableName, "receiver_id")
	_promotionKefuMessage.ReceiverType = field.NewInt(tableName, "receiver_type")
	_promotionKefuMessage.ContentType = field.NewInt(tableName, "content_type")
	_promotionKefuMessage.Content = field.NewString(tableName, "content")
	_promotionKefuMessage.ReadStatus = field.NewBool(tableName, "read_status")
	_promotionKefuMessage.Creator = field.NewString(tableName, "creator")
	_promotionKefuMessage.CreateTime = field.NewTime(tableName, "create_time")
	_promotionKefuMessage.Updater = field.NewString(tableName, "updater")
	_promotionKefuMessage.UpdateTime = field.NewTime(tableName, "update_time")
	_promotionKefuMessage.Deleted = field.NewInt(tableName, "deleted")
	_promotionKefuMessage.TenantID = field.NewInt64(tableName, "tenant_id")

	_promotionKefuMessage.fillFieldMap()

	return _promotionKefuMessage
}

type promotionKefuMessage struct {
	promotionKefuMessageDo promotionKefuMessageDo

	ALL            field.Asterisk
	ID             field.Int64  // 编号
	ConversationID field.Int64  // 会话编号
	SenderID       field.Int64  // 发送人编号
	SenderType     field.Int    // 发送人类型
	ReceiverID     field.Int64  // 接收人编号
	ReceiverType   field.Int    // 接收人类型
	ContentType    field.Int    // 消息类型
	Content        field.String // 消息内容
	ReadStatus     field.Bool   // 是否已读
	Creator        field.String
	CreateTime     field.Time
	Updater        field.String
	UpdateTime     field.Time
	Deleted        field.Int
	TenantID       field.Int64

	fieldMap map[string]field.Expr
}

func (p promotionKefuMessage) Table(newTableName string) *promotionKefuMessage {
	p.promotionKefuMessageDo.UseTable(newTableName)
	return p.updateTableName(newTableName)
}

func (p promotionKefuMessage) As(alias string) *promotionKefuMessage {
	p.promotionKefuMessageDo.DO = *(p.promotionKefuMessageDo.As(alias).(*gen.DO))
	return p.updateTableName(alias)
}

func (p *promotionKefuMessage) updateTableName(table string) *promotionKefuMessage {
	p.ALL = field.NewAsterisk(table)
	p.ID = field.NewInt64(table, "id")
	p.ConversationID = field.NewInt64(table, "conversation_id")
	p.SenderID = field.NewInt64(table, "sender_id")
	p.SenderType = field.NewInt(table, "sender_type")
	p.ReceiverID = field.NewInt64(table, "receiver_id")
	p.ReceiverType = field.NewInt(table, "receiver_type")
	p.ContentType = field.NewInt(table, "content_type")
	p.Content = field.NewString(table, "content")
	p.ReadStatus = field.NewBool(table, "read_status")
	p.Creator = field.NewString(table, "creator")
	p.CreateTime = field.NewTime(table, "create_time")
	p.Updater = field.NewString(table, "updater")
	p.UpdateTime = field.NewTime(table, "update_time")
	p.Deleted = field.NewInt(table, "deleted")
	p.TenantID = field.NewInt64(table, "tenant_id")

	p.fillFieldMap()

	return p
}

func (p *promotionKefuMessage) WithContext(ctx context.Context) IPromotionKefuMessageDo {
	return p.promotionKefuMessageDo.WithContext(ctx)
}

func (p promotionKefuMessage) TableName() string { return p.promotionKefuMessageDo.TableName() }

func (p promotionKefuMessage) Alias() string { return p.promotionKefuMessageDo.Alias() }

func (p promotionKefuMessage) Columns(cols ...field.Expr) gen.Columns {
	return p.promotionKefuMessageDo.Columns(cols...)
}

func (p *promotionKefuMessage) GetFieldByName(fieldName string) (field.OrderExpr, bool) {
	_f, ok := p.fieldMap[fieldName]
	if !ok || _f == nil {
		return nil, false
	}
	_oe, ok := _f.(field.OrderExpr)
	return _oe, ok
}

func (p *promotionKefuMessage) fillFieldMap() {
	p.fieldMap = make(map[string]field.Expr, 15)
	p.fieldMap["id"] = p.ID
	p.fieldMap["conversation_id"] = p.ConversationID
	p.fieldMap["sender_id"] = p.SenderID
	p.fieldMap["sender_type"] = p.SenderType
	p.fieldMap["receiver_id"] = p.ReceiverID
	p.fieldMap["receiver_type"] = p.ReceiverType
	p.fieldMap["content_type"] = p.ContentType
	p.fieldMap["content"] = p.Content
	p.fieldMap["read_status"] = p.ReadStatus
	p.fieldMap["creator"] = p.Creator
	p.fieldMap["create_time"] = p.CreateTime
	p.fieldMap["updater"] = p.Updater
	p.fieldMap["update_time"] = p.UpdateTime
	p.fieldMap["deleted"] = p.Deleted
	p.fieldMap["tenant_id"] = p.TenantID
}

func (p promotionKefuMessage) clone(db *gorm.DB) promotionKefuMessage {
	p.promotionKefuMessageDo.ReplaceConnPool(db.Statement.ConnPool)
	return p
}

func (p promotionKefuMessage) replaceDB(db *gorm.DB) promotionKefuMessage {
	p.promotionKefuMessageDo.ReplaceDB(db)
	return p
}

type promotionKefuMessageDo struct{ gen.DO }

type IPromotionKefuMessageDo interface {
	gen.SubQuery
	Debug() IPromotionKefuMessageDo
	WithContext(ctx context.Context) IPromotionKefuMessageDo
	WithResult(fc func(tx gen.Dao)) gen.ResultInfo
	ReplaceDB(db *gorm.DB)
	ReadDB() IPromotionKefuMessageDo
	WriteDB() IPromotionKefuMessageDo
	As(alias string) gen.Dao
	Session(config *gorm.Session) IPromotionKefuMessageDo
	Columns(cols ...field.Expr) gen.Columns
	Clauses(conds ...clause.Expression) IPromotionKefuMessageDo
	Not(conds ...gen.Condition) IPromotionKefuMessageDo
	Or(conds ...gen.Condition) IPromotionKefuMessageDo
	Select(conds ...field.Expr) IPromotionKefuMessageDo
	Where(conds ...gen.Condition) IPromotionKefuMessageDo
	Order(conds ...field.Expr) IPromotionKefuMessageDo
	Distinct(cols ...field.Expr) IPromotionKefuMessageDo
	Omit(cols ...field.Expr) IPromotionKefuMessageDo
	Join(table schema.Tabler, on ...field.Expr) IPromotionKefuMessageDo
	LeftJoin(table schema.Tabler, on ...field.Expr) IPromotionKefuMessageDo
	RightJoin(table schema.Tabler, on ...field.Expr) IPromotionKefuMessageDo
	Group(cols ...field.Expr) IPromotionKefuMessageDo
	Having(conds ...gen.Condition) IPromotionKefuMessageDo
	Limit(limit int) IPromotionKefuMessageDo
	Offset(offset int) IPromotionKefuMessageDo
	Count() (count int64, err error)
	Scopes(funcs ...func(gen.Dao) gen.Dao) IPromotionKefuMessageDo
	Unscoped() IPromotionKefuMessageDo
	Create(values ...*promotion.PromotionKefuMessage) error
	CreateInBatches(values []*promotion.PromotionKefuMessage, batchSize int) error
	Save(values ...*promotion.PromotionKefuMessage) error
	First() (*promotion.PromotionKefuMessage, error)
	Take() (*promotion.PromotionKefuMessage, error)
	Last() (*promotion.PromotionKefuMessage, error)
	Find() ([]*promotion.PromotionKefuMessage, error)
	FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*promotion.PromotionKefuMessage, err error)
	FindInBatches(result *[]*promotion.PromotionKefuMessage, batchSize int, fc func(tx gen.Dao, batch int) error) error
	Pluck(column field.Expr, dest interface{}) error
	Delete(...*promotion.PromotionKefuMessage) (info gen.ResultInfo, err error)
	Update(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	Updates(value interface{}) (info gen.ResultInfo, err error)
	UpdateColumn(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateColumnSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	UpdateColumns(value interface{}) (info gen.ResultInfo, err error)
	UpdateFrom(q gen.SubQuery) gen.Dao
	Attrs(attrs ...field.AssignExpr) IPromotionKefuMessageDo
	Assign(attrs ...field.AssignExpr) IPromotionKefuMessageDo
	Joins(fields ...field.RelationField) IPromotionKefuMessageDo
	Preload(fields ...field.RelationField) IPromotionKefuMessageDo
	FirstOrInit() (*promotion.PromotionKefuMessage, error)
	FirstOrCreate() (*promotion.PromotionKefuMessage, error)
	FindByPage(offset int, limit int) (result []*promotion.PromotionKefuMessage, count int64, err error)
	ScanByPage(result interface{}, offset int, limit int) (count int64, err error)
	Rows() (*sql.Rows, error)
	Row() *sql.Row
	Scan(result interface{}) (err error)
	Returning(value interface{}, columns ...string) IPromotionKefuMessageDo
	UnderlyingDB() *gorm.DB
	schema.Tabler
}

func (p promotionKefuMessageDo) Debug() IPromotionKefuMessageDo {
	return p.withDO(p.DO.Debug())
}

func (p promotionKefuMessageDo) WithContext(ctx context.Context) IPromotionKefuMessageDo {
	return p.withDO(p.DO.WithContext(ctx))
}

func (p promotionKefuMessageDo) ReadDB() IPromotionKefuMessageDo {
	return p.Clauses(dbresolver.Read)
}

func (p promotionKefuMessageDo) WriteDB() IPromotionKefuMessageDo {
	return p.Clauses(dbresolver.Write)
}

func (p promotionKefuMessageDo) Session(config *gorm.Session) IPromotionKefuMessageDo {
	return p.withDO(p.DO.Session(config))
}

func (p promotionKefuMessageDo) Clauses(conds ...clause.Expression) IPromotionKefuMessageDo {
	return p.withDO(p.DO.Clauses(conds...))
}

func (p promotionKefuMessageDo) Returning(value interface{}, columns ...string) IPromotionKefuMessageDo {
	return p.withDO(p.DO.Returning(value, columns...))
}

func (p promotionKefuMessageDo) Not(conds ...gen.Condition) IPromotionKefuMessageDo {
	return p.withDO(p.DO.Not(conds...))
}

func (p promotionKefuMessageDo) Or(conds ...gen.Condition) IPromotionKefuMessageDo {
	return p.withDO(p.DO.Or(conds...))
}

func (p promotionKefuMessageDo) Select(conds ...field.Expr) IPromotionKefuMessageDo {
	return p.withDO(p.DO.Select(conds...))
}

func (p promotionKefuMessageDo) Where(conds ...gen.Condition) IPromotionKefuMessageDo {
	return p.withDO(p.DO.Where(conds...))
}

func (p promotionKefuMessageDo) Order(conds ...field.Expr) IPromotionKefuMessageDo {
	return p.withDO(p.DO.Order(conds...))
}

func (p promotionKefuMessageDo) Distinct(cols ...field.Expr) IPromotionKefuMessageDo {
	return p.withDO(p.DO.Distinct(cols...))
}

func (p promotionKefuMessageDo) Omit(cols ...field.Expr) IPromotionKefuMessageDo {
	return p.withDO(p.DO.Omit(cols...))
}

func (p promotionKefuMessageDo) Join(table schema.Tabler, on ...field.Expr) IPromotionKefuMessageDo {
	return p.withDO(p.DO.Join(table, on...))
}

func (p promotionKefuMessageDo) LeftJoin(table schema.Tabler, on ...field.Expr) IPromotionKefuMessageDo {
	return p.withDO(p.DO.LeftJoin(table, on...))
}

func (p promotionKefuMessageDo) RightJoin(table schema.Tabler, on ...field.Expr) IPromotionKefuMessageDo {
	return p.withDO(p.DO.RightJoin(table, on...))
}

func (p promotionKefuMessageDo) Group(cols ...field.Expr) IPromotionKefuMessageDo {
	return p.withDO(p.DO.Group(cols...))
}

func (p promotionKefuMessageDo) Having(conds ...gen.Condition) IPromotionKefuMessageDo {
	return p.withDO(p.DO.Having(conds...))
}

func (p promotionKefuMessageDo) Limit(limit int) IPromotionKefuMessageDo {
	return p.withDO(p.DO.Limit(limit))
}

func (p promotionKefuMessageDo) Offset(offset int) IPromotionKefuMessageDo {
	return p.withDO(p.DO.Offset(offset))
}

func (p promotionKefuMessageDo) Scopes(funcs ...func(gen.Dao) gen.Dao) IPromotionKefuMessageDo {
	return p.withDO(p.DO.Scopes(funcs...))
}

func (p promotionKefuMessageDo) Unscoped() IPromotionKefuMessageDo {
	return p.withDO(p.DO.Unscoped())
}

func (p promotionKefuMessageDo) Create(values ...*promotion.PromotionKefuMessage) error {
	if len(values) == 0 {
		return nil
	}
	return p.DO.Create(values)
}

func (p promotionKefuMessageDo) CreateInBatches(values []*promotion.PromotionKefuMessage, batchSize int) error {
	return p.DO.CreateInBatches(values, batchSize)
}

// Save : !!! underlying implementation is different with GORM
// The method is equivalent to executing the statement: db.Clauses(clause.OnConflict{UpdateAll: true}).Create(values)
func (p promotionKefuMessageDo) Save(values ...*promotion.PromotionKefuMessage) error {
	if len(values) == 0 {
		return nil
	}
	return p.DO.Save(values)
}

func (p promotionKefuMessageDo) First() (*promotion.PromotionKefuMessage, error) {
	if result, err := p.DO.First(); err != nil {
		return nil, err
	} else {
		return result.(*promotion.PromotionKefuMessage), nil
	}
}

func (p promotionKefuMessageDo) Take() (*promotion.PromotionKefuMessage, error) {
	if result, err := p.DO.Take(); err != nil {
		return nil, err
	} else {
		return result.(*promotion.PromotionKefuMessage), nil
	}
}

func (p promotionKefuMessageDo) Last() (*promotion.PromotionKefuMessage, error) {
	if result, err := p.DO.Last(); err != nil {
		return nil, err
	} else {
		return result.(*promotion.PromotionKefuMessage), nil
	}
}

func (p promotionKefuMessageDo) Find() ([]*promotion.PromotionKefuMessage, error) {
	result, err := p.DO.Find()
	return result.([]*promotion.PromotionKefuMessage), err
}

func (p promotionKefuMessageDo) FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*promotion.PromotionKefuMessage, err error) {
	buf := make([]*promotion.PromotionKefuMessage, 0, batchSize)
	err = p.DO.FindInBatches(&buf, batchSize, func(tx gen.Dao, batch int) error {
		defer func() { results = append(results, buf...) }()
		return fc(tx, batch)
	})
	return results, err
}

func (p promotionKefuMessageDo) FindInBatches(result *[]*promotion.PromotionKefuMessage, batchSize int, fc func(tx gen.Dao, batch int) error) error {
	return p.DO.FindInBatches(result, batchSize, fc)
}

func (p promotionKefuMessageDo) Attrs(attrs ...field.AssignExpr) IPromotionKefuMessageDo {
	return p.withDO(p.DO.Attrs(attrs...))
}

func (p promotionKefuMessageDo) Assign(attrs ...field.AssignExpr) IPromotionKefuMessageDo {
	return p.withDO(p.DO.Assign(attrs...))
}

func (p promotionKefuMessageDo) Joins(fields ...field.RelationField) IPromotionKefuMessageDo {
	for _, _f := range fields {
		p = *p.withDO(p.DO.Joins(_f))
	}
	return &p
}

func (p promotionKefuMessageDo) Preload(fields ...field.RelationField) IPromotionKefuMessageDo {
	for _, _f := range fields {
		p = *p.withDO(p.DO.Preload(_f))
	}
	return &p
}

func (p promotionKefuMessageDo) FirstOrInit() (*promotion.PromotionKefuMessage, error) {
	if result, err := p.DO.FirstOrInit(); err != nil {
		return nil, err
	} else {
		return result.(*promotion.PromotionKefuMessage), nil
	}
}

func (p promotionKefuMessageDo) FirstOrCreate() (*promotion.PromotionKefuMessage, error) {
	if result, err := p.DO.FirstOrCreate(); err != nil {
		return nil, err
	} else {
		return result.(*promotion.PromotionKefuMessage), nil
	}
}

func (p promotionKefuMessageDo) FindByPage(offset int, limit int) (result []*promotion.PromotionKefuMessage, count int64, err error) {
	result, err = p.Offset(offset).Limit(limit).Find()
	if err != nil {
		return
	}

	if size := len(result); 0 < limit && 0 < size && size < limit {
		count = int64(size + offset)
		return
	}

	count, err = p.Offset(-1).Limit(-1).Count()
	return
}

func (p promotionKefuMessageDo) ScanByPage(result interface{}, offset int, limit int) (count int64, err error) {
	count, err = p.Count()
	if err != nil {
		return
	}

	err = p.Offset(offset).Limit(limit).Scan(result)
	return
}

func (p promotionKefuMessageDo) Scan(result interface{}) (err error) {
	return p.DO.Scan(result)
}

func (p promotionKefuMessageDo) Delete(models ...*promotion.PromotionKefuMessage) (result gen.ResultInfo, err error) {
	return p.DO.Delete(models)
}

func (p *promotionKefuMessageDo) withDO(do gen.Dao) *promotionKefuMessageDo {
	p.DO = *do.(*gen.DO)
	return p
}
