// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package query

import (
	"context"
	"database/sql"

	"gorm.io/gorm"
	"gorm.io/gorm/clause"
	"gorm.io/gorm/schema"

	"gorm.io/gen"
	"gorm.io/gen/field"

	"gorm.io/plugin/dbresolver"

	"backend-go/internal/model/promotion"
)

func newPromotionDiyPage(db *gorm.DB, opts ...gen.DOOption) promotionDiyPage {
	_promotionDiyPage := promotionDiyPage{}

	_promotionDiyPage.promotionDiyPageDo.UseDB(db, opts...)
	_promotionDiyPage.promotionDiyPageDo.UseModel(&promotion.PromotionDiyPage{})

	tableName := _promotionDiyPage.promotionDiyPageDo.TableName()
	_promotionDiyPage.ALL = field.NewAsterisk(tableName)
	_promotionDiyPage.ID = field.NewInt64(tableName, "id")
	_promotionDiyPage.TemplateID = field.NewInt64(tableName, "template_id")
	_promotionDiyPage.Name = field.NewString(tableName, "name")
	_promotionDiyPage.Remark = field.NewString(tableName, "remark")
	_promotionDiyPage.Status = field.NewInt(tableName, "status")
	_promotionDiyPage.Property = field.NewString(tableName, "property")
	_promotionDiyPage.Creator = field.NewString(tableName, "creator")
	_promotionDiyPage.CreateTime = field.NewTime(tableName, "create_time")
	_promotionDiyPage.Updater = field.NewString(tableName, "updater")
	_promotionDiyPage.UpdateTime = field.NewTime(tableName, "update_time")
	_promotionDiyPage.Deleted = field.NewInt(tableName, "deleted")
	_promotionDiyPage.TenantID = field.NewInt64(tableName, "tenant_id")

	_promotionDiyPage.fillFieldMap()

	return _promotionDiyPage
}

type promotionDiyPage struct {
	promotionDiyPageDo promotionDiyPageDo

	ALL        field.Asterisk
	ID         field.Int64
	TemplateID field.Int64  // 模板ID
	Name       field.String // 页面名称
	Remark     field.String // 备注
	Status     field.Int    // 状态
	Property   field.String // 页面属性
	Creator    field.String
	CreateTime field.Time
	Updater    field.String
	UpdateTime field.Time
	Deleted    field.Int
	TenantID   field.Int64

	fieldMap map[string]field.Expr
}

func (p promotionDiyPage) Table(newTableName string) *promotionDiyPage {
	p.promotionDiyPageDo.UseTable(newTableName)
	return p.updateTableName(newTableName)
}

func (p promotionDiyPage) As(alias string) *promotionDiyPage {
	p.promotionDiyPageDo.DO = *(p.promotionDiyPageDo.As(alias).(*gen.DO))
	return p.updateTableName(alias)
}

func (p *promotionDiyPage) updateTableName(table string) *promotionDiyPage {
	p.ALL = field.NewAsterisk(table)
	p.ID = field.NewInt64(table, "id")
	p.TemplateID = field.NewInt64(table, "template_id")
	p.Name = field.NewString(table, "name")
	p.Remark = field.NewString(table, "remark")
	p.Status = field.NewInt(table, "status")
	p.Property = field.NewString(table, "property")
	p.Creator = field.NewString(table, "creator")
	p.CreateTime = field.NewTime(table, "create_time")
	p.Updater = field.NewString(table, "updater")
	p.UpdateTime = field.NewTime(table, "update_time")
	p.Deleted = field.NewInt(table, "deleted")
	p.TenantID = field.NewInt64(table, "tenant_id")

	p.fillFieldMap()

	return p
}

func (p *promotionDiyPage) WithContext(ctx context.Context) IPromotionDiyPageDo {
	return p.promotionDiyPageDo.WithContext(ctx)
}

func (p promotionDiyPage) TableName() string { return p.promotionDiyPageDo.TableName() }

func (p promotionDiyPage) Alias() string { return p.promotionDiyPageDo.Alias() }

func (p promotionDiyPage) Columns(cols ...field.Expr) gen.Columns {
	return p.promotionDiyPageDo.Columns(cols...)
}

func (p *promotionDiyPage) GetFieldByName(fieldName string) (field.OrderExpr, bool) {
	_f, ok := p.fieldMap[fieldName]
	if !ok || _f == nil {
		return nil, false
	}
	_oe, ok := _f.(field.OrderExpr)
	return _oe, ok
}

func (p *promotionDiyPage) fillFieldMap() {
	p.fieldMap = make(map[string]field.Expr, 12)
	p.fieldMap["id"] = p.ID
	p.fieldMap["template_id"] = p.TemplateID
	p.fieldMap["name"] = p.Name
	p.fieldMap["remark"] = p.Remark
	p.fieldMap["status"] = p.Status
	p.fieldMap["property"] = p.Property
	p.fieldMap["creator"] = p.Creator
	p.fieldMap["create_time"] = p.CreateTime
	p.fieldMap["updater"] = p.Updater
	p.fieldMap["update_time"] = p.UpdateTime
	p.fieldMap["deleted"] = p.Deleted
	p.fieldMap["tenant_id"] = p.TenantID
}

func (p promotionDiyPage) clone(db *gorm.DB) promotionDiyPage {
	p.promotionDiyPageDo.ReplaceConnPool(db.Statement.ConnPool)
	return p
}

func (p promotionDiyPage) replaceDB(db *gorm.DB) promotionDiyPage {
	p.promotionDiyPageDo.ReplaceDB(db)
	return p
}

type promotionDiyPageDo struct{ gen.DO }

type IPromotionDiyPageDo interface {
	gen.SubQuery
	Debug() IPromotionDiyPageDo
	WithContext(ctx context.Context) IPromotionDiyPageDo
	WithResult(fc func(tx gen.Dao)) gen.ResultInfo
	ReplaceDB(db *gorm.DB)
	ReadDB() IPromotionDiyPageDo
	WriteDB() IPromotionDiyPageDo
	As(alias string) gen.Dao
	Session(config *gorm.Session) IPromotionDiyPageDo
	Columns(cols ...field.Expr) gen.Columns
	Clauses(conds ...clause.Expression) IPromotionDiyPageDo
	Not(conds ...gen.Condition) IPromotionDiyPageDo
	Or(conds ...gen.Condition) IPromotionDiyPageDo
	Select(conds ...field.Expr) IPromotionDiyPageDo
	Where(conds ...gen.Condition) IPromotionDiyPageDo
	Order(conds ...field.Expr) IPromotionDiyPageDo
	Distinct(cols ...field.Expr) IPromotionDiyPageDo
	Omit(cols ...field.Expr) IPromotionDiyPageDo
	Join(table schema.Tabler, on ...field.Expr) IPromotionDiyPageDo
	LeftJoin(table schema.Tabler, on ...field.Expr) IPromotionDiyPageDo
	RightJoin(table schema.Tabler, on ...field.Expr) IPromotionDiyPageDo
	Group(cols ...field.Expr) IPromotionDiyPageDo
	Having(conds ...gen.Condition) IPromotionDiyPageDo
	Limit(limit int) IPromotionDiyPageDo
	Offset(offset int) IPromotionDiyPageDo
	Count() (count int64, err error)
	Scopes(funcs ...func(gen.Dao) gen.Dao) IPromotionDiyPageDo
	Unscoped() IPromotionDiyPageDo
	Create(values ...*promotion.PromotionDiyPage) error
	CreateInBatches(values []*promotion.PromotionDiyPage, batchSize int) error
	Save(values ...*promotion.PromotionDiyPage) error
	First() (*promotion.PromotionDiyPage, error)
	Take() (*promotion.PromotionDiyPage, error)
	Last() (*promotion.PromotionDiyPage, error)
	Find() ([]*promotion.PromotionDiyPage, error)
	FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*promotion.PromotionDiyPage, err error)
	FindInBatches(result *[]*promotion.PromotionDiyPage, batchSize int, fc func(tx gen.Dao, batch int) error) error
	Pluck(column field.Expr, dest interface{}) error
	Delete(...*promotion.PromotionDiyPage) (info gen.ResultInfo, err error)
	Update(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	Updates(value interface{}) (info gen.ResultInfo, err error)
	UpdateColumn(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateColumnSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	UpdateColumns(value interface{}) (info gen.ResultInfo, err error)
	UpdateFrom(q gen.SubQuery) gen.Dao
	Attrs(attrs ...field.AssignExpr) IPromotionDiyPageDo
	Assign(attrs ...field.AssignExpr) IPromotionDiyPageDo
	Joins(fields ...field.RelationField) IPromotionDiyPageDo
	Preload(fields ...field.RelationField) IPromotionDiyPageDo
	FirstOrInit() (*promotion.PromotionDiyPage, error)
	FirstOrCreate() (*promotion.PromotionDiyPage, error)
	FindByPage(offset int, limit int) (result []*promotion.PromotionDiyPage, count int64, err error)
	ScanByPage(result interface{}, offset int, limit int) (count int64, err error)
	Rows() (*sql.Rows, error)
	Row() *sql.Row
	Scan(result interface{}) (err error)
	Returning(value interface{}, columns ...string) IPromotionDiyPageDo
	UnderlyingDB() *gorm.DB
	schema.Tabler
}

func (p promotionDiyPageDo) Debug() IPromotionDiyPageDo {
	return p.withDO(p.DO.Debug())
}

func (p promotionDiyPageDo) WithContext(ctx context.Context) IPromotionDiyPageDo {
	return p.withDO(p.DO.WithContext(ctx))
}

func (p promotionDiyPageDo) ReadDB() IPromotionDiyPageDo {
	return p.Clauses(dbresolver.Read)
}

func (p promotionDiyPageDo) WriteDB() IPromotionDiyPageDo {
	return p.Clauses(dbresolver.Write)
}

func (p promotionDiyPageDo) Session(config *gorm.Session) IPromotionDiyPageDo {
	return p.withDO(p.DO.Session(config))
}

func (p promotionDiyPageDo) Clauses(conds ...clause.Expression) IPromotionDiyPageDo {
	return p.withDO(p.DO.Clauses(conds...))
}

func (p promotionDiyPageDo) Returning(value interface{}, columns ...string) IPromotionDiyPageDo {
	return p.withDO(p.DO.Returning(value, columns...))
}

func (p promotionDiyPageDo) Not(conds ...gen.Condition) IPromotionDiyPageDo {
	return p.withDO(p.DO.Not(conds...))
}

func (p promotionDiyPageDo) Or(conds ...gen.Condition) IPromotionDiyPageDo {
	return p.withDO(p.DO.Or(conds...))
}

func (p promotionDiyPageDo) Select(conds ...field.Expr) IPromotionDiyPageDo {
	return p.withDO(p.DO.Select(conds...))
}

func (p promotionDiyPageDo) Where(conds ...gen.Condition) IPromotionDiyPageDo {
	return p.withDO(p.DO.Where(conds...))
}

func (p promotionDiyPageDo) Order(conds ...field.Expr) IPromotionDiyPageDo {
	return p.withDO(p.DO.Order(conds...))
}

func (p promotionDiyPageDo) Distinct(cols ...field.Expr) IPromotionDiyPageDo {
	return p.withDO(p.DO.Distinct(cols...))
}

func (p promotionDiyPageDo) Omit(cols ...field.Expr) IPromotionDiyPageDo {
	return p.withDO(p.DO.Omit(cols...))
}

func (p promotionDiyPageDo) Join(table schema.Tabler, on ...field.Expr) IPromotionDiyPageDo {
	return p.withDO(p.DO.Join(table, on...))
}

func (p promotionDiyPageDo) LeftJoin(table schema.Tabler, on ...field.Expr) IPromotionDiyPageDo {
	return p.withDO(p.DO.LeftJoin(table, on...))
}

func (p promotionDiyPageDo) RightJoin(table schema.Tabler, on ...field.Expr) IPromotionDiyPageDo {
	return p.withDO(p.DO.RightJoin(table, on...))
}

func (p promotionDiyPageDo) Group(cols ...field.Expr) IPromotionDiyPageDo {
	return p.withDO(p.DO.Group(cols...))
}

func (p promotionDiyPageDo) Having(conds ...gen.Condition) IPromotionDiyPageDo {
	return p.withDO(p.DO.Having(conds...))
}

func (p promotionDiyPageDo) Limit(limit int) IPromotionDiyPageDo {
	return p.withDO(p.DO.Limit(limit))
}

func (p promotionDiyPageDo) Offset(offset int) IPromotionDiyPageDo {
	return p.withDO(p.DO.Offset(offset))
}

func (p promotionDiyPageDo) Scopes(funcs ...func(gen.Dao) gen.Dao) IPromotionDiyPageDo {
	return p.withDO(p.DO.Scopes(funcs...))
}

func (p promotionDiyPageDo) Unscoped() IPromotionDiyPageDo {
	return p.withDO(p.DO.Unscoped())
}

func (p promotionDiyPageDo) Create(values ...*promotion.PromotionDiyPage) error {
	if len(values) == 0 {
		return nil
	}
	return p.DO.Create(values)
}

func (p promotionDiyPageDo) CreateInBatches(values []*promotion.PromotionDiyPage, batchSize int) error {
	return p.DO.CreateInBatches(values, batchSize)
}

// Save : !!! underlying implementation is different with GORM
// The method is equivalent to executing the statement: db.Clauses(clause.OnConflict{UpdateAll: true}).Create(values)
func (p promotionDiyPageDo) Save(values ...*promotion.PromotionDiyPage) error {
	if len(values) == 0 {
		return nil
	}
	return p.DO.Save(values)
}

func (p promotionDiyPageDo) First() (*promotion.PromotionDiyPage, error) {
	if result, err := p.DO.First(); err != nil {
		return nil, err
	} else {
		return result.(*promotion.PromotionDiyPage), nil
	}
}

func (p promotionDiyPageDo) Take() (*promotion.PromotionDiyPage, error) {
	if result, err := p.DO.Take(); err != nil {
		return nil, err
	} else {
		return result.(*promotion.PromotionDiyPage), nil
	}
}

func (p promotionDiyPageDo) Last() (*promotion.PromotionDiyPage, error) {
	if result, err := p.DO.Last(); err != nil {
		return nil, err
	} else {
		return result.(*promotion.PromotionDiyPage), nil
	}
}

func (p promotionDiyPageDo) Find() ([]*promotion.PromotionDiyPage, error) {
	result, err := p.DO.Find()
	return result.([]*promotion.PromotionDiyPage), err
}

func (p promotionDiyPageDo) FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*promotion.PromotionDiyPage, err error) {
	buf := make([]*promotion.PromotionDiyPage, 0, batchSize)
	err = p.DO.FindInBatches(&buf, batchSize, func(tx gen.Dao, batch int) error {
		defer func() { results = append(results, buf...) }()
		return fc(tx, batch)
	})
	return results, err
}

func (p promotionDiyPageDo) FindInBatches(result *[]*promotion.PromotionDiyPage, batchSize int, fc func(tx gen.Dao, batch int) error) error {
	return p.DO.FindInBatches(result, batchSize, fc)
}

func (p promotionDiyPageDo) Attrs(attrs ...field.AssignExpr) IPromotionDiyPageDo {
	return p.withDO(p.DO.Attrs(attrs...))
}

func (p promotionDiyPageDo) Assign(attrs ...field.AssignExpr) IPromotionDiyPageDo {
	return p.withDO(p.DO.Assign(attrs...))
}

func (p promotionDiyPageDo) Joins(fields ...field.RelationField) IPromotionDiyPageDo {
	for _, _f := range fields {
		p = *p.withDO(p.DO.Joins(_f))
	}
	return &p
}

func (p promotionDiyPageDo) Preload(fields ...field.RelationField) IPromotionDiyPageDo {
	for _, _f := range fields {
		p = *p.withDO(p.DO.Preload(_f))
	}
	return &p
}

func (p promotionDiyPageDo) FirstOrInit() (*promotion.PromotionDiyPage, error) {
	if result, err := p.DO.FirstOrInit(); err != nil {
		return nil, err
	} else {
		return result.(*promotion.PromotionDiyPage), nil
	}
}

func (p promotionDiyPageDo) FirstOrCreate() (*promotion.PromotionDiyPage, error) {
	if result, err := p.DO.FirstOrCreate(); err != nil {
		return nil, err
	} else {
		return result.(*promotion.PromotionDiyPage), nil
	}
}

func (p promotionDiyPageDo) FindByPage(offset int, limit int) (result []*promotion.PromotionDiyPage, count int64, err error) {
	result, err = p.Offset(offset).Limit(limit).Find()
	if err != nil {
		return
	}

	if size := len(result); 0 < limit && 0 < size && size < limit {
		count = int64(size + offset)
		return
	}

	count, err = p.Offset(-1).Limit(-1).Count()
	return
}

func (p promotionDiyPageDo) ScanByPage(result interface{}, offset int, limit int) (count int64, err error) {
	count, err = p.Count()
	if err != nil {
		return
	}

	err = p.Offset(offset).Limit(limit).Scan(result)
	return
}

func (p promotionDiyPageDo) Scan(result interface{}) (err error) {
	return p.DO.Scan(result)
}

func (p promotionDiyPageDo) Delete(models ...*promotion.PromotionDiyPage) (result gen.ResultInfo, err error) {
	return p.DO.Delete(models)
}

func (p *promotionDiyPageDo) withDO(do gen.Dao) *promotionDiyPageDo {
	p.DO = *do.(*gen.DO)
	return p
}
