// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package query

import (
	"context"
	"database/sql"

	"gorm.io/gorm"
	"gorm.io/gorm/clause"
	"gorm.io/gorm/schema"

	"gorm.io/gen"
	"gorm.io/gen/field"

	"gorm.io/plugin/dbresolver"

	"backend-go/internal/model/promotion"
)

func newPromotionArticle(db *gorm.DB, opts ...gen.DOOption) promotionArticle {
	_promotionArticle := promotionArticle{}

	_promotionArticle.promotionArticleDo.UseDB(db, opts...)
	_promotionArticle.promotionArticleDo.UseModel(&promotion.PromotionArticle{})

	tableName := _promotionArticle.promotionArticleDo.TableName()
	_promotionArticle.ALL = field.NewAsterisk(tableName)
	_promotionArticle.ID = field.NewInt64(tableName, "id")
	_promotionArticle.CategoryID = field.NewInt64(tableName, "category_id")
	_promotionArticle.Title = field.NewString(tableName, "title")
	_promotionArticle.Author = field.NewString(tableName, "author")
	_promotionArticle.PicURL = field.NewString(tableName, "pic_url")
	_promotionArticle.Introduction = field.NewString(tableName, "introduction")
	_promotionArticle.BrowseCount = field.NewInt(tableName, "browse_count")
	_promotionArticle.Sort = field.NewInt(tableName, "sort")
	_promotionArticle.Status = field.NewInt(tableName, "status")
	_promotionArticle.RecommendHot = field.NewBool(tableName, "recommend_hot")
	_promotionArticle.RecommendBanner = field.NewBool(tableName, "recommend_banner")
	_promotionArticle.Content = field.NewString(tableName, "content")
	_promotionArticle.Creator = field.NewString(tableName, "creator")
	_promotionArticle.CreateTime = field.NewTime(tableName, "create_time")
	_promotionArticle.Updater = field.NewString(tableName, "updater")
	_promotionArticle.UpdateTime = field.NewTime(tableName, "update_time")
	_promotionArticle.Deleted = field.NewInt(tableName, "deleted")
	_promotionArticle.TenantID = field.NewInt64(tableName, "tenant_id")

	_promotionArticle.fillFieldMap()

	return _promotionArticle
}

type promotionArticle struct {
	promotionArticleDo promotionArticleDo

	ALL             field.Asterisk
	ID              field.Int64
	CategoryID      field.Int64  // 分类ID
	Title           field.String // 文章标题
	Author          field.String // 文章作者
	PicURL          field.String // 封面图片
	Introduction    field.String // 文章简介
	BrowseCount     field.Int    // 浏览次数
	Sort            field.Int    // 排序
	Status          field.Int    // 状态
	RecommendHot    field.Bool   // 是否热门(小程序)
	RecommendBanner field.Bool   // 是否轮播图(小程序)
	Content         field.String // 文章内容
	Creator         field.String
	CreateTime      field.Time
	Updater         field.String
	UpdateTime      field.Time
	Deleted         field.Int
	TenantID        field.Int64

	fieldMap map[string]field.Expr
}

func (p promotionArticle) Table(newTableName string) *promotionArticle {
	p.promotionArticleDo.UseTable(newTableName)
	return p.updateTableName(newTableName)
}

func (p promotionArticle) As(alias string) *promotionArticle {
	p.promotionArticleDo.DO = *(p.promotionArticleDo.As(alias).(*gen.DO))
	return p.updateTableName(alias)
}

func (p *promotionArticle) updateTableName(table string) *promotionArticle {
	p.ALL = field.NewAsterisk(table)
	p.ID = field.NewInt64(table, "id")
	p.CategoryID = field.NewInt64(table, "category_id")
	p.Title = field.NewString(table, "title")
	p.Author = field.NewString(table, "author")
	p.PicURL = field.NewString(table, "pic_url")
	p.Introduction = field.NewString(table, "introduction")
	p.BrowseCount = field.NewInt(table, "browse_count")
	p.Sort = field.NewInt(table, "sort")
	p.Status = field.NewInt(table, "status")
	p.RecommendHot = field.NewBool(table, "recommend_hot")
	p.RecommendBanner = field.NewBool(table, "recommend_banner")
	p.Content = field.NewString(table, "content")
	p.Creator = field.NewString(table, "creator")
	p.CreateTime = field.NewTime(table, "create_time")
	p.Updater = field.NewString(table, "updater")
	p.UpdateTime = field.NewTime(table, "update_time")
	p.Deleted = field.NewInt(table, "deleted")
	p.TenantID = field.NewInt64(table, "tenant_id")

	p.fillFieldMap()

	return p
}

func (p *promotionArticle) WithContext(ctx context.Context) IPromotionArticleDo {
	return p.promotionArticleDo.WithContext(ctx)
}

func (p promotionArticle) TableName() string { return p.promotionArticleDo.TableName() }

func (p promotionArticle) Alias() string { return p.promotionArticleDo.Alias() }

func (p promotionArticle) Columns(cols ...field.Expr) gen.Columns {
	return p.promotionArticleDo.Columns(cols...)
}

func (p *promotionArticle) GetFieldByName(fieldName string) (field.OrderExpr, bool) {
	_f, ok := p.fieldMap[fieldName]
	if !ok || _f == nil {
		return nil, false
	}
	_oe, ok := _f.(field.OrderExpr)
	return _oe, ok
}

func (p *promotionArticle) fillFieldMap() {
	p.fieldMap = make(map[string]field.Expr, 18)
	p.fieldMap["id"] = p.ID
	p.fieldMap["category_id"] = p.CategoryID
	p.fieldMap["title"] = p.Title
	p.fieldMap["author"] = p.Author
	p.fieldMap["pic_url"] = p.PicURL
	p.fieldMap["introduction"] = p.Introduction
	p.fieldMap["browse_count"] = p.BrowseCount
	p.fieldMap["sort"] = p.Sort
	p.fieldMap["status"] = p.Status
	p.fieldMap["recommend_hot"] = p.RecommendHot
	p.fieldMap["recommend_banner"] = p.RecommendBanner
	p.fieldMap["content"] = p.Content
	p.fieldMap["creator"] = p.Creator
	p.fieldMap["create_time"] = p.CreateTime
	p.fieldMap["updater"] = p.Updater
	p.fieldMap["update_time"] = p.UpdateTime
	p.fieldMap["deleted"] = p.Deleted
	p.fieldMap["tenant_id"] = p.TenantID
}

func (p promotionArticle) clone(db *gorm.DB) promotionArticle {
	p.promotionArticleDo.ReplaceConnPool(db.Statement.ConnPool)
	return p
}

func (p promotionArticle) replaceDB(db *gorm.DB) promotionArticle {
	p.promotionArticleDo.ReplaceDB(db)
	return p
}

type promotionArticleDo struct{ gen.DO }

type IPromotionArticleDo interface {
	gen.SubQuery
	Debug() IPromotionArticleDo
	WithContext(ctx context.Context) IPromotionArticleDo
	WithResult(fc func(tx gen.Dao)) gen.ResultInfo
	ReplaceDB(db *gorm.DB)
	ReadDB() IPromotionArticleDo
	WriteDB() IPromotionArticleDo
	As(alias string) gen.Dao
	Session(config *gorm.Session) IPromotionArticleDo
	Columns(cols ...field.Expr) gen.Columns
	Clauses(conds ...clause.Expression) IPromotionArticleDo
	Not(conds ...gen.Condition) IPromotionArticleDo
	Or(conds ...gen.Condition) IPromotionArticleDo
	Select(conds ...field.Expr) IPromotionArticleDo
	Where(conds ...gen.Condition) IPromotionArticleDo
	Order(conds ...field.Expr) IPromotionArticleDo
	Distinct(cols ...field.Expr) IPromotionArticleDo
	Omit(cols ...field.Expr) IPromotionArticleDo
	Join(table schema.Tabler, on ...field.Expr) IPromotionArticleDo
	LeftJoin(table schema.Tabler, on ...field.Expr) IPromotionArticleDo
	RightJoin(table schema.Tabler, on ...field.Expr) IPromotionArticleDo
	Group(cols ...field.Expr) IPromotionArticleDo
	Having(conds ...gen.Condition) IPromotionArticleDo
	Limit(limit int) IPromotionArticleDo
	Offset(offset int) IPromotionArticleDo
	Count() (count int64, err error)
	Scopes(funcs ...func(gen.Dao) gen.Dao) IPromotionArticleDo
	Unscoped() IPromotionArticleDo
	Create(values ...*promotion.PromotionArticle) error
	CreateInBatches(values []*promotion.PromotionArticle, batchSize int) error
	Save(values ...*promotion.PromotionArticle) error
	First() (*promotion.PromotionArticle, error)
	Take() (*promotion.PromotionArticle, error)
	Last() (*promotion.PromotionArticle, error)
	Find() ([]*promotion.PromotionArticle, error)
	FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*promotion.PromotionArticle, err error)
	FindInBatches(result *[]*promotion.PromotionArticle, batchSize int, fc func(tx gen.Dao, batch int) error) error
	Pluck(column field.Expr, dest interface{}) error
	Delete(...*promotion.PromotionArticle) (info gen.ResultInfo, err error)
	Update(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	Updates(value interface{}) (info gen.ResultInfo, err error)
	UpdateColumn(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateColumnSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	UpdateColumns(value interface{}) (info gen.ResultInfo, err error)
	UpdateFrom(q gen.SubQuery) gen.Dao
	Attrs(attrs ...field.AssignExpr) IPromotionArticleDo
	Assign(attrs ...field.AssignExpr) IPromotionArticleDo
	Joins(fields ...field.RelationField) IPromotionArticleDo
	Preload(fields ...field.RelationField) IPromotionArticleDo
	FirstOrInit() (*promotion.PromotionArticle, error)
	FirstOrCreate() (*promotion.PromotionArticle, error)
	FindByPage(offset int, limit int) (result []*promotion.PromotionArticle, count int64, err error)
	ScanByPage(result interface{}, offset int, limit int) (count int64, err error)
	Rows() (*sql.Rows, error)
	Row() *sql.Row
	Scan(result interface{}) (err error)
	Returning(value interface{}, columns ...string) IPromotionArticleDo
	UnderlyingDB() *gorm.DB
	schema.Tabler
}

func (p promotionArticleDo) Debug() IPromotionArticleDo {
	return p.withDO(p.DO.Debug())
}

func (p promotionArticleDo) WithContext(ctx context.Context) IPromotionArticleDo {
	return p.withDO(p.DO.WithContext(ctx))
}

func (p promotionArticleDo) ReadDB() IPromotionArticleDo {
	return p.Clauses(dbresolver.Read)
}

func (p promotionArticleDo) WriteDB() IPromotionArticleDo {
	return p.Clauses(dbresolver.Write)
}

func (p promotionArticleDo) Session(config *gorm.Session) IPromotionArticleDo {
	return p.withDO(p.DO.Session(config))
}

func (p promotionArticleDo) Clauses(conds ...clause.Expression) IPromotionArticleDo {
	return p.withDO(p.DO.Clauses(conds...))
}

func (p promotionArticleDo) Returning(value interface{}, columns ...string) IPromotionArticleDo {
	return p.withDO(p.DO.Returning(value, columns...))
}

func (p promotionArticleDo) Not(conds ...gen.Condition) IPromotionArticleDo {
	return p.withDO(p.DO.Not(conds...))
}

func (p promotionArticleDo) Or(conds ...gen.Condition) IPromotionArticleDo {
	return p.withDO(p.DO.Or(conds...))
}

func (p promotionArticleDo) Select(conds ...field.Expr) IPromotionArticleDo {
	return p.withDO(p.DO.Select(conds...))
}

func (p promotionArticleDo) Where(conds ...gen.Condition) IPromotionArticleDo {
	return p.withDO(p.DO.Where(conds...))
}

func (p promotionArticleDo) Order(conds ...field.Expr) IPromotionArticleDo {
	return p.withDO(p.DO.Order(conds...))
}

func (p promotionArticleDo) Distinct(cols ...field.Expr) IPromotionArticleDo {
	return p.withDO(p.DO.Distinct(cols...))
}

func (p promotionArticleDo) Omit(cols ...field.Expr) IPromotionArticleDo {
	return p.withDO(p.DO.Omit(cols...))
}

func (p promotionArticleDo) Join(table schema.Tabler, on ...field.Expr) IPromotionArticleDo {
	return p.withDO(p.DO.Join(table, on...))
}

func (p promotionArticleDo) LeftJoin(table schema.Tabler, on ...field.Expr) IPromotionArticleDo {
	return p.withDO(p.DO.LeftJoin(table, on...))
}

func (p promotionArticleDo) RightJoin(table schema.Tabler, on ...field.Expr) IPromotionArticleDo {
	return p.withDO(p.DO.RightJoin(table, on...))
}

func (p promotionArticleDo) Group(cols ...field.Expr) IPromotionArticleDo {
	return p.withDO(p.DO.Group(cols...))
}

func (p promotionArticleDo) Having(conds ...gen.Condition) IPromotionArticleDo {
	return p.withDO(p.DO.Having(conds...))
}

func (p promotionArticleDo) Limit(limit int) IPromotionArticleDo {
	return p.withDO(p.DO.Limit(limit))
}

func (p promotionArticleDo) Offset(offset int) IPromotionArticleDo {
	return p.withDO(p.DO.Offset(offset))
}

func (p promotionArticleDo) Scopes(funcs ...func(gen.Dao) gen.Dao) IPromotionArticleDo {
	return p.withDO(p.DO.Scopes(funcs...))
}

func (p promotionArticleDo) Unscoped() IPromotionArticleDo {
	return p.withDO(p.DO.Unscoped())
}

func (p promotionArticleDo) Create(values ...*promotion.PromotionArticle) error {
	if len(values) == 0 {
		return nil
	}
	return p.DO.Create(values)
}

func (p promotionArticleDo) CreateInBatches(values []*promotion.PromotionArticle, batchSize int) error {
	return p.DO.CreateInBatches(values, batchSize)
}

// Save : !!! underlying implementation is different with GORM
// The method is equivalent to executing the statement: db.Clauses(clause.OnConflict{UpdateAll: true}).Create(values)
func (p promotionArticleDo) Save(values ...*promotion.PromotionArticle) error {
	if len(values) == 0 {
		return nil
	}
	return p.DO.Save(values)
}

func (p promotionArticleDo) First() (*promotion.PromotionArticle, error) {
	if result, err := p.DO.First(); err != nil {
		return nil, err
	} else {
		return result.(*promotion.PromotionArticle), nil
	}
}

func (p promotionArticleDo) Take() (*promotion.PromotionArticle, error) {
	if result, err := p.DO.Take(); err != nil {
		return nil, err
	} else {
		return result.(*promotion.PromotionArticle), nil
	}
}

func (p promotionArticleDo) Last() (*promotion.PromotionArticle, error) {
	if result, err := p.DO.Last(); err != nil {
		return nil, err
	} else {
		return result.(*promotion.PromotionArticle), nil
	}
}

func (p promotionArticleDo) Find() ([]*promotion.PromotionArticle, error) {
	result, err := p.DO.Find()
	return result.([]*promotion.PromotionArticle), err
}

func (p promotionArticleDo) FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*promotion.PromotionArticle, err error) {
	buf := make([]*promotion.PromotionArticle, 0, batchSize)
	err = p.DO.FindInBatches(&buf, batchSize, func(tx gen.Dao, batch int) error {
		defer func() { results = append(results, buf...) }()
		return fc(tx, batch)
	})
	return results, err
}

func (p promotionArticleDo) FindInBatches(result *[]*promotion.PromotionArticle, batchSize int, fc func(tx gen.Dao, batch int) error) error {
	return p.DO.FindInBatches(result, batchSize, fc)
}

func (p promotionArticleDo) Attrs(attrs ...field.AssignExpr) IPromotionArticleDo {
	return p.withDO(p.DO.Attrs(attrs...))
}

func (p promotionArticleDo) Assign(attrs ...field.AssignExpr) IPromotionArticleDo {
	return p.withDO(p.DO.Assign(attrs...))
}

func (p promotionArticleDo) Joins(fields ...field.RelationField) IPromotionArticleDo {
	for _, _f := range fields {
		p = *p.withDO(p.DO.Joins(_f))
	}
	return &p
}

func (p promotionArticleDo) Preload(fields ...field.RelationField) IPromotionArticleDo {
	for _, _f := range fields {
		p = *p.withDO(p.DO.Preload(_f))
	}
	return &p
}

func (p promotionArticleDo) FirstOrInit() (*promotion.PromotionArticle, error) {
	if result, err := p.DO.FirstOrInit(); err != nil {
		return nil, err
	} else {
		return result.(*promotion.PromotionArticle), nil
	}
}

func (p promotionArticleDo) FirstOrCreate() (*promotion.PromotionArticle, error) {
	if result, err := p.DO.FirstOrCreate(); err != nil {
		return nil, err
	} else {
		return result.(*promotion.PromotionArticle), nil
	}
}

func (p promotionArticleDo) FindByPage(offset int, limit int) (result []*promotion.PromotionArticle, count int64, err error) {
	result, err = p.Offset(offset).Limit(limit).Find()
	if err != nil {
		return
	}

	if size := len(result); 0 < limit && 0 < size && size < limit {
		count = int64(size + offset)
		return
	}

	count, err = p.Offset(-1).Limit(-1).Count()
	return
}

func (p promotionArticleDo) ScanByPage(result interface{}, offset int, limit int) (count int64, err error) {
	count, err = p.Count()
	if err != nil {
		return
	}

	err = p.Offset(offset).Limit(limit).Scan(result)
	return
}

func (p promotionArticleDo) Scan(result interface{}) (err error) {
	return p.DO.Scan(result)
}

func (p promotionArticleDo) Delete(models ...*promotion.PromotionArticle) (result gen.ResultInfo, err error) {
	return p.DO.Delete(models)
}

func (p *promotionArticleDo) withDO(do gen.Dao) *promotionArticleDo {
	p.DO = *do.(*gen.DO)
	return p
}
