// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package query

import (
	"context"
	"database/sql"

	"gorm.io/gorm"
	"gorm.io/gorm/clause"
	"gorm.io/gorm/schema"

	"gorm.io/gen"
	"gorm.io/gen/field"

	"gorm.io/plugin/dbresolver"

	"backend-go/internal/model/promotion"
)

func newPromotionKefuConversation(db *gorm.DB, opts ...gen.DOOption) promotionKefuConversation {
	_promotionKefuConversation := promotionKefuConversation{}

	_promotionKefuConversation.promotionKefuConversationDo.UseDB(db, opts...)
	_promotionKefuConversation.promotionKefuConversationDo.UseModel(&promotion.PromotionKefuConversation{})

	tableName := _promotionKefuConversation.promotionKefuConversationDo.TableName()
	_promotionKefuConversation.ALL = field.NewAsterisk(tableName)
	_promotionKefuConversation.ID = field.NewInt64(tableName, "id")
	_promotionKefuConversation.UserID = field.NewInt64(tableName, "user_id")
	_promotionKefuConversation.AdminID = field.NewInt64(tableName, "admin_id")
	_promotionKefuConversation.UserDeleted = field.NewBool(tableName, "user_deleted")
	_promotionKefuConversation.AdminDeleted = field.NewBool(tableName, "admin_deleted")
	_promotionKefuConversation.AdminUnreadCount = field.NewInt(tableName, "admin_unread_count")
	_promotionKefuConversation.UserUnreadCount = field.NewInt(tableName, "user_unread_count")
	_promotionKefuConversation.LastMessageTime = field.NewTime(tableName, "last_message_time")
	_promotionKefuConversation.LastMessageContent = field.NewString(tableName, "last_message_content")
	_promotionKefuConversation.LastMessageType = field.NewInt(tableName, "last_message_type")
	_promotionKefuConversation.Status = field.NewInt(tableName, "status")
	_promotionKefuConversation.Creator = field.NewString(tableName, "creator")
	_promotionKefuConversation.CreateTime = field.NewTime(tableName, "create_time")
	_promotionKefuConversation.Updater = field.NewString(tableName, "updater")
	_promotionKefuConversation.UpdateTime = field.NewTime(tableName, "update_time")
	_promotionKefuConversation.Deleted = field.NewInt(tableName, "deleted")
	_promotionKefuConversation.TenantID = field.NewInt64(tableName, "tenant_id")

	_promotionKefuConversation.fillFieldMap()

	return _promotionKefuConversation
}

type promotionKefuConversation struct {
	promotionKefuConversationDo promotionKefuConversationDo

	ALL                field.Asterisk
	ID                 field.Int64  // 编号
	UserID             field.Int64  // 用户编号
	AdminID            field.Int64  // 客服编号
	UserDeleted        field.Bool   // 用户是否删除
	AdminDeleted       field.Bool   // 客服是否删除
	AdminUnreadCount   field.Int    // 客服未读消息数
	UserUnreadCount    field.Int    // 用户未读消息数
	LastMessageTime    field.Time   // 最后一条消息时间
	LastMessageContent field.String // 最后一条消息内容
	LastMessageType    field.Int    // 最后一条消息类型
	Status             field.Int    // 会话状态
	Creator            field.String
	CreateTime         field.Time
	Updater            field.String
	UpdateTime         field.Time
	Deleted            field.Int
	TenantID           field.Int64

	fieldMap map[string]field.Expr
}

func (p promotionKefuConversation) Table(newTableName string) *promotionKefuConversation {
	p.promotionKefuConversationDo.UseTable(newTableName)
	return p.updateTableName(newTableName)
}

func (p promotionKefuConversation) As(alias string) *promotionKefuConversation {
	p.promotionKefuConversationDo.DO = *(p.promotionKefuConversationDo.As(alias).(*gen.DO))
	return p.updateTableName(alias)
}

func (p *promotionKefuConversation) updateTableName(table string) *promotionKefuConversation {
	p.ALL = field.NewAsterisk(table)
	p.ID = field.NewInt64(table, "id")
	p.UserID = field.NewInt64(table, "user_id")
	p.AdminID = field.NewInt64(table, "admin_id")
	p.UserDeleted = field.NewBool(table, "user_deleted")
	p.AdminDeleted = field.NewBool(table, "admin_deleted")
	p.AdminUnreadCount = field.NewInt(table, "admin_unread_count")
	p.UserUnreadCount = field.NewInt(table, "user_unread_count")
	p.LastMessageTime = field.NewTime(table, "last_message_time")
	p.LastMessageContent = field.NewString(table, "last_message_content")
	p.LastMessageType = field.NewInt(table, "last_message_type")
	p.Status = field.NewInt(table, "status")
	p.Creator = field.NewString(table, "creator")
	p.CreateTime = field.NewTime(table, "create_time")
	p.Updater = field.NewString(table, "updater")
	p.UpdateTime = field.NewTime(table, "update_time")
	p.Deleted = field.NewInt(table, "deleted")
	p.TenantID = field.NewInt64(table, "tenant_id")

	p.fillFieldMap()

	return p
}

func (p *promotionKefuConversation) WithContext(ctx context.Context) IPromotionKefuConversationDo {
	return p.promotionKefuConversationDo.WithContext(ctx)
}

func (p promotionKefuConversation) TableName() string {
	return p.promotionKefuConversationDo.TableName()
}

func (p promotionKefuConversation) Alias() string { return p.promotionKefuConversationDo.Alias() }

func (p promotionKefuConversation) Columns(cols ...field.Expr) gen.Columns {
	return p.promotionKefuConversationDo.Columns(cols...)
}

func (p *promotionKefuConversation) GetFieldByName(fieldName string) (field.OrderExpr, bool) {
	_f, ok := p.fieldMap[fieldName]
	if !ok || _f == nil {
		return nil, false
	}
	_oe, ok := _f.(field.OrderExpr)
	return _oe, ok
}

func (p *promotionKefuConversation) fillFieldMap() {
	p.fieldMap = make(map[string]field.Expr, 17)
	p.fieldMap["id"] = p.ID
	p.fieldMap["user_id"] = p.UserID
	p.fieldMap["admin_id"] = p.AdminID
	p.fieldMap["user_deleted"] = p.UserDeleted
	p.fieldMap["admin_deleted"] = p.AdminDeleted
	p.fieldMap["admin_unread_count"] = p.AdminUnreadCount
	p.fieldMap["user_unread_count"] = p.UserUnreadCount
	p.fieldMap["last_message_time"] = p.LastMessageTime
	p.fieldMap["last_message_content"] = p.LastMessageContent
	p.fieldMap["last_message_type"] = p.LastMessageType
	p.fieldMap["status"] = p.Status
	p.fieldMap["creator"] = p.Creator
	p.fieldMap["create_time"] = p.CreateTime
	p.fieldMap["updater"] = p.Updater
	p.fieldMap["update_time"] = p.UpdateTime
	p.fieldMap["deleted"] = p.Deleted
	p.fieldMap["tenant_id"] = p.TenantID
}

func (p promotionKefuConversation) clone(db *gorm.DB) promotionKefuConversation {
	p.promotionKefuConversationDo.ReplaceConnPool(db.Statement.ConnPool)
	return p
}

func (p promotionKefuConversation) replaceDB(db *gorm.DB) promotionKefuConversation {
	p.promotionKefuConversationDo.ReplaceDB(db)
	return p
}

type promotionKefuConversationDo struct{ gen.DO }

type IPromotionKefuConversationDo interface {
	gen.SubQuery
	Debug() IPromotionKefuConversationDo
	WithContext(ctx context.Context) IPromotionKefuConversationDo
	WithResult(fc func(tx gen.Dao)) gen.ResultInfo
	ReplaceDB(db *gorm.DB)
	ReadDB() IPromotionKefuConversationDo
	WriteDB() IPromotionKefuConversationDo
	As(alias string) gen.Dao
	Session(config *gorm.Session) IPromotionKefuConversationDo
	Columns(cols ...field.Expr) gen.Columns
	Clauses(conds ...clause.Expression) IPromotionKefuConversationDo
	Not(conds ...gen.Condition) IPromotionKefuConversationDo
	Or(conds ...gen.Condition) IPromotionKefuConversationDo
	Select(conds ...field.Expr) IPromotionKefuConversationDo
	Where(conds ...gen.Condition) IPromotionKefuConversationDo
	Order(conds ...field.Expr) IPromotionKefuConversationDo
	Distinct(cols ...field.Expr) IPromotionKefuConversationDo
	Omit(cols ...field.Expr) IPromotionKefuConversationDo
	Join(table schema.Tabler, on ...field.Expr) IPromotionKefuConversationDo
	LeftJoin(table schema.Tabler, on ...field.Expr) IPromotionKefuConversationDo
	RightJoin(table schema.Tabler, on ...field.Expr) IPromotionKefuConversationDo
	Group(cols ...field.Expr) IPromotionKefuConversationDo
	Having(conds ...gen.Condition) IPromotionKefuConversationDo
	Limit(limit int) IPromotionKefuConversationDo
	Offset(offset int) IPromotionKefuConversationDo
	Count() (count int64, err error)
	Scopes(funcs ...func(gen.Dao) gen.Dao) IPromotionKefuConversationDo
	Unscoped() IPromotionKefuConversationDo
	Create(values ...*promotion.PromotionKefuConversation) error
	CreateInBatches(values []*promotion.PromotionKefuConversation, batchSize int) error
	Save(values ...*promotion.PromotionKefuConversation) error
	First() (*promotion.PromotionKefuConversation, error)
	Take() (*promotion.PromotionKefuConversation, error)
	Last() (*promotion.PromotionKefuConversation, error)
	Find() ([]*promotion.PromotionKefuConversation, error)
	FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*promotion.PromotionKefuConversation, err error)
	FindInBatches(result *[]*promotion.PromotionKefuConversation, batchSize int, fc func(tx gen.Dao, batch int) error) error
	Pluck(column field.Expr, dest interface{}) error
	Delete(...*promotion.PromotionKefuConversation) (info gen.ResultInfo, err error)
	Update(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	Updates(value interface{}) (info gen.ResultInfo, err error)
	UpdateColumn(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateColumnSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	UpdateColumns(value interface{}) (info gen.ResultInfo, err error)
	UpdateFrom(q gen.SubQuery) gen.Dao
	Attrs(attrs ...field.AssignExpr) IPromotionKefuConversationDo
	Assign(attrs ...field.AssignExpr) IPromotionKefuConversationDo
	Joins(fields ...field.RelationField) IPromotionKefuConversationDo
	Preload(fields ...field.RelationField) IPromotionKefuConversationDo
	FirstOrInit() (*promotion.PromotionKefuConversation, error)
	FirstOrCreate() (*promotion.PromotionKefuConversation, error)
	FindByPage(offset int, limit int) (result []*promotion.PromotionKefuConversation, count int64, err error)
	ScanByPage(result interface{}, offset int, limit int) (count int64, err error)
	Rows() (*sql.Rows, error)
	Row() *sql.Row
	Scan(result interface{}) (err error)
	Returning(value interface{}, columns ...string) IPromotionKefuConversationDo
	UnderlyingDB() *gorm.DB
	schema.Tabler
}

func (p promotionKefuConversationDo) Debug() IPromotionKefuConversationDo {
	return p.withDO(p.DO.Debug())
}

func (p promotionKefuConversationDo) WithContext(ctx context.Context) IPromotionKefuConversationDo {
	return p.withDO(p.DO.WithContext(ctx))
}

func (p promotionKefuConversationDo) ReadDB() IPromotionKefuConversationDo {
	return p.Clauses(dbresolver.Read)
}

func (p promotionKefuConversationDo) WriteDB() IPromotionKefuConversationDo {
	return p.Clauses(dbresolver.Write)
}

func (p promotionKefuConversationDo) Session(config *gorm.Session) IPromotionKefuConversationDo {
	return p.withDO(p.DO.Session(config))
}

func (p promotionKefuConversationDo) Clauses(conds ...clause.Expression) IPromotionKefuConversationDo {
	return p.withDO(p.DO.Clauses(conds...))
}

func (p promotionKefuConversationDo) Returning(value interface{}, columns ...string) IPromotionKefuConversationDo {
	return p.withDO(p.DO.Returning(value, columns...))
}

func (p promotionKefuConversationDo) Not(conds ...gen.Condition) IPromotionKefuConversationDo {
	return p.withDO(p.DO.Not(conds...))
}

func (p promotionKefuConversationDo) Or(conds ...gen.Condition) IPromotionKefuConversationDo {
	return p.withDO(p.DO.Or(conds...))
}

func (p promotionKefuConversationDo) Select(conds ...field.Expr) IPromotionKefuConversationDo {
	return p.withDO(p.DO.Select(conds...))
}

func (p promotionKefuConversationDo) Where(conds ...gen.Condition) IPromotionKefuConversationDo {
	return p.withDO(p.DO.Where(conds...))
}

func (p promotionKefuConversationDo) Order(conds ...field.Expr) IPromotionKefuConversationDo {
	return p.withDO(p.DO.Order(conds...))
}

func (p promotionKefuConversationDo) Distinct(cols ...field.Expr) IPromotionKefuConversationDo {
	return p.withDO(p.DO.Distinct(cols...))
}

func (p promotionKefuConversationDo) Omit(cols ...field.Expr) IPromotionKefuConversationDo {
	return p.withDO(p.DO.Omit(cols...))
}

func (p promotionKefuConversationDo) Join(table schema.Tabler, on ...field.Expr) IPromotionKefuConversationDo {
	return p.withDO(p.DO.Join(table, on...))
}

func (p promotionKefuConversationDo) LeftJoin(table schema.Tabler, on ...field.Expr) IPromotionKefuConversationDo {
	return p.withDO(p.DO.LeftJoin(table, on...))
}

func (p promotionKefuConversationDo) RightJoin(table schema.Tabler, on ...field.Expr) IPromotionKefuConversationDo {
	return p.withDO(p.DO.RightJoin(table, on...))
}

func (p promotionKefuConversationDo) Group(cols ...field.Expr) IPromotionKefuConversationDo {
	return p.withDO(p.DO.Group(cols...))
}

func (p promotionKefuConversationDo) Having(conds ...gen.Condition) IPromotionKefuConversationDo {
	return p.withDO(p.DO.Having(conds...))
}

func (p promotionKefuConversationDo) Limit(limit int) IPromotionKefuConversationDo {
	return p.withDO(p.DO.Limit(limit))
}

func (p promotionKefuConversationDo) Offset(offset int) IPromotionKefuConversationDo {
	return p.withDO(p.DO.Offset(offset))
}

func (p promotionKefuConversationDo) Scopes(funcs ...func(gen.Dao) gen.Dao) IPromotionKefuConversationDo {
	return p.withDO(p.DO.Scopes(funcs...))
}

func (p promotionKefuConversationDo) Unscoped() IPromotionKefuConversationDo {
	return p.withDO(p.DO.Unscoped())
}

func (p promotionKefuConversationDo) Create(values ...*promotion.PromotionKefuConversation) error {
	if len(values) == 0 {
		return nil
	}
	return p.DO.Create(values)
}

func (p promotionKefuConversationDo) CreateInBatches(values []*promotion.PromotionKefuConversation, batchSize int) error {
	return p.DO.CreateInBatches(values, batchSize)
}

// Save : !!! underlying implementation is different with GORM
// The method is equivalent to executing the statement: db.Clauses(clause.OnConflict{UpdateAll: true}).Create(values)
func (p promotionKefuConversationDo) Save(values ...*promotion.PromotionKefuConversation) error {
	if len(values) == 0 {
		return nil
	}
	return p.DO.Save(values)
}

func (p promotionKefuConversationDo) First() (*promotion.PromotionKefuConversation, error) {
	if result, err := p.DO.First(); err != nil {
		return nil, err
	} else {
		return result.(*promotion.PromotionKefuConversation), nil
	}
}

func (p promotionKefuConversationDo) Take() (*promotion.PromotionKefuConversation, error) {
	if result, err := p.DO.Take(); err != nil {
		return nil, err
	} else {
		return result.(*promotion.PromotionKefuConversation), nil
	}
}

func (p promotionKefuConversationDo) Last() (*promotion.PromotionKefuConversation, error) {
	if result, err := p.DO.Last(); err != nil {
		return nil, err
	} else {
		return result.(*promotion.PromotionKefuConversation), nil
	}
}

func (p promotionKefuConversationDo) Find() ([]*promotion.PromotionKefuConversation, error) {
	result, err := p.DO.Find()
	return result.([]*promotion.PromotionKefuConversation), err
}

func (p promotionKefuConversationDo) FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*promotion.PromotionKefuConversation, err error) {
	buf := make([]*promotion.PromotionKefuConversation, 0, batchSize)
	err = p.DO.FindInBatches(&buf, batchSize, func(tx gen.Dao, batch int) error {
		defer func() { results = append(results, buf...) }()
		return fc(tx, batch)
	})
	return results, err
}

func (p promotionKefuConversationDo) FindInBatches(result *[]*promotion.PromotionKefuConversation, batchSize int, fc func(tx gen.Dao, batch int) error) error {
	return p.DO.FindInBatches(result, batchSize, fc)
}

func (p promotionKefuConversationDo) Attrs(attrs ...field.AssignExpr) IPromotionKefuConversationDo {
	return p.withDO(p.DO.Attrs(attrs...))
}

func (p promotionKefuConversationDo) Assign(attrs ...field.AssignExpr) IPromotionKefuConversationDo {
	return p.withDO(p.DO.Assign(attrs...))
}

func (p promotionKefuConversationDo) Joins(fields ...field.RelationField) IPromotionKefuConversationDo {
	for _, _f := range fields {
		p = *p.withDO(p.DO.Joins(_f))
	}
	return &p
}

func (p promotionKefuConversationDo) Preload(fields ...field.RelationField) IPromotionKefuConversationDo {
	for _, _f := range fields {
		p = *p.withDO(p.DO.Preload(_f))
	}
	return &p
}

func (p promotionKefuConversationDo) FirstOrInit() (*promotion.PromotionKefuConversation, error) {
	if result, err := p.DO.FirstOrInit(); err != nil {
		return nil, err
	} else {
		return result.(*promotion.PromotionKefuConversation), nil
	}
}

func (p promotionKefuConversationDo) FirstOrCreate() (*promotion.PromotionKefuConversation, error) {
	if result, err := p.DO.FirstOrCreate(); err != nil {
		return nil, err
	} else {
		return result.(*promotion.PromotionKefuConversation), nil
	}
}

func (p promotionKefuConversationDo) FindByPage(offset int, limit int) (result []*promotion.PromotionKefuConversation, count int64, err error) {
	result, err = p.Offset(offset).Limit(limit).Find()
	if err != nil {
		return
	}

	if size := len(result); 0 < limit && 0 < size && size < limit {
		count = int64(size + offset)
		return
	}

	count, err = p.Offset(-1).Limit(-1).Count()
	return
}

func (p promotionKefuConversationDo) ScanByPage(result interface{}, offset int, limit int) (count int64, err error) {
	count, err = p.Count()
	if err != nil {
		return
	}

	err = p.Offset(offset).Limit(limit).Scan(result)
	return
}

func (p promotionKefuConversationDo) Scan(result interface{}) (err error) {
	return p.DO.Scan(result)
}

func (p promotionKefuConversationDo) Delete(models ...*promotion.PromotionKefuConversation) (result gen.ResultInfo, err error) {
	return p.DO.Delete(models)
}

func (p *promotionKefuConversationDo) withDO(do gen.Dao) *promotionKefuConversationDo {
	p.DO = *do.(*gen.DO)
	return p
}
