// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package query

import (
	"context"
	"database/sql"

	"gorm.io/gorm"
	"gorm.io/gorm/clause"
	"gorm.io/gorm/schema"

	"gorm.io/gen"
	"gorm.io/gen/field"

	"gorm.io/plugin/dbresolver"

	"backend-go/internal/model/promotion"
)

func newPromotionDiscountProduct(db *gorm.DB, opts ...gen.DOOption) promotionDiscountProduct {
	_promotionDiscountProduct := promotionDiscountProduct{}

	_promotionDiscountProduct.promotionDiscountProductDo.UseDB(db, opts...)
	_promotionDiscountProduct.promotionDiscountProductDo.UseModel(&promotion.PromotionDiscountProduct{})

	tableName := _promotionDiscountProduct.promotionDiscountProductDo.TableName()
	_promotionDiscountProduct.ALL = field.NewAsterisk(tableName)
	_promotionDiscountProduct.ID = field.NewInt64(tableName, "id")
	_promotionDiscountProduct.ActivityID = field.NewInt64(tableName, "activity_id")
	_promotionDiscountProduct.SpuID = field.NewInt64(tableName, "spu_id")
	_promotionDiscountProduct.SkuID = field.NewInt64(tableName, "sku_id")
	_promotionDiscountProduct.DiscountType = field.NewInt(tableName, "discount_type")
	_promotionDiscountProduct.DiscountPercent = field.NewInt(tableName, "discount_percent")
	_promotionDiscountProduct.DiscountPrice = field.NewInt(tableName, "discount_price")
	_promotionDiscountProduct.ActivityName = field.NewString(tableName, "activity_name")
	_promotionDiscountProduct.ActivityStatus = field.NewInt(tableName, "activity_status")
	_promotionDiscountProduct.ActivityStartTime = field.NewTime(tableName, "activity_start_time")
	_promotionDiscountProduct.ActivityEndTime = field.NewTime(tableName, "activity_end_time")
	_promotionDiscountProduct.Creator = field.NewString(tableName, "creator")
	_promotionDiscountProduct.CreateTime = field.NewTime(tableName, "create_time")
	_promotionDiscountProduct.Updater = field.NewString(tableName, "updater")
	_promotionDiscountProduct.UpdateTime = field.NewTime(tableName, "update_time")
	_promotionDiscountProduct.Deleted = field.NewInt(tableName, "deleted")
	_promotionDiscountProduct.TenantID = field.NewInt64(tableName, "tenant_id")

	_promotionDiscountProduct.fillFieldMap()

	return _promotionDiscountProduct
}

type promotionDiscountProduct struct {
	promotionDiscountProductDo promotionDiscountProductDo

	ALL               field.Asterisk
	ID                field.Int64
	ActivityID        field.Int64
	SpuID             field.Int64
	SkuID             field.Int64
	DiscountType      field.Int
	DiscountPercent   field.Int
	DiscountPrice     field.Int
	ActivityName      field.String
	ActivityStatus    field.Int
	ActivityStartTime field.Time
	ActivityEndTime   field.Time
	Creator           field.String
	CreateTime        field.Time
	Updater           field.String
	UpdateTime        field.Time
	Deleted           field.Int
	TenantID          field.Int64

	fieldMap map[string]field.Expr
}

func (p promotionDiscountProduct) Table(newTableName string) *promotionDiscountProduct {
	p.promotionDiscountProductDo.UseTable(newTableName)
	return p.updateTableName(newTableName)
}

func (p promotionDiscountProduct) As(alias string) *promotionDiscountProduct {
	p.promotionDiscountProductDo.DO = *(p.promotionDiscountProductDo.As(alias).(*gen.DO))
	return p.updateTableName(alias)
}

func (p *promotionDiscountProduct) updateTableName(table string) *promotionDiscountProduct {
	p.ALL = field.NewAsterisk(table)
	p.ID = field.NewInt64(table, "id")
	p.ActivityID = field.NewInt64(table, "activity_id")
	p.SpuID = field.NewInt64(table, "spu_id")
	p.SkuID = field.NewInt64(table, "sku_id")
	p.DiscountType = field.NewInt(table, "discount_type")
	p.DiscountPercent = field.NewInt(table, "discount_percent")
	p.DiscountPrice = field.NewInt(table, "discount_price")
	p.ActivityName = field.NewString(table, "activity_name")
	p.ActivityStatus = field.NewInt(table, "activity_status")
	p.ActivityStartTime = field.NewTime(table, "activity_start_time")
	p.ActivityEndTime = field.NewTime(table, "activity_end_time")
	p.Creator = field.NewString(table, "creator")
	p.CreateTime = field.NewTime(table, "create_time")
	p.Updater = field.NewString(table, "updater")
	p.UpdateTime = field.NewTime(table, "update_time")
	p.Deleted = field.NewInt(table, "deleted")
	p.TenantID = field.NewInt64(table, "tenant_id")

	p.fillFieldMap()

	return p
}

func (p *promotionDiscountProduct) WithContext(ctx context.Context) IPromotionDiscountProductDo {
	return p.promotionDiscountProductDo.WithContext(ctx)
}

func (p promotionDiscountProduct) TableName() string { return p.promotionDiscountProductDo.TableName() }

func (p promotionDiscountProduct) Alias() string { return p.promotionDiscountProductDo.Alias() }

func (p promotionDiscountProduct) Columns(cols ...field.Expr) gen.Columns {
	return p.promotionDiscountProductDo.Columns(cols...)
}

func (p *promotionDiscountProduct) GetFieldByName(fieldName string) (field.OrderExpr, bool) {
	_f, ok := p.fieldMap[fieldName]
	if !ok || _f == nil {
		return nil, false
	}
	_oe, ok := _f.(field.OrderExpr)
	return _oe, ok
}

func (p *promotionDiscountProduct) fillFieldMap() {
	p.fieldMap = make(map[string]field.Expr, 17)
	p.fieldMap["id"] = p.ID
	p.fieldMap["activity_id"] = p.ActivityID
	p.fieldMap["spu_id"] = p.SpuID
	p.fieldMap["sku_id"] = p.SkuID
	p.fieldMap["discount_type"] = p.DiscountType
	p.fieldMap["discount_percent"] = p.DiscountPercent
	p.fieldMap["discount_price"] = p.DiscountPrice
	p.fieldMap["activity_name"] = p.ActivityName
	p.fieldMap["activity_status"] = p.ActivityStatus
	p.fieldMap["activity_start_time"] = p.ActivityStartTime
	p.fieldMap["activity_end_time"] = p.ActivityEndTime
	p.fieldMap["creator"] = p.Creator
	p.fieldMap["create_time"] = p.CreateTime
	p.fieldMap["updater"] = p.Updater
	p.fieldMap["update_time"] = p.UpdateTime
	p.fieldMap["deleted"] = p.Deleted
	p.fieldMap["tenant_id"] = p.TenantID
}

func (p promotionDiscountProduct) clone(db *gorm.DB) promotionDiscountProduct {
	p.promotionDiscountProductDo.ReplaceConnPool(db.Statement.ConnPool)
	return p
}

func (p promotionDiscountProduct) replaceDB(db *gorm.DB) promotionDiscountProduct {
	p.promotionDiscountProductDo.ReplaceDB(db)
	return p
}

type promotionDiscountProductDo struct{ gen.DO }

type IPromotionDiscountProductDo interface {
	gen.SubQuery
	Debug() IPromotionDiscountProductDo
	WithContext(ctx context.Context) IPromotionDiscountProductDo
	WithResult(fc func(tx gen.Dao)) gen.ResultInfo
	ReplaceDB(db *gorm.DB)
	ReadDB() IPromotionDiscountProductDo
	WriteDB() IPromotionDiscountProductDo
	As(alias string) gen.Dao
	Session(config *gorm.Session) IPromotionDiscountProductDo
	Columns(cols ...field.Expr) gen.Columns
	Clauses(conds ...clause.Expression) IPromotionDiscountProductDo
	Not(conds ...gen.Condition) IPromotionDiscountProductDo
	Or(conds ...gen.Condition) IPromotionDiscountProductDo
	Select(conds ...field.Expr) IPromotionDiscountProductDo
	Where(conds ...gen.Condition) IPromotionDiscountProductDo
	Order(conds ...field.Expr) IPromotionDiscountProductDo
	Distinct(cols ...field.Expr) IPromotionDiscountProductDo
	Omit(cols ...field.Expr) IPromotionDiscountProductDo
	Join(table schema.Tabler, on ...field.Expr) IPromotionDiscountProductDo
	LeftJoin(table schema.Tabler, on ...field.Expr) IPromotionDiscountProductDo
	RightJoin(table schema.Tabler, on ...field.Expr) IPromotionDiscountProductDo
	Group(cols ...field.Expr) IPromotionDiscountProductDo
	Having(conds ...gen.Condition) IPromotionDiscountProductDo
	Limit(limit int) IPromotionDiscountProductDo
	Offset(offset int) IPromotionDiscountProductDo
	Count() (count int64, err error)
	Scopes(funcs ...func(gen.Dao) gen.Dao) IPromotionDiscountProductDo
	Unscoped() IPromotionDiscountProductDo
	Create(values ...*promotion.PromotionDiscountProduct) error
	CreateInBatches(values []*promotion.PromotionDiscountProduct, batchSize int) error
	Save(values ...*promotion.PromotionDiscountProduct) error
	First() (*promotion.PromotionDiscountProduct, error)
	Take() (*promotion.PromotionDiscountProduct, error)
	Last() (*promotion.PromotionDiscountProduct, error)
	Find() ([]*promotion.PromotionDiscountProduct, error)
	FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*promotion.PromotionDiscountProduct, err error)
	FindInBatches(result *[]*promotion.PromotionDiscountProduct, batchSize int, fc func(tx gen.Dao, batch int) error) error
	Pluck(column field.Expr, dest interface{}) error
	Delete(...*promotion.PromotionDiscountProduct) (info gen.ResultInfo, err error)
	Update(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	Updates(value interface{}) (info gen.ResultInfo, err error)
	UpdateColumn(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateColumnSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	UpdateColumns(value interface{}) (info gen.ResultInfo, err error)
	UpdateFrom(q gen.SubQuery) gen.Dao
	Attrs(attrs ...field.AssignExpr) IPromotionDiscountProductDo
	Assign(attrs ...field.AssignExpr) IPromotionDiscountProductDo
	Joins(fields ...field.RelationField) IPromotionDiscountProductDo
	Preload(fields ...field.RelationField) IPromotionDiscountProductDo
	FirstOrInit() (*promotion.PromotionDiscountProduct, error)
	FirstOrCreate() (*promotion.PromotionDiscountProduct, error)
	FindByPage(offset int, limit int) (result []*promotion.PromotionDiscountProduct, count int64, err error)
	ScanByPage(result interface{}, offset int, limit int) (count int64, err error)
	Rows() (*sql.Rows, error)
	Row() *sql.Row
	Scan(result interface{}) (err error)
	Returning(value interface{}, columns ...string) IPromotionDiscountProductDo
	UnderlyingDB() *gorm.DB
	schema.Tabler
}

func (p promotionDiscountProductDo) Debug() IPromotionDiscountProductDo {
	return p.withDO(p.DO.Debug())
}

func (p promotionDiscountProductDo) WithContext(ctx context.Context) IPromotionDiscountProductDo {
	return p.withDO(p.DO.WithContext(ctx))
}

func (p promotionDiscountProductDo) ReadDB() IPromotionDiscountProductDo {
	return p.Clauses(dbresolver.Read)
}

func (p promotionDiscountProductDo) WriteDB() IPromotionDiscountProductDo {
	return p.Clauses(dbresolver.Write)
}

func (p promotionDiscountProductDo) Session(config *gorm.Session) IPromotionDiscountProductDo {
	return p.withDO(p.DO.Session(config))
}

func (p promotionDiscountProductDo) Clauses(conds ...clause.Expression) IPromotionDiscountProductDo {
	return p.withDO(p.DO.Clauses(conds...))
}

func (p promotionDiscountProductDo) Returning(value interface{}, columns ...string) IPromotionDiscountProductDo {
	return p.withDO(p.DO.Returning(value, columns...))
}

func (p promotionDiscountProductDo) Not(conds ...gen.Condition) IPromotionDiscountProductDo {
	return p.withDO(p.DO.Not(conds...))
}

func (p promotionDiscountProductDo) Or(conds ...gen.Condition) IPromotionDiscountProductDo {
	return p.withDO(p.DO.Or(conds...))
}

func (p promotionDiscountProductDo) Select(conds ...field.Expr) IPromotionDiscountProductDo {
	return p.withDO(p.DO.Select(conds...))
}

func (p promotionDiscountProductDo) Where(conds ...gen.Condition) IPromotionDiscountProductDo {
	return p.withDO(p.DO.Where(conds...))
}

func (p promotionDiscountProductDo) Order(conds ...field.Expr) IPromotionDiscountProductDo {
	return p.withDO(p.DO.Order(conds...))
}

func (p promotionDiscountProductDo) Distinct(cols ...field.Expr) IPromotionDiscountProductDo {
	return p.withDO(p.DO.Distinct(cols...))
}

func (p promotionDiscountProductDo) Omit(cols ...field.Expr) IPromotionDiscountProductDo {
	return p.withDO(p.DO.Omit(cols...))
}

func (p promotionDiscountProductDo) Join(table schema.Tabler, on ...field.Expr) IPromotionDiscountProductDo {
	return p.withDO(p.DO.Join(table, on...))
}

func (p promotionDiscountProductDo) LeftJoin(table schema.Tabler, on ...field.Expr) IPromotionDiscountProductDo {
	return p.withDO(p.DO.LeftJoin(table, on...))
}

func (p promotionDiscountProductDo) RightJoin(table schema.Tabler, on ...field.Expr) IPromotionDiscountProductDo {
	return p.withDO(p.DO.RightJoin(table, on...))
}

func (p promotionDiscountProductDo) Group(cols ...field.Expr) IPromotionDiscountProductDo {
	return p.withDO(p.DO.Group(cols...))
}

func (p promotionDiscountProductDo) Having(conds ...gen.Condition) IPromotionDiscountProductDo {
	return p.withDO(p.DO.Having(conds...))
}

func (p promotionDiscountProductDo) Limit(limit int) IPromotionDiscountProductDo {
	return p.withDO(p.DO.Limit(limit))
}

func (p promotionDiscountProductDo) Offset(offset int) IPromotionDiscountProductDo {
	return p.withDO(p.DO.Offset(offset))
}

func (p promotionDiscountProductDo) Scopes(funcs ...func(gen.Dao) gen.Dao) IPromotionDiscountProductDo {
	return p.withDO(p.DO.Scopes(funcs...))
}

func (p promotionDiscountProductDo) Unscoped() IPromotionDiscountProductDo {
	return p.withDO(p.DO.Unscoped())
}

func (p promotionDiscountProductDo) Create(values ...*promotion.PromotionDiscountProduct) error {
	if len(values) == 0 {
		return nil
	}
	return p.DO.Create(values)
}

func (p promotionDiscountProductDo) CreateInBatches(values []*promotion.PromotionDiscountProduct, batchSize int) error {
	return p.DO.CreateInBatches(values, batchSize)
}

// Save : !!! underlying implementation is different with GORM
// The method is equivalent to executing the statement: db.Clauses(clause.OnConflict{UpdateAll: true}).Create(values)
func (p promotionDiscountProductDo) Save(values ...*promotion.PromotionDiscountProduct) error {
	if len(values) == 0 {
		return nil
	}
	return p.DO.Save(values)
}

func (p promotionDiscountProductDo) First() (*promotion.PromotionDiscountProduct, error) {
	if result, err := p.DO.First(); err != nil {
		return nil, err
	} else {
		return result.(*promotion.PromotionDiscountProduct), nil
	}
}

func (p promotionDiscountProductDo) Take() (*promotion.PromotionDiscountProduct, error) {
	if result, err := p.DO.Take(); err != nil {
		return nil, err
	} else {
		return result.(*promotion.PromotionDiscountProduct), nil
	}
}

func (p promotionDiscountProductDo) Last() (*promotion.PromotionDiscountProduct, error) {
	if result, err := p.DO.Last(); err != nil {
		return nil, err
	} else {
		return result.(*promotion.PromotionDiscountProduct), nil
	}
}

func (p promotionDiscountProductDo) Find() ([]*promotion.PromotionDiscountProduct, error) {
	result, err := p.DO.Find()
	return result.([]*promotion.PromotionDiscountProduct), err
}

func (p promotionDiscountProductDo) FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*promotion.PromotionDiscountProduct, err error) {
	buf := make([]*promotion.PromotionDiscountProduct, 0, batchSize)
	err = p.DO.FindInBatches(&buf, batchSize, func(tx gen.Dao, batch int) error {
		defer func() { results = append(results, buf...) }()
		return fc(tx, batch)
	})
	return results, err
}

func (p promotionDiscountProductDo) FindInBatches(result *[]*promotion.PromotionDiscountProduct, batchSize int, fc func(tx gen.Dao, batch int) error) error {
	return p.DO.FindInBatches(result, batchSize, fc)
}

func (p promotionDiscountProductDo) Attrs(attrs ...field.AssignExpr) IPromotionDiscountProductDo {
	return p.withDO(p.DO.Attrs(attrs...))
}

func (p promotionDiscountProductDo) Assign(attrs ...field.AssignExpr) IPromotionDiscountProductDo {
	return p.withDO(p.DO.Assign(attrs...))
}

func (p promotionDiscountProductDo) Joins(fields ...field.RelationField) IPromotionDiscountProductDo {
	for _, _f := range fields {
		p = *p.withDO(p.DO.Joins(_f))
	}
	return &p
}

func (p promotionDiscountProductDo) Preload(fields ...field.RelationField) IPromotionDiscountProductDo {
	for _, _f := range fields {
		p = *p.withDO(p.DO.Preload(_f))
	}
	return &p
}

func (p promotionDiscountProductDo) FirstOrInit() (*promotion.PromotionDiscountProduct, error) {
	if result, err := p.DO.FirstOrInit(); err != nil {
		return nil, err
	} else {
		return result.(*promotion.PromotionDiscountProduct), nil
	}
}

func (p promotionDiscountProductDo) FirstOrCreate() (*promotion.PromotionDiscountProduct, error) {
	if result, err := p.DO.FirstOrCreate(); err != nil {
		return nil, err
	} else {
		return result.(*promotion.PromotionDiscountProduct), nil
	}
}

func (p promotionDiscountProductDo) FindByPage(offset int, limit int) (result []*promotion.PromotionDiscountProduct, count int64, err error) {
	result, err = p.Offset(offset).Limit(limit).Find()
	if err != nil {
		return
	}

	if size := len(result); 0 < limit && 0 < size && size < limit {
		count = int64(size + offset)
		return
	}

	count, err = p.Offset(-1).Limit(-1).Count()
	return
}

func (p promotionDiscountProductDo) ScanByPage(result interface{}, offset int, limit int) (count int64, err error) {
	count, err = p.Count()
	if err != nil {
		return
	}

	err = p.Offset(offset).Limit(limit).Scan(result)
	return
}

func (p promotionDiscountProductDo) Scan(result interface{}) (err error) {
	return p.DO.Scan(result)
}

func (p promotionDiscountProductDo) Delete(models ...*promotion.PromotionDiscountProduct) (result gen.ResultInfo, err error) {
	return p.DO.Delete(models)
}

func (p *promotionDiscountProductDo) withDO(do gen.Dao) *promotionDiscountProductDo {
	p.DO = *do.(*gen.DO)
	return p
}
