// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package query

import (
	"context"
	"database/sql"

	"gorm.io/gorm"
	"gorm.io/gorm/clause"
	"gorm.io/gorm/schema"

	"gorm.io/gen"
	"gorm.io/gen/field"

	"gorm.io/plugin/dbresolver"

	"backend-go/internal/model/promotion"
)

func newPromotionDiscountActivity(db *gorm.DB, opts ...gen.DOOption) promotionDiscountActivity {
	_promotionDiscountActivity := promotionDiscountActivity{}

	_promotionDiscountActivity.promotionDiscountActivityDo.UseDB(db, opts...)
	_promotionDiscountActivity.promotionDiscountActivityDo.UseModel(&promotion.PromotionDiscountActivity{})

	tableName := _promotionDiscountActivity.promotionDiscountActivityDo.TableName()
	_promotionDiscountActivity.ALL = field.NewAsterisk(tableName)
	_promotionDiscountActivity.ID = field.NewInt64(tableName, "id")
	_promotionDiscountActivity.Name = field.NewString(tableName, "name")
	_promotionDiscountActivity.Status = field.NewInt(tableName, "status")
	_promotionDiscountActivity.StartTime = field.NewTime(tableName, "start_time")
	_promotionDiscountActivity.EndTime = field.NewTime(tableName, "end_time")
	_promotionDiscountActivity.Remark = field.NewString(tableName, "remark")
	_promotionDiscountActivity.Creator = field.NewString(tableName, "creator")
	_promotionDiscountActivity.CreateTime = field.NewTime(tableName, "create_time")
	_promotionDiscountActivity.Updater = field.NewString(tableName, "updater")
	_promotionDiscountActivity.UpdateTime = field.NewTime(tableName, "update_time")
	_promotionDiscountActivity.Deleted = field.NewInt(tableName, "deleted")
	_promotionDiscountActivity.TenantID = field.NewInt64(tableName, "tenant_id")

	_promotionDiscountActivity.fillFieldMap()

	return _promotionDiscountActivity
}

type promotionDiscountActivity struct {
	promotionDiscountActivityDo promotionDiscountActivityDo

	ALL        field.Asterisk
	ID         field.Int64
	Name       field.String
	Status     field.Int
	StartTime  field.Time
	EndTime    field.Time
	Remark     field.String
	Creator    field.String
	CreateTime field.Time
	Updater    field.String
	UpdateTime field.Time
	Deleted    field.Int
	TenantID   field.Int64

	fieldMap map[string]field.Expr
}

func (p promotionDiscountActivity) Table(newTableName string) *promotionDiscountActivity {
	p.promotionDiscountActivityDo.UseTable(newTableName)
	return p.updateTableName(newTableName)
}

func (p promotionDiscountActivity) As(alias string) *promotionDiscountActivity {
	p.promotionDiscountActivityDo.DO = *(p.promotionDiscountActivityDo.As(alias).(*gen.DO))
	return p.updateTableName(alias)
}

func (p *promotionDiscountActivity) updateTableName(table string) *promotionDiscountActivity {
	p.ALL = field.NewAsterisk(table)
	p.ID = field.NewInt64(table, "id")
	p.Name = field.NewString(table, "name")
	p.Status = field.NewInt(table, "status")
	p.StartTime = field.NewTime(table, "start_time")
	p.EndTime = field.NewTime(table, "end_time")
	p.Remark = field.NewString(table, "remark")
	p.Creator = field.NewString(table, "creator")
	p.CreateTime = field.NewTime(table, "create_time")
	p.Updater = field.NewString(table, "updater")
	p.UpdateTime = field.NewTime(table, "update_time")
	p.Deleted = field.NewInt(table, "deleted")
	p.TenantID = field.NewInt64(table, "tenant_id")

	p.fillFieldMap()

	return p
}

func (p *promotionDiscountActivity) WithContext(ctx context.Context) IPromotionDiscountActivityDo {
	return p.promotionDiscountActivityDo.WithContext(ctx)
}

func (p promotionDiscountActivity) TableName() string {
	return p.promotionDiscountActivityDo.TableName()
}

func (p promotionDiscountActivity) Alias() string { return p.promotionDiscountActivityDo.Alias() }

func (p promotionDiscountActivity) Columns(cols ...field.Expr) gen.Columns {
	return p.promotionDiscountActivityDo.Columns(cols...)
}

func (p *promotionDiscountActivity) GetFieldByName(fieldName string) (field.OrderExpr, bool) {
	_f, ok := p.fieldMap[fieldName]
	if !ok || _f == nil {
		return nil, false
	}
	_oe, ok := _f.(field.OrderExpr)
	return _oe, ok
}

func (p *promotionDiscountActivity) fillFieldMap() {
	p.fieldMap = make(map[string]field.Expr, 12)
	p.fieldMap["id"] = p.ID
	p.fieldMap["name"] = p.Name
	p.fieldMap["status"] = p.Status
	p.fieldMap["start_time"] = p.StartTime
	p.fieldMap["end_time"] = p.EndTime
	p.fieldMap["remark"] = p.Remark
	p.fieldMap["creator"] = p.Creator
	p.fieldMap["create_time"] = p.CreateTime
	p.fieldMap["updater"] = p.Updater
	p.fieldMap["update_time"] = p.UpdateTime
	p.fieldMap["deleted"] = p.Deleted
	p.fieldMap["tenant_id"] = p.TenantID
}

func (p promotionDiscountActivity) clone(db *gorm.DB) promotionDiscountActivity {
	p.promotionDiscountActivityDo.ReplaceConnPool(db.Statement.ConnPool)
	return p
}

func (p promotionDiscountActivity) replaceDB(db *gorm.DB) promotionDiscountActivity {
	p.promotionDiscountActivityDo.ReplaceDB(db)
	return p
}

type promotionDiscountActivityDo struct{ gen.DO }

type IPromotionDiscountActivityDo interface {
	gen.SubQuery
	Debug() IPromotionDiscountActivityDo
	WithContext(ctx context.Context) IPromotionDiscountActivityDo
	WithResult(fc func(tx gen.Dao)) gen.ResultInfo
	ReplaceDB(db *gorm.DB)
	ReadDB() IPromotionDiscountActivityDo
	WriteDB() IPromotionDiscountActivityDo
	As(alias string) gen.Dao
	Session(config *gorm.Session) IPromotionDiscountActivityDo
	Columns(cols ...field.Expr) gen.Columns
	Clauses(conds ...clause.Expression) IPromotionDiscountActivityDo
	Not(conds ...gen.Condition) IPromotionDiscountActivityDo
	Or(conds ...gen.Condition) IPromotionDiscountActivityDo
	Select(conds ...field.Expr) IPromotionDiscountActivityDo
	Where(conds ...gen.Condition) IPromotionDiscountActivityDo
	Order(conds ...field.Expr) IPromotionDiscountActivityDo
	Distinct(cols ...field.Expr) IPromotionDiscountActivityDo
	Omit(cols ...field.Expr) IPromotionDiscountActivityDo
	Join(table schema.Tabler, on ...field.Expr) IPromotionDiscountActivityDo
	LeftJoin(table schema.Tabler, on ...field.Expr) IPromotionDiscountActivityDo
	RightJoin(table schema.Tabler, on ...field.Expr) IPromotionDiscountActivityDo
	Group(cols ...field.Expr) IPromotionDiscountActivityDo
	Having(conds ...gen.Condition) IPromotionDiscountActivityDo
	Limit(limit int) IPromotionDiscountActivityDo
	Offset(offset int) IPromotionDiscountActivityDo
	Count() (count int64, err error)
	Scopes(funcs ...func(gen.Dao) gen.Dao) IPromotionDiscountActivityDo
	Unscoped() IPromotionDiscountActivityDo
	Create(values ...*promotion.PromotionDiscountActivity) error
	CreateInBatches(values []*promotion.PromotionDiscountActivity, batchSize int) error
	Save(values ...*promotion.PromotionDiscountActivity) error
	First() (*promotion.PromotionDiscountActivity, error)
	Take() (*promotion.PromotionDiscountActivity, error)
	Last() (*promotion.PromotionDiscountActivity, error)
	Find() ([]*promotion.PromotionDiscountActivity, error)
	FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*promotion.PromotionDiscountActivity, err error)
	FindInBatches(result *[]*promotion.PromotionDiscountActivity, batchSize int, fc func(tx gen.Dao, batch int) error) error
	Pluck(column field.Expr, dest interface{}) error
	Delete(...*promotion.PromotionDiscountActivity) (info gen.ResultInfo, err error)
	Update(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	Updates(value interface{}) (info gen.ResultInfo, err error)
	UpdateColumn(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateColumnSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	UpdateColumns(value interface{}) (info gen.ResultInfo, err error)
	UpdateFrom(q gen.SubQuery) gen.Dao
	Attrs(attrs ...field.AssignExpr) IPromotionDiscountActivityDo
	Assign(attrs ...field.AssignExpr) IPromotionDiscountActivityDo
	Joins(fields ...field.RelationField) IPromotionDiscountActivityDo
	Preload(fields ...field.RelationField) IPromotionDiscountActivityDo
	FirstOrInit() (*promotion.PromotionDiscountActivity, error)
	FirstOrCreate() (*promotion.PromotionDiscountActivity, error)
	FindByPage(offset int, limit int) (result []*promotion.PromotionDiscountActivity, count int64, err error)
	ScanByPage(result interface{}, offset int, limit int) (count int64, err error)
	Rows() (*sql.Rows, error)
	Row() *sql.Row
	Scan(result interface{}) (err error)
	Returning(value interface{}, columns ...string) IPromotionDiscountActivityDo
	UnderlyingDB() *gorm.DB
	schema.Tabler
}

func (p promotionDiscountActivityDo) Debug() IPromotionDiscountActivityDo {
	return p.withDO(p.DO.Debug())
}

func (p promotionDiscountActivityDo) WithContext(ctx context.Context) IPromotionDiscountActivityDo {
	return p.withDO(p.DO.WithContext(ctx))
}

func (p promotionDiscountActivityDo) ReadDB() IPromotionDiscountActivityDo {
	return p.Clauses(dbresolver.Read)
}

func (p promotionDiscountActivityDo) WriteDB() IPromotionDiscountActivityDo {
	return p.Clauses(dbresolver.Write)
}

func (p promotionDiscountActivityDo) Session(config *gorm.Session) IPromotionDiscountActivityDo {
	return p.withDO(p.DO.Session(config))
}

func (p promotionDiscountActivityDo) Clauses(conds ...clause.Expression) IPromotionDiscountActivityDo {
	return p.withDO(p.DO.Clauses(conds...))
}

func (p promotionDiscountActivityDo) Returning(value interface{}, columns ...string) IPromotionDiscountActivityDo {
	return p.withDO(p.DO.Returning(value, columns...))
}

func (p promotionDiscountActivityDo) Not(conds ...gen.Condition) IPromotionDiscountActivityDo {
	return p.withDO(p.DO.Not(conds...))
}

func (p promotionDiscountActivityDo) Or(conds ...gen.Condition) IPromotionDiscountActivityDo {
	return p.withDO(p.DO.Or(conds...))
}

func (p promotionDiscountActivityDo) Select(conds ...field.Expr) IPromotionDiscountActivityDo {
	return p.withDO(p.DO.Select(conds...))
}

func (p promotionDiscountActivityDo) Where(conds ...gen.Condition) IPromotionDiscountActivityDo {
	return p.withDO(p.DO.Where(conds...))
}

func (p promotionDiscountActivityDo) Order(conds ...field.Expr) IPromotionDiscountActivityDo {
	return p.withDO(p.DO.Order(conds...))
}

func (p promotionDiscountActivityDo) Distinct(cols ...field.Expr) IPromotionDiscountActivityDo {
	return p.withDO(p.DO.Distinct(cols...))
}

func (p promotionDiscountActivityDo) Omit(cols ...field.Expr) IPromotionDiscountActivityDo {
	return p.withDO(p.DO.Omit(cols...))
}

func (p promotionDiscountActivityDo) Join(table schema.Tabler, on ...field.Expr) IPromotionDiscountActivityDo {
	return p.withDO(p.DO.Join(table, on...))
}

func (p promotionDiscountActivityDo) LeftJoin(table schema.Tabler, on ...field.Expr) IPromotionDiscountActivityDo {
	return p.withDO(p.DO.LeftJoin(table, on...))
}

func (p promotionDiscountActivityDo) RightJoin(table schema.Tabler, on ...field.Expr) IPromotionDiscountActivityDo {
	return p.withDO(p.DO.RightJoin(table, on...))
}

func (p promotionDiscountActivityDo) Group(cols ...field.Expr) IPromotionDiscountActivityDo {
	return p.withDO(p.DO.Group(cols...))
}

func (p promotionDiscountActivityDo) Having(conds ...gen.Condition) IPromotionDiscountActivityDo {
	return p.withDO(p.DO.Having(conds...))
}

func (p promotionDiscountActivityDo) Limit(limit int) IPromotionDiscountActivityDo {
	return p.withDO(p.DO.Limit(limit))
}

func (p promotionDiscountActivityDo) Offset(offset int) IPromotionDiscountActivityDo {
	return p.withDO(p.DO.Offset(offset))
}

func (p promotionDiscountActivityDo) Scopes(funcs ...func(gen.Dao) gen.Dao) IPromotionDiscountActivityDo {
	return p.withDO(p.DO.Scopes(funcs...))
}

func (p promotionDiscountActivityDo) Unscoped() IPromotionDiscountActivityDo {
	return p.withDO(p.DO.Unscoped())
}

func (p promotionDiscountActivityDo) Create(values ...*promotion.PromotionDiscountActivity) error {
	if len(values) == 0 {
		return nil
	}
	return p.DO.Create(values)
}

func (p promotionDiscountActivityDo) CreateInBatches(values []*promotion.PromotionDiscountActivity, batchSize int) error {
	return p.DO.CreateInBatches(values, batchSize)
}

// Save : !!! underlying implementation is different with GORM
// The method is equivalent to executing the statement: db.Clauses(clause.OnConflict{UpdateAll: true}).Create(values)
func (p promotionDiscountActivityDo) Save(values ...*promotion.PromotionDiscountActivity) error {
	if len(values) == 0 {
		return nil
	}
	return p.DO.Save(values)
}

func (p promotionDiscountActivityDo) First() (*promotion.PromotionDiscountActivity, error) {
	if result, err := p.DO.First(); err != nil {
		return nil, err
	} else {
		return result.(*promotion.PromotionDiscountActivity), nil
	}
}

func (p promotionDiscountActivityDo) Take() (*promotion.PromotionDiscountActivity, error) {
	if result, err := p.DO.Take(); err != nil {
		return nil, err
	} else {
		return result.(*promotion.PromotionDiscountActivity), nil
	}
}

func (p promotionDiscountActivityDo) Last() (*promotion.PromotionDiscountActivity, error) {
	if result, err := p.DO.Last(); err != nil {
		return nil, err
	} else {
		return result.(*promotion.PromotionDiscountActivity), nil
	}
}

func (p promotionDiscountActivityDo) Find() ([]*promotion.PromotionDiscountActivity, error) {
	result, err := p.DO.Find()
	return result.([]*promotion.PromotionDiscountActivity), err
}

func (p promotionDiscountActivityDo) FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*promotion.PromotionDiscountActivity, err error) {
	buf := make([]*promotion.PromotionDiscountActivity, 0, batchSize)
	err = p.DO.FindInBatches(&buf, batchSize, func(tx gen.Dao, batch int) error {
		defer func() { results = append(results, buf...) }()
		return fc(tx, batch)
	})
	return results, err
}

func (p promotionDiscountActivityDo) FindInBatches(result *[]*promotion.PromotionDiscountActivity, batchSize int, fc func(tx gen.Dao, batch int) error) error {
	return p.DO.FindInBatches(result, batchSize, fc)
}

func (p promotionDiscountActivityDo) Attrs(attrs ...field.AssignExpr) IPromotionDiscountActivityDo {
	return p.withDO(p.DO.Attrs(attrs...))
}

func (p promotionDiscountActivityDo) Assign(attrs ...field.AssignExpr) IPromotionDiscountActivityDo {
	return p.withDO(p.DO.Assign(attrs...))
}

func (p promotionDiscountActivityDo) Joins(fields ...field.RelationField) IPromotionDiscountActivityDo {
	for _, _f := range fields {
		p = *p.withDO(p.DO.Joins(_f))
	}
	return &p
}

func (p promotionDiscountActivityDo) Preload(fields ...field.RelationField) IPromotionDiscountActivityDo {
	for _, _f := range fields {
		p = *p.withDO(p.DO.Preload(_f))
	}
	return &p
}

func (p promotionDiscountActivityDo) FirstOrInit() (*promotion.PromotionDiscountActivity, error) {
	if result, err := p.DO.FirstOrInit(); err != nil {
		return nil, err
	} else {
		return result.(*promotion.PromotionDiscountActivity), nil
	}
}

func (p promotionDiscountActivityDo) FirstOrCreate() (*promotion.PromotionDiscountActivity, error) {
	if result, err := p.DO.FirstOrCreate(); err != nil {
		return nil, err
	} else {
		return result.(*promotion.PromotionDiscountActivity), nil
	}
}

func (p promotionDiscountActivityDo) FindByPage(offset int, limit int) (result []*promotion.PromotionDiscountActivity, count int64, err error) {
	result, err = p.Offset(offset).Limit(limit).Find()
	if err != nil {
		return
	}

	if size := len(result); 0 < limit && 0 < size && size < limit {
		count = int64(size + offset)
		return
	}

	count, err = p.Offset(-1).Limit(-1).Count()
	return
}

func (p promotionDiscountActivityDo) ScanByPage(result interface{}, offset int, limit int) (count int64, err error) {
	count, err = p.Count()
	if err != nil {
		return
	}

	err = p.Offset(offset).Limit(limit).Scan(result)
	return
}

func (p promotionDiscountActivityDo) Scan(result interface{}) (err error) {
	return p.DO.Scan(result)
}

func (p promotionDiscountActivityDo) Delete(models ...*promotion.PromotionDiscountActivity) (result gen.ResultInfo, err error) {
	return p.DO.Delete(models)
}

func (p *promotionDiscountActivityDo) withDO(do gen.Dao) *promotionDiscountActivityDo {
	p.DO = *do.(*gen.DO)
	return p
}
