// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package query

import (
	"context"
	"database/sql"

	"gorm.io/gorm"
	"gorm.io/gorm/clause"
	"gorm.io/gorm/schema"

	"gorm.io/gen"
	"gorm.io/gen/field"

	"gorm.io/plugin/dbresolver"

	"backend-go/internal/model/promotion"
)

func newPromotionArticleCategory(db *gorm.DB, opts ...gen.DOOption) promotionArticleCategory {
	_promotionArticleCategory := promotionArticleCategory{}

	_promotionArticleCategory.promotionArticleCategoryDo.UseDB(db, opts...)
	_promotionArticleCategory.promotionArticleCategoryDo.UseModel(&promotion.PromotionArticleCategory{})

	tableName := _promotionArticleCategory.promotionArticleCategoryDo.TableName()
	_promotionArticleCategory.ALL = field.NewAsterisk(tableName)
	_promotionArticleCategory.ID = field.NewInt64(tableName, "id")
	_promotionArticleCategory.Name = field.NewString(tableName, "name")
	_promotionArticleCategory.PicURL = field.NewString(tableName, "pic_url")
	_promotionArticleCategory.Sort = field.NewInt(tableName, "sort")
	_promotionArticleCategory.Status = field.NewInt(tableName, "status")
	_promotionArticleCategory.Creator = field.NewString(tableName, "creator")
	_promotionArticleCategory.CreateTime = field.NewTime(tableName, "create_time")
	_promotionArticleCategory.Updater = field.NewString(tableName, "updater")
	_promotionArticleCategory.UpdateTime = field.NewTime(tableName, "update_time")
	_promotionArticleCategory.Deleted = field.NewInt(tableName, "deleted")
	_promotionArticleCategory.TenantID = field.NewInt64(tableName, "tenant_id")

	_promotionArticleCategory.fillFieldMap()

	return _promotionArticleCategory
}

type promotionArticleCategory struct {
	promotionArticleCategoryDo promotionArticleCategoryDo

	ALL        field.Asterisk
	ID         field.Int64
	Name       field.String // 分类名称
	PicURL     field.String // 图标地址
	Sort       field.Int    // 排序
	Status     field.Int    // 状态
	Creator    field.String
	CreateTime field.Time
	Updater    field.String
	UpdateTime field.Time
	Deleted    field.Int
	TenantID   field.Int64

	fieldMap map[string]field.Expr
}

func (p promotionArticleCategory) Table(newTableName string) *promotionArticleCategory {
	p.promotionArticleCategoryDo.UseTable(newTableName)
	return p.updateTableName(newTableName)
}

func (p promotionArticleCategory) As(alias string) *promotionArticleCategory {
	p.promotionArticleCategoryDo.DO = *(p.promotionArticleCategoryDo.As(alias).(*gen.DO))
	return p.updateTableName(alias)
}

func (p *promotionArticleCategory) updateTableName(table string) *promotionArticleCategory {
	p.ALL = field.NewAsterisk(table)
	p.ID = field.NewInt64(table, "id")
	p.Name = field.NewString(table, "name")
	p.PicURL = field.NewString(table, "pic_url")
	p.Sort = field.NewInt(table, "sort")
	p.Status = field.NewInt(table, "status")
	p.Creator = field.NewString(table, "creator")
	p.CreateTime = field.NewTime(table, "create_time")
	p.Updater = field.NewString(table, "updater")
	p.UpdateTime = field.NewTime(table, "update_time")
	p.Deleted = field.NewInt(table, "deleted")
	p.TenantID = field.NewInt64(table, "tenant_id")

	p.fillFieldMap()

	return p
}

func (p *promotionArticleCategory) WithContext(ctx context.Context) IPromotionArticleCategoryDo {
	return p.promotionArticleCategoryDo.WithContext(ctx)
}

func (p promotionArticleCategory) TableName() string { return p.promotionArticleCategoryDo.TableName() }

func (p promotionArticleCategory) Alias() string { return p.promotionArticleCategoryDo.Alias() }

func (p promotionArticleCategory) Columns(cols ...field.Expr) gen.Columns {
	return p.promotionArticleCategoryDo.Columns(cols...)
}

func (p *promotionArticleCategory) GetFieldByName(fieldName string) (field.OrderExpr, bool) {
	_f, ok := p.fieldMap[fieldName]
	if !ok || _f == nil {
		return nil, false
	}
	_oe, ok := _f.(field.OrderExpr)
	return _oe, ok
}

func (p *promotionArticleCategory) fillFieldMap() {
	p.fieldMap = make(map[string]field.Expr, 11)
	p.fieldMap["id"] = p.ID
	p.fieldMap["name"] = p.Name
	p.fieldMap["pic_url"] = p.PicURL
	p.fieldMap["sort"] = p.Sort
	p.fieldMap["status"] = p.Status
	p.fieldMap["creator"] = p.Creator
	p.fieldMap["create_time"] = p.CreateTime
	p.fieldMap["updater"] = p.Updater
	p.fieldMap["update_time"] = p.UpdateTime
	p.fieldMap["deleted"] = p.Deleted
	p.fieldMap["tenant_id"] = p.TenantID
}

func (p promotionArticleCategory) clone(db *gorm.DB) promotionArticleCategory {
	p.promotionArticleCategoryDo.ReplaceConnPool(db.Statement.ConnPool)
	return p
}

func (p promotionArticleCategory) replaceDB(db *gorm.DB) promotionArticleCategory {
	p.promotionArticleCategoryDo.ReplaceDB(db)
	return p
}

type promotionArticleCategoryDo struct{ gen.DO }

type IPromotionArticleCategoryDo interface {
	gen.SubQuery
	Debug() IPromotionArticleCategoryDo
	WithContext(ctx context.Context) IPromotionArticleCategoryDo
	WithResult(fc func(tx gen.Dao)) gen.ResultInfo
	ReplaceDB(db *gorm.DB)
	ReadDB() IPromotionArticleCategoryDo
	WriteDB() IPromotionArticleCategoryDo
	As(alias string) gen.Dao
	Session(config *gorm.Session) IPromotionArticleCategoryDo
	Columns(cols ...field.Expr) gen.Columns
	Clauses(conds ...clause.Expression) IPromotionArticleCategoryDo
	Not(conds ...gen.Condition) IPromotionArticleCategoryDo
	Or(conds ...gen.Condition) IPromotionArticleCategoryDo
	Select(conds ...field.Expr) IPromotionArticleCategoryDo
	Where(conds ...gen.Condition) IPromotionArticleCategoryDo
	Order(conds ...field.Expr) IPromotionArticleCategoryDo
	Distinct(cols ...field.Expr) IPromotionArticleCategoryDo
	Omit(cols ...field.Expr) IPromotionArticleCategoryDo
	Join(table schema.Tabler, on ...field.Expr) IPromotionArticleCategoryDo
	LeftJoin(table schema.Tabler, on ...field.Expr) IPromotionArticleCategoryDo
	RightJoin(table schema.Tabler, on ...field.Expr) IPromotionArticleCategoryDo
	Group(cols ...field.Expr) IPromotionArticleCategoryDo
	Having(conds ...gen.Condition) IPromotionArticleCategoryDo
	Limit(limit int) IPromotionArticleCategoryDo
	Offset(offset int) IPromotionArticleCategoryDo
	Count() (count int64, err error)
	Scopes(funcs ...func(gen.Dao) gen.Dao) IPromotionArticleCategoryDo
	Unscoped() IPromotionArticleCategoryDo
	Create(values ...*promotion.PromotionArticleCategory) error
	CreateInBatches(values []*promotion.PromotionArticleCategory, batchSize int) error
	Save(values ...*promotion.PromotionArticleCategory) error
	First() (*promotion.PromotionArticleCategory, error)
	Take() (*promotion.PromotionArticleCategory, error)
	Last() (*promotion.PromotionArticleCategory, error)
	Find() ([]*promotion.PromotionArticleCategory, error)
	FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*promotion.PromotionArticleCategory, err error)
	FindInBatches(result *[]*promotion.PromotionArticleCategory, batchSize int, fc func(tx gen.Dao, batch int) error) error
	Pluck(column field.Expr, dest interface{}) error
	Delete(...*promotion.PromotionArticleCategory) (info gen.ResultInfo, err error)
	Update(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	Updates(value interface{}) (info gen.ResultInfo, err error)
	UpdateColumn(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateColumnSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	UpdateColumns(value interface{}) (info gen.ResultInfo, err error)
	UpdateFrom(q gen.SubQuery) gen.Dao
	Attrs(attrs ...field.AssignExpr) IPromotionArticleCategoryDo
	Assign(attrs ...field.AssignExpr) IPromotionArticleCategoryDo
	Joins(fields ...field.RelationField) IPromotionArticleCategoryDo
	Preload(fields ...field.RelationField) IPromotionArticleCategoryDo
	FirstOrInit() (*promotion.PromotionArticleCategory, error)
	FirstOrCreate() (*promotion.PromotionArticleCategory, error)
	FindByPage(offset int, limit int) (result []*promotion.PromotionArticleCategory, count int64, err error)
	ScanByPage(result interface{}, offset int, limit int) (count int64, err error)
	Rows() (*sql.Rows, error)
	Row() *sql.Row
	Scan(result interface{}) (err error)
	Returning(value interface{}, columns ...string) IPromotionArticleCategoryDo
	UnderlyingDB() *gorm.DB
	schema.Tabler
}

func (p promotionArticleCategoryDo) Debug() IPromotionArticleCategoryDo {
	return p.withDO(p.DO.Debug())
}

func (p promotionArticleCategoryDo) WithContext(ctx context.Context) IPromotionArticleCategoryDo {
	return p.withDO(p.DO.WithContext(ctx))
}

func (p promotionArticleCategoryDo) ReadDB() IPromotionArticleCategoryDo {
	return p.Clauses(dbresolver.Read)
}

func (p promotionArticleCategoryDo) WriteDB() IPromotionArticleCategoryDo {
	return p.Clauses(dbresolver.Write)
}

func (p promotionArticleCategoryDo) Session(config *gorm.Session) IPromotionArticleCategoryDo {
	return p.withDO(p.DO.Session(config))
}

func (p promotionArticleCategoryDo) Clauses(conds ...clause.Expression) IPromotionArticleCategoryDo {
	return p.withDO(p.DO.Clauses(conds...))
}

func (p promotionArticleCategoryDo) Returning(value interface{}, columns ...string) IPromotionArticleCategoryDo {
	return p.withDO(p.DO.Returning(value, columns...))
}

func (p promotionArticleCategoryDo) Not(conds ...gen.Condition) IPromotionArticleCategoryDo {
	return p.withDO(p.DO.Not(conds...))
}

func (p promotionArticleCategoryDo) Or(conds ...gen.Condition) IPromotionArticleCategoryDo {
	return p.withDO(p.DO.Or(conds...))
}

func (p promotionArticleCategoryDo) Select(conds ...field.Expr) IPromotionArticleCategoryDo {
	return p.withDO(p.DO.Select(conds...))
}

func (p promotionArticleCategoryDo) Where(conds ...gen.Condition) IPromotionArticleCategoryDo {
	return p.withDO(p.DO.Where(conds...))
}

func (p promotionArticleCategoryDo) Order(conds ...field.Expr) IPromotionArticleCategoryDo {
	return p.withDO(p.DO.Order(conds...))
}

func (p promotionArticleCategoryDo) Distinct(cols ...field.Expr) IPromotionArticleCategoryDo {
	return p.withDO(p.DO.Distinct(cols...))
}

func (p promotionArticleCategoryDo) Omit(cols ...field.Expr) IPromotionArticleCategoryDo {
	return p.withDO(p.DO.Omit(cols...))
}

func (p promotionArticleCategoryDo) Join(table schema.Tabler, on ...field.Expr) IPromotionArticleCategoryDo {
	return p.withDO(p.DO.Join(table, on...))
}

func (p promotionArticleCategoryDo) LeftJoin(table schema.Tabler, on ...field.Expr) IPromotionArticleCategoryDo {
	return p.withDO(p.DO.LeftJoin(table, on...))
}

func (p promotionArticleCategoryDo) RightJoin(table schema.Tabler, on ...field.Expr) IPromotionArticleCategoryDo {
	return p.withDO(p.DO.RightJoin(table, on...))
}

func (p promotionArticleCategoryDo) Group(cols ...field.Expr) IPromotionArticleCategoryDo {
	return p.withDO(p.DO.Group(cols...))
}

func (p promotionArticleCategoryDo) Having(conds ...gen.Condition) IPromotionArticleCategoryDo {
	return p.withDO(p.DO.Having(conds...))
}

func (p promotionArticleCategoryDo) Limit(limit int) IPromotionArticleCategoryDo {
	return p.withDO(p.DO.Limit(limit))
}

func (p promotionArticleCategoryDo) Offset(offset int) IPromotionArticleCategoryDo {
	return p.withDO(p.DO.Offset(offset))
}

func (p promotionArticleCategoryDo) Scopes(funcs ...func(gen.Dao) gen.Dao) IPromotionArticleCategoryDo {
	return p.withDO(p.DO.Scopes(funcs...))
}

func (p promotionArticleCategoryDo) Unscoped() IPromotionArticleCategoryDo {
	return p.withDO(p.DO.Unscoped())
}

func (p promotionArticleCategoryDo) Create(values ...*promotion.PromotionArticleCategory) error {
	if len(values) == 0 {
		return nil
	}
	return p.DO.Create(values)
}

func (p promotionArticleCategoryDo) CreateInBatches(values []*promotion.PromotionArticleCategory, batchSize int) error {
	return p.DO.CreateInBatches(values, batchSize)
}

// Save : !!! underlying implementation is different with GORM
// The method is equivalent to executing the statement: db.Clauses(clause.OnConflict{UpdateAll: true}).Create(values)
func (p promotionArticleCategoryDo) Save(values ...*promotion.PromotionArticleCategory) error {
	if len(values) == 0 {
		return nil
	}
	return p.DO.Save(values)
}

func (p promotionArticleCategoryDo) First() (*promotion.PromotionArticleCategory, error) {
	if result, err := p.DO.First(); err != nil {
		return nil, err
	} else {
		return result.(*promotion.PromotionArticleCategory), nil
	}
}

func (p promotionArticleCategoryDo) Take() (*promotion.PromotionArticleCategory, error) {
	if result, err := p.DO.Take(); err != nil {
		return nil, err
	} else {
		return result.(*promotion.PromotionArticleCategory), nil
	}
}

func (p promotionArticleCategoryDo) Last() (*promotion.PromotionArticleCategory, error) {
	if result, err := p.DO.Last(); err != nil {
		return nil, err
	} else {
		return result.(*promotion.PromotionArticleCategory), nil
	}
}

func (p promotionArticleCategoryDo) Find() ([]*promotion.PromotionArticleCategory, error) {
	result, err := p.DO.Find()
	return result.([]*promotion.PromotionArticleCategory), err
}

func (p promotionArticleCategoryDo) FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*promotion.PromotionArticleCategory, err error) {
	buf := make([]*promotion.PromotionArticleCategory, 0, batchSize)
	err = p.DO.FindInBatches(&buf, batchSize, func(tx gen.Dao, batch int) error {
		defer func() { results = append(results, buf...) }()
		return fc(tx, batch)
	})
	return results, err
}

func (p promotionArticleCategoryDo) FindInBatches(result *[]*promotion.PromotionArticleCategory, batchSize int, fc func(tx gen.Dao, batch int) error) error {
	return p.DO.FindInBatches(result, batchSize, fc)
}

func (p promotionArticleCategoryDo) Attrs(attrs ...field.AssignExpr) IPromotionArticleCategoryDo {
	return p.withDO(p.DO.Attrs(attrs...))
}

func (p promotionArticleCategoryDo) Assign(attrs ...field.AssignExpr) IPromotionArticleCategoryDo {
	return p.withDO(p.DO.Assign(attrs...))
}

func (p promotionArticleCategoryDo) Joins(fields ...field.RelationField) IPromotionArticleCategoryDo {
	for _, _f := range fields {
		p = *p.withDO(p.DO.Joins(_f))
	}
	return &p
}

func (p promotionArticleCategoryDo) Preload(fields ...field.RelationField) IPromotionArticleCategoryDo {
	for _, _f := range fields {
		p = *p.withDO(p.DO.Preload(_f))
	}
	return &p
}

func (p promotionArticleCategoryDo) FirstOrInit() (*promotion.PromotionArticleCategory, error) {
	if result, err := p.DO.FirstOrInit(); err != nil {
		return nil, err
	} else {
		return result.(*promotion.PromotionArticleCategory), nil
	}
}

func (p promotionArticleCategoryDo) FirstOrCreate() (*promotion.PromotionArticleCategory, error) {
	if result, err := p.DO.FirstOrCreate(); err != nil {
		return nil, err
	} else {
		return result.(*promotion.PromotionArticleCategory), nil
	}
}

func (p promotionArticleCategoryDo) FindByPage(offset int, limit int) (result []*promotion.PromotionArticleCategory, count int64, err error) {
	result, err = p.Offset(offset).Limit(limit).Find()
	if err != nil {
		return
	}

	if size := len(result); 0 < limit && 0 < size && size < limit {
		count = int64(size + offset)
		return
	}

	count, err = p.Offset(-1).Limit(-1).Count()
	return
}

func (p promotionArticleCategoryDo) ScanByPage(result interface{}, offset int, limit int) (count int64, err error) {
	count, err = p.Count()
	if err != nil {
		return
	}

	err = p.Offset(offset).Limit(limit).Scan(result)
	return
}

func (p promotionArticleCategoryDo) Scan(result interface{}) (err error) {
	return p.DO.Scan(result)
}

func (p promotionArticleCategoryDo) Delete(models ...*promotion.PromotionArticleCategory) (result gen.ResultInfo, err error) {
	return p.DO.Delete(models)
}

func (p *promotionArticleCategoryDo) withDO(do gen.Dao) *promotionArticleCategoryDo {
	p.DO = *do.(*gen.DO)
	return p
}
