// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package query

import (
	"context"
	"database/sql"

	"gorm.io/gorm"
	"gorm.io/gorm/clause"
	"gorm.io/gorm/schema"

	"gorm.io/gen"
	"gorm.io/gen/field"

	"gorm.io/plugin/dbresolver"

	"backend-go/internal/model/promotion"
)

func newPromotionDiyTemplate(db *gorm.DB, opts ...gen.DOOption) promotionDiyTemplate {
	_promotionDiyTemplate := promotionDiyTemplate{}

	_promotionDiyTemplate.promotionDiyTemplateDo.UseDB(db, opts...)
	_promotionDiyTemplate.promotionDiyTemplateDo.UseModel(&promotion.PromotionDiyTemplate{})

	tableName := _promotionDiyTemplate.promotionDiyTemplateDo.TableName()
	_promotionDiyTemplate.ALL = field.NewAsterisk(tableName)
	_promotionDiyTemplate.ID = field.NewInt64(tableName, "id")
	_promotionDiyTemplate.Name = field.NewString(tableName, "name")
	_promotionDiyTemplate.CoverImage = field.NewString(tableName, "cover_image")
	_promotionDiyTemplate.PreviewImage = field.NewString(tableName, "preview_image")
	_promotionDiyTemplate.Status = field.NewInt(tableName, "status")
	_promotionDiyTemplate.Property = field.NewString(tableName, "property")
	_promotionDiyTemplate.Sort = field.NewInt(tableName, "sort")
	_promotionDiyTemplate.Remark = field.NewString(tableName, "remark")
	_promotionDiyTemplate.Creator = field.NewString(tableName, "creator")
	_promotionDiyTemplate.CreateTime = field.NewTime(tableName, "create_time")
	_promotionDiyTemplate.Updater = field.NewString(tableName, "updater")
	_promotionDiyTemplate.UpdateTime = field.NewTime(tableName, "update_time")
	_promotionDiyTemplate.Deleted = field.NewInt(tableName, "deleted")
	_promotionDiyTemplate.TenantID = field.NewInt64(tableName, "tenant_id")

	_promotionDiyTemplate.fillFieldMap()

	return _promotionDiyTemplate
}

type promotionDiyTemplate struct {
	promotionDiyTemplateDo promotionDiyTemplateDo

	ALL          field.Asterisk
	ID           field.Int64
	Name         field.String // 模板名称
	CoverImage   field.String // 封面图片
	PreviewImage field.String // 预览图片
	Status       field.Int    // 状态
	Property     field.String // 模板属性
	Sort         field.Int    // 排序
	Remark       field.String // 备注
	Creator      field.String
	CreateTime   field.Time
	Updater      field.String
	UpdateTime   field.Time
	Deleted      field.Int
	TenantID     field.Int64

	fieldMap map[string]field.Expr
}

func (p promotionDiyTemplate) Table(newTableName string) *promotionDiyTemplate {
	p.promotionDiyTemplateDo.UseTable(newTableName)
	return p.updateTableName(newTableName)
}

func (p promotionDiyTemplate) As(alias string) *promotionDiyTemplate {
	p.promotionDiyTemplateDo.DO = *(p.promotionDiyTemplateDo.As(alias).(*gen.DO))
	return p.updateTableName(alias)
}

func (p *promotionDiyTemplate) updateTableName(table string) *promotionDiyTemplate {
	p.ALL = field.NewAsterisk(table)
	p.ID = field.NewInt64(table, "id")
	p.Name = field.NewString(table, "name")
	p.CoverImage = field.NewString(table, "cover_image")
	p.PreviewImage = field.NewString(table, "preview_image")
	p.Status = field.NewInt(table, "status")
	p.Property = field.NewString(table, "property")
	p.Sort = field.NewInt(table, "sort")
	p.Remark = field.NewString(table, "remark")
	p.Creator = field.NewString(table, "creator")
	p.CreateTime = field.NewTime(table, "create_time")
	p.Updater = field.NewString(table, "updater")
	p.UpdateTime = field.NewTime(table, "update_time")
	p.Deleted = field.NewInt(table, "deleted")
	p.TenantID = field.NewInt64(table, "tenant_id")

	p.fillFieldMap()

	return p
}

func (p *promotionDiyTemplate) WithContext(ctx context.Context) IPromotionDiyTemplateDo {
	return p.promotionDiyTemplateDo.WithContext(ctx)
}

func (p promotionDiyTemplate) TableName() string { return p.promotionDiyTemplateDo.TableName() }

func (p promotionDiyTemplate) Alias() string { return p.promotionDiyTemplateDo.Alias() }

func (p promotionDiyTemplate) Columns(cols ...field.Expr) gen.Columns {
	return p.promotionDiyTemplateDo.Columns(cols...)
}

func (p *promotionDiyTemplate) GetFieldByName(fieldName string) (field.OrderExpr, bool) {
	_f, ok := p.fieldMap[fieldName]
	if !ok || _f == nil {
		return nil, false
	}
	_oe, ok := _f.(field.OrderExpr)
	return _oe, ok
}

func (p *promotionDiyTemplate) fillFieldMap() {
	p.fieldMap = make(map[string]field.Expr, 14)
	p.fieldMap["id"] = p.ID
	p.fieldMap["name"] = p.Name
	p.fieldMap["cover_image"] = p.CoverImage
	p.fieldMap["preview_image"] = p.PreviewImage
	p.fieldMap["status"] = p.Status
	p.fieldMap["property"] = p.Property
	p.fieldMap["sort"] = p.Sort
	p.fieldMap["remark"] = p.Remark
	p.fieldMap["creator"] = p.Creator
	p.fieldMap["create_time"] = p.CreateTime
	p.fieldMap["updater"] = p.Updater
	p.fieldMap["update_time"] = p.UpdateTime
	p.fieldMap["deleted"] = p.Deleted
	p.fieldMap["tenant_id"] = p.TenantID
}

func (p promotionDiyTemplate) clone(db *gorm.DB) promotionDiyTemplate {
	p.promotionDiyTemplateDo.ReplaceConnPool(db.Statement.ConnPool)
	return p
}

func (p promotionDiyTemplate) replaceDB(db *gorm.DB) promotionDiyTemplate {
	p.promotionDiyTemplateDo.ReplaceDB(db)
	return p
}

type promotionDiyTemplateDo struct{ gen.DO }

type IPromotionDiyTemplateDo interface {
	gen.SubQuery
	Debug() IPromotionDiyTemplateDo
	WithContext(ctx context.Context) IPromotionDiyTemplateDo
	WithResult(fc func(tx gen.Dao)) gen.ResultInfo
	ReplaceDB(db *gorm.DB)
	ReadDB() IPromotionDiyTemplateDo
	WriteDB() IPromotionDiyTemplateDo
	As(alias string) gen.Dao
	Session(config *gorm.Session) IPromotionDiyTemplateDo
	Columns(cols ...field.Expr) gen.Columns
	Clauses(conds ...clause.Expression) IPromotionDiyTemplateDo
	Not(conds ...gen.Condition) IPromotionDiyTemplateDo
	Or(conds ...gen.Condition) IPromotionDiyTemplateDo
	Select(conds ...field.Expr) IPromotionDiyTemplateDo
	Where(conds ...gen.Condition) IPromotionDiyTemplateDo
	Order(conds ...field.Expr) IPromotionDiyTemplateDo
	Distinct(cols ...field.Expr) IPromotionDiyTemplateDo
	Omit(cols ...field.Expr) IPromotionDiyTemplateDo
	Join(table schema.Tabler, on ...field.Expr) IPromotionDiyTemplateDo
	LeftJoin(table schema.Tabler, on ...field.Expr) IPromotionDiyTemplateDo
	RightJoin(table schema.Tabler, on ...field.Expr) IPromotionDiyTemplateDo
	Group(cols ...field.Expr) IPromotionDiyTemplateDo
	Having(conds ...gen.Condition) IPromotionDiyTemplateDo
	Limit(limit int) IPromotionDiyTemplateDo
	Offset(offset int) IPromotionDiyTemplateDo
	Count() (count int64, err error)
	Scopes(funcs ...func(gen.Dao) gen.Dao) IPromotionDiyTemplateDo
	Unscoped() IPromotionDiyTemplateDo
	Create(values ...*promotion.PromotionDiyTemplate) error
	CreateInBatches(values []*promotion.PromotionDiyTemplate, batchSize int) error
	Save(values ...*promotion.PromotionDiyTemplate) error
	First() (*promotion.PromotionDiyTemplate, error)
	Take() (*promotion.PromotionDiyTemplate, error)
	Last() (*promotion.PromotionDiyTemplate, error)
	Find() ([]*promotion.PromotionDiyTemplate, error)
	FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*promotion.PromotionDiyTemplate, err error)
	FindInBatches(result *[]*promotion.PromotionDiyTemplate, batchSize int, fc func(tx gen.Dao, batch int) error) error
	Pluck(column field.Expr, dest interface{}) error
	Delete(...*promotion.PromotionDiyTemplate) (info gen.ResultInfo, err error)
	Update(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	Updates(value interface{}) (info gen.ResultInfo, err error)
	UpdateColumn(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateColumnSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	UpdateColumns(value interface{}) (info gen.ResultInfo, err error)
	UpdateFrom(q gen.SubQuery) gen.Dao
	Attrs(attrs ...field.AssignExpr) IPromotionDiyTemplateDo
	Assign(attrs ...field.AssignExpr) IPromotionDiyTemplateDo
	Joins(fields ...field.RelationField) IPromotionDiyTemplateDo
	Preload(fields ...field.RelationField) IPromotionDiyTemplateDo
	FirstOrInit() (*promotion.PromotionDiyTemplate, error)
	FirstOrCreate() (*promotion.PromotionDiyTemplate, error)
	FindByPage(offset int, limit int) (result []*promotion.PromotionDiyTemplate, count int64, err error)
	ScanByPage(result interface{}, offset int, limit int) (count int64, err error)
	Rows() (*sql.Rows, error)
	Row() *sql.Row
	Scan(result interface{}) (err error)
	Returning(value interface{}, columns ...string) IPromotionDiyTemplateDo
	UnderlyingDB() *gorm.DB
	schema.Tabler
}

func (p promotionDiyTemplateDo) Debug() IPromotionDiyTemplateDo {
	return p.withDO(p.DO.Debug())
}

func (p promotionDiyTemplateDo) WithContext(ctx context.Context) IPromotionDiyTemplateDo {
	return p.withDO(p.DO.WithContext(ctx))
}

func (p promotionDiyTemplateDo) ReadDB() IPromotionDiyTemplateDo {
	return p.Clauses(dbresolver.Read)
}

func (p promotionDiyTemplateDo) WriteDB() IPromotionDiyTemplateDo {
	return p.Clauses(dbresolver.Write)
}

func (p promotionDiyTemplateDo) Session(config *gorm.Session) IPromotionDiyTemplateDo {
	return p.withDO(p.DO.Session(config))
}

func (p promotionDiyTemplateDo) Clauses(conds ...clause.Expression) IPromotionDiyTemplateDo {
	return p.withDO(p.DO.Clauses(conds...))
}

func (p promotionDiyTemplateDo) Returning(value interface{}, columns ...string) IPromotionDiyTemplateDo {
	return p.withDO(p.DO.Returning(value, columns...))
}

func (p promotionDiyTemplateDo) Not(conds ...gen.Condition) IPromotionDiyTemplateDo {
	return p.withDO(p.DO.Not(conds...))
}

func (p promotionDiyTemplateDo) Or(conds ...gen.Condition) IPromotionDiyTemplateDo {
	return p.withDO(p.DO.Or(conds...))
}

func (p promotionDiyTemplateDo) Select(conds ...field.Expr) IPromotionDiyTemplateDo {
	return p.withDO(p.DO.Select(conds...))
}

func (p promotionDiyTemplateDo) Where(conds ...gen.Condition) IPromotionDiyTemplateDo {
	return p.withDO(p.DO.Where(conds...))
}

func (p promotionDiyTemplateDo) Order(conds ...field.Expr) IPromotionDiyTemplateDo {
	return p.withDO(p.DO.Order(conds...))
}

func (p promotionDiyTemplateDo) Distinct(cols ...field.Expr) IPromotionDiyTemplateDo {
	return p.withDO(p.DO.Distinct(cols...))
}

func (p promotionDiyTemplateDo) Omit(cols ...field.Expr) IPromotionDiyTemplateDo {
	return p.withDO(p.DO.Omit(cols...))
}

func (p promotionDiyTemplateDo) Join(table schema.Tabler, on ...field.Expr) IPromotionDiyTemplateDo {
	return p.withDO(p.DO.Join(table, on...))
}

func (p promotionDiyTemplateDo) LeftJoin(table schema.Tabler, on ...field.Expr) IPromotionDiyTemplateDo {
	return p.withDO(p.DO.LeftJoin(table, on...))
}

func (p promotionDiyTemplateDo) RightJoin(table schema.Tabler, on ...field.Expr) IPromotionDiyTemplateDo {
	return p.withDO(p.DO.RightJoin(table, on...))
}

func (p promotionDiyTemplateDo) Group(cols ...field.Expr) IPromotionDiyTemplateDo {
	return p.withDO(p.DO.Group(cols...))
}

func (p promotionDiyTemplateDo) Having(conds ...gen.Condition) IPromotionDiyTemplateDo {
	return p.withDO(p.DO.Having(conds...))
}

func (p promotionDiyTemplateDo) Limit(limit int) IPromotionDiyTemplateDo {
	return p.withDO(p.DO.Limit(limit))
}

func (p promotionDiyTemplateDo) Offset(offset int) IPromotionDiyTemplateDo {
	return p.withDO(p.DO.Offset(offset))
}

func (p promotionDiyTemplateDo) Scopes(funcs ...func(gen.Dao) gen.Dao) IPromotionDiyTemplateDo {
	return p.withDO(p.DO.Scopes(funcs...))
}

func (p promotionDiyTemplateDo) Unscoped() IPromotionDiyTemplateDo {
	return p.withDO(p.DO.Unscoped())
}

func (p promotionDiyTemplateDo) Create(values ...*promotion.PromotionDiyTemplate) error {
	if len(values) == 0 {
		return nil
	}
	return p.DO.Create(values)
}

func (p promotionDiyTemplateDo) CreateInBatches(values []*promotion.PromotionDiyTemplate, batchSize int) error {
	return p.DO.CreateInBatches(values, batchSize)
}

// Save : !!! underlying implementation is different with GORM
// The method is equivalent to executing the statement: db.Clauses(clause.OnConflict{UpdateAll: true}).Create(values)
func (p promotionDiyTemplateDo) Save(values ...*promotion.PromotionDiyTemplate) error {
	if len(values) == 0 {
		return nil
	}
	return p.DO.Save(values)
}

func (p promotionDiyTemplateDo) First() (*promotion.PromotionDiyTemplate, error) {
	if result, err := p.DO.First(); err != nil {
		return nil, err
	} else {
		return result.(*promotion.PromotionDiyTemplate), nil
	}
}

func (p promotionDiyTemplateDo) Take() (*promotion.PromotionDiyTemplate, error) {
	if result, err := p.DO.Take(); err != nil {
		return nil, err
	} else {
		return result.(*promotion.PromotionDiyTemplate), nil
	}
}

func (p promotionDiyTemplateDo) Last() (*promotion.PromotionDiyTemplate, error) {
	if result, err := p.DO.Last(); err != nil {
		return nil, err
	} else {
		return result.(*promotion.PromotionDiyTemplate), nil
	}
}

func (p promotionDiyTemplateDo) Find() ([]*promotion.PromotionDiyTemplate, error) {
	result, err := p.DO.Find()
	return result.([]*promotion.PromotionDiyTemplate), err
}

func (p promotionDiyTemplateDo) FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*promotion.PromotionDiyTemplate, err error) {
	buf := make([]*promotion.PromotionDiyTemplate, 0, batchSize)
	err = p.DO.FindInBatches(&buf, batchSize, func(tx gen.Dao, batch int) error {
		defer func() { results = append(results, buf...) }()
		return fc(tx, batch)
	})
	return results, err
}

func (p promotionDiyTemplateDo) FindInBatches(result *[]*promotion.PromotionDiyTemplate, batchSize int, fc func(tx gen.Dao, batch int) error) error {
	return p.DO.FindInBatches(result, batchSize, fc)
}

func (p promotionDiyTemplateDo) Attrs(attrs ...field.AssignExpr) IPromotionDiyTemplateDo {
	return p.withDO(p.DO.Attrs(attrs...))
}

func (p promotionDiyTemplateDo) Assign(attrs ...field.AssignExpr) IPromotionDiyTemplateDo {
	return p.withDO(p.DO.Assign(attrs...))
}

func (p promotionDiyTemplateDo) Joins(fields ...field.RelationField) IPromotionDiyTemplateDo {
	for _, _f := range fields {
		p = *p.withDO(p.DO.Joins(_f))
	}
	return &p
}

func (p promotionDiyTemplateDo) Preload(fields ...field.RelationField) IPromotionDiyTemplateDo {
	for _, _f := range fields {
		p = *p.withDO(p.DO.Preload(_f))
	}
	return &p
}

func (p promotionDiyTemplateDo) FirstOrInit() (*promotion.PromotionDiyTemplate, error) {
	if result, err := p.DO.FirstOrInit(); err != nil {
		return nil, err
	} else {
		return result.(*promotion.PromotionDiyTemplate), nil
	}
}

func (p promotionDiyTemplateDo) FirstOrCreate() (*promotion.PromotionDiyTemplate, error) {
	if result, err := p.DO.FirstOrCreate(); err != nil {
		return nil, err
	} else {
		return result.(*promotion.PromotionDiyTemplate), nil
	}
}

func (p promotionDiyTemplateDo) FindByPage(offset int, limit int) (result []*promotion.PromotionDiyTemplate, count int64, err error) {
	result, err = p.Offset(offset).Limit(limit).Find()
	if err != nil {
		return
	}

	if size := len(result); 0 < limit && 0 < size && size < limit {
		count = int64(size + offset)
		return
	}

	count, err = p.Offset(-1).Limit(-1).Count()
	return
}

func (p promotionDiyTemplateDo) ScanByPage(result interface{}, offset int, limit int) (count int64, err error) {
	count, err = p.Count()
	if err != nil {
		return
	}

	err = p.Offset(offset).Limit(limit).Scan(result)
	return
}

func (p promotionDiyTemplateDo) Scan(result interface{}) (err error) {
	return p.DO.Scan(result)
}

func (p promotionDiyTemplateDo) Delete(models ...*promotion.PromotionDiyTemplate) (result gen.ResultInfo, err error) {
	return p.DO.Delete(models)
}

func (p *promotionDiyTemplateDo) withDO(do gen.Dao) *promotionDiyTemplateDo {
	p.DO = *do.(*gen.DO)
	return p
}
