// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package query

import (
	"context"
	"database/sql"

	"gorm.io/gorm"
	"gorm.io/gorm/clause"
	"gorm.io/gorm/schema"

	"gorm.io/gen"
	"gorm.io/gen/field"

	"gorm.io/plugin/dbresolver"

	"backend-go/internal/model"
)

func newSystemDictData(db *gorm.DB, opts ...gen.DOOption) systemDictData {
	_systemDictData := systemDictData{}

	_systemDictData.systemDictDataDo.UseDB(db, opts...)
	_systemDictData.systemDictDataDo.UseModel(&model.SystemDictData{})

	tableName := _systemDictData.systemDictDataDo.TableName()
	_systemDictData.ALL = field.NewAsterisk(tableName)
	_systemDictData.ID = field.NewInt64(tableName, "id")
	_systemDictData.Sort = field.NewInt32(tableName, "sort")
	_systemDictData.Label = field.NewString(tableName, "label")
	_systemDictData.Value = field.NewString(tableName, "value")
	_systemDictData.DictType = field.NewString(tableName, "dict_type")
	_systemDictData.Status = field.NewInt32(tableName, "status")
	_systemDictData.ColorType = field.NewString(tableName, "color_type")
	_systemDictData.CssClass = field.NewString(tableName, "css_class")
	_systemDictData.Remark = field.NewString(tableName, "remark")
	_systemDictData.Creator = field.NewString(tableName, "creator")
	_systemDictData.Updater = field.NewString(tableName, "updater")
	_systemDictData.CreatedAt = field.NewTime(tableName, "create_time")
	_systemDictData.UpdatedAt = field.NewTime(tableName, "update_time")
	_systemDictData.Deleted = field.NewField(tableName, "deleted")

	_systemDictData.fillFieldMap()

	return _systemDictData
}

type systemDictData struct {
	systemDictDataDo systemDictDataDo

	ALL       field.Asterisk
	ID        field.Int64
	Sort      field.Int32
	Label     field.String
	Value     field.String
	DictType  field.String
	Status    field.Int32
	ColorType field.String
	CssClass  field.String
	Remark    field.String
	Creator   field.String
	Updater   field.String
	CreatedAt field.Time
	UpdatedAt field.Time
	Deleted   field.Field

	fieldMap map[string]field.Expr
}

func (s systemDictData) Table(newTableName string) *systemDictData {
	s.systemDictDataDo.UseTable(newTableName)
	return s.updateTableName(newTableName)
}

func (s systemDictData) As(alias string) *systemDictData {
	s.systemDictDataDo.DO = *(s.systemDictDataDo.As(alias).(*gen.DO))
	return s.updateTableName(alias)
}

func (s *systemDictData) updateTableName(table string) *systemDictData {
	s.ALL = field.NewAsterisk(table)
	s.ID = field.NewInt64(table, "id")
	s.Sort = field.NewInt32(table, "sort")
	s.Label = field.NewString(table, "label")
	s.Value = field.NewString(table, "value")
	s.DictType = field.NewString(table, "dict_type")
	s.Status = field.NewInt32(table, "status")
	s.ColorType = field.NewString(table, "color_type")
	s.CssClass = field.NewString(table, "css_class")
	s.Remark = field.NewString(table, "remark")
	s.Creator = field.NewString(table, "creator")
	s.Updater = field.NewString(table, "updater")
	s.CreatedAt = field.NewTime(table, "create_time")
	s.UpdatedAt = field.NewTime(table, "update_time")
	s.Deleted = field.NewField(table, "deleted")

	s.fillFieldMap()

	return s
}

func (s *systemDictData) WithContext(ctx context.Context) ISystemDictDataDo {
	return s.systemDictDataDo.WithContext(ctx)
}

func (s systemDictData) TableName() string { return s.systemDictDataDo.TableName() }

func (s systemDictData) Alias() string { return s.systemDictDataDo.Alias() }

func (s systemDictData) Columns(cols ...field.Expr) gen.Columns {
	return s.systemDictDataDo.Columns(cols...)
}

func (s *systemDictData) GetFieldByName(fieldName string) (field.OrderExpr, bool) {
	_f, ok := s.fieldMap[fieldName]
	if !ok || _f == nil {
		return nil, false
	}
	_oe, ok := _f.(field.OrderExpr)
	return _oe, ok
}

func (s *systemDictData) fillFieldMap() {
	s.fieldMap = make(map[string]field.Expr, 14)
	s.fieldMap["id"] = s.ID
	s.fieldMap["sort"] = s.Sort
	s.fieldMap["label"] = s.Label
	s.fieldMap["value"] = s.Value
	s.fieldMap["dict_type"] = s.DictType
	s.fieldMap["status"] = s.Status
	s.fieldMap["color_type"] = s.ColorType
	s.fieldMap["css_class"] = s.CssClass
	s.fieldMap["remark"] = s.Remark
	s.fieldMap["creator"] = s.Creator
	s.fieldMap["updater"] = s.Updater
	s.fieldMap["create_time"] = s.CreatedAt
	s.fieldMap["update_time"] = s.UpdatedAt
	s.fieldMap["deleted"] = s.Deleted
}

func (s systemDictData) clone(db *gorm.DB) systemDictData {
	s.systemDictDataDo.ReplaceConnPool(db.Statement.ConnPool)
	return s
}

func (s systemDictData) replaceDB(db *gorm.DB) systemDictData {
	s.systemDictDataDo.ReplaceDB(db)
	return s
}

type systemDictDataDo struct{ gen.DO }

type ISystemDictDataDo interface {
	gen.SubQuery
	Debug() ISystemDictDataDo
	WithContext(ctx context.Context) ISystemDictDataDo
	WithResult(fc func(tx gen.Dao)) gen.ResultInfo
	ReplaceDB(db *gorm.DB)
	ReadDB() ISystemDictDataDo
	WriteDB() ISystemDictDataDo
	As(alias string) gen.Dao
	Session(config *gorm.Session) ISystemDictDataDo
	Columns(cols ...field.Expr) gen.Columns
	Clauses(conds ...clause.Expression) ISystemDictDataDo
	Not(conds ...gen.Condition) ISystemDictDataDo
	Or(conds ...gen.Condition) ISystemDictDataDo
	Select(conds ...field.Expr) ISystemDictDataDo
	Where(conds ...gen.Condition) ISystemDictDataDo
	Order(conds ...field.Expr) ISystemDictDataDo
	Distinct(cols ...field.Expr) ISystemDictDataDo
	Omit(cols ...field.Expr) ISystemDictDataDo
	Join(table schema.Tabler, on ...field.Expr) ISystemDictDataDo
	LeftJoin(table schema.Tabler, on ...field.Expr) ISystemDictDataDo
	RightJoin(table schema.Tabler, on ...field.Expr) ISystemDictDataDo
	Group(cols ...field.Expr) ISystemDictDataDo
	Having(conds ...gen.Condition) ISystemDictDataDo
	Limit(limit int) ISystemDictDataDo
	Offset(offset int) ISystemDictDataDo
	Count() (count int64, err error)
	Scopes(funcs ...func(gen.Dao) gen.Dao) ISystemDictDataDo
	Unscoped() ISystemDictDataDo
	Create(values ...*model.SystemDictData) error
	CreateInBatches(values []*model.SystemDictData, batchSize int) error
	Save(values ...*model.SystemDictData) error
	First() (*model.SystemDictData, error)
	Take() (*model.SystemDictData, error)
	Last() (*model.SystemDictData, error)
	Find() ([]*model.SystemDictData, error)
	FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.SystemDictData, err error)
	FindInBatches(result *[]*model.SystemDictData, batchSize int, fc func(tx gen.Dao, batch int) error) error
	Pluck(column field.Expr, dest interface{}) error
	Delete(...*model.SystemDictData) (info gen.ResultInfo, err error)
	Update(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	Updates(value interface{}) (info gen.ResultInfo, err error)
	UpdateColumn(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateColumnSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	UpdateColumns(value interface{}) (info gen.ResultInfo, err error)
	UpdateFrom(q gen.SubQuery) gen.Dao
	Attrs(attrs ...field.AssignExpr) ISystemDictDataDo
	Assign(attrs ...field.AssignExpr) ISystemDictDataDo
	Joins(fields ...field.RelationField) ISystemDictDataDo
	Preload(fields ...field.RelationField) ISystemDictDataDo
	FirstOrInit() (*model.SystemDictData, error)
	FirstOrCreate() (*model.SystemDictData, error)
	FindByPage(offset int, limit int) (result []*model.SystemDictData, count int64, err error)
	ScanByPage(result interface{}, offset int, limit int) (count int64, err error)
	Rows() (*sql.Rows, error)
	Row() *sql.Row
	Scan(result interface{}) (err error)
	Returning(value interface{}, columns ...string) ISystemDictDataDo
	UnderlyingDB() *gorm.DB
	schema.Tabler
}

func (s systemDictDataDo) Debug() ISystemDictDataDo {
	return s.withDO(s.DO.Debug())
}

func (s systemDictDataDo) WithContext(ctx context.Context) ISystemDictDataDo {
	return s.withDO(s.DO.WithContext(ctx))
}

func (s systemDictDataDo) ReadDB() ISystemDictDataDo {
	return s.Clauses(dbresolver.Read)
}

func (s systemDictDataDo) WriteDB() ISystemDictDataDo {
	return s.Clauses(dbresolver.Write)
}

func (s systemDictDataDo) Session(config *gorm.Session) ISystemDictDataDo {
	return s.withDO(s.DO.Session(config))
}

func (s systemDictDataDo) Clauses(conds ...clause.Expression) ISystemDictDataDo {
	return s.withDO(s.DO.Clauses(conds...))
}

func (s systemDictDataDo) Returning(value interface{}, columns ...string) ISystemDictDataDo {
	return s.withDO(s.DO.Returning(value, columns...))
}

func (s systemDictDataDo) Not(conds ...gen.Condition) ISystemDictDataDo {
	return s.withDO(s.DO.Not(conds...))
}

func (s systemDictDataDo) Or(conds ...gen.Condition) ISystemDictDataDo {
	return s.withDO(s.DO.Or(conds...))
}

func (s systemDictDataDo) Select(conds ...field.Expr) ISystemDictDataDo {
	return s.withDO(s.DO.Select(conds...))
}

func (s systemDictDataDo) Where(conds ...gen.Condition) ISystemDictDataDo {
	return s.withDO(s.DO.Where(conds...))
}

func (s systemDictDataDo) Order(conds ...field.Expr) ISystemDictDataDo {
	return s.withDO(s.DO.Order(conds...))
}

func (s systemDictDataDo) Distinct(cols ...field.Expr) ISystemDictDataDo {
	return s.withDO(s.DO.Distinct(cols...))
}

func (s systemDictDataDo) Omit(cols ...field.Expr) ISystemDictDataDo {
	return s.withDO(s.DO.Omit(cols...))
}

func (s systemDictDataDo) Join(table schema.Tabler, on ...field.Expr) ISystemDictDataDo {
	return s.withDO(s.DO.Join(table, on...))
}

func (s systemDictDataDo) LeftJoin(table schema.Tabler, on ...field.Expr) ISystemDictDataDo {
	return s.withDO(s.DO.LeftJoin(table, on...))
}

func (s systemDictDataDo) RightJoin(table schema.Tabler, on ...field.Expr) ISystemDictDataDo {
	return s.withDO(s.DO.RightJoin(table, on...))
}

func (s systemDictDataDo) Group(cols ...field.Expr) ISystemDictDataDo {
	return s.withDO(s.DO.Group(cols...))
}

func (s systemDictDataDo) Having(conds ...gen.Condition) ISystemDictDataDo {
	return s.withDO(s.DO.Having(conds...))
}

func (s systemDictDataDo) Limit(limit int) ISystemDictDataDo {
	return s.withDO(s.DO.Limit(limit))
}

func (s systemDictDataDo) Offset(offset int) ISystemDictDataDo {
	return s.withDO(s.DO.Offset(offset))
}

func (s systemDictDataDo) Scopes(funcs ...func(gen.Dao) gen.Dao) ISystemDictDataDo {
	return s.withDO(s.DO.Scopes(funcs...))
}

func (s systemDictDataDo) Unscoped() ISystemDictDataDo {
	return s.withDO(s.DO.Unscoped())
}

func (s systemDictDataDo) Create(values ...*model.SystemDictData) error {
	if len(values) == 0 {
		return nil
	}
	return s.DO.Create(values)
}

func (s systemDictDataDo) CreateInBatches(values []*model.SystemDictData, batchSize int) error {
	return s.DO.CreateInBatches(values, batchSize)
}

// Save : !!! underlying implementation is different with GORM
// The method is equivalent to executing the statement: db.Clauses(clause.OnConflict{UpdateAll: true}).Create(values)
func (s systemDictDataDo) Save(values ...*model.SystemDictData) error {
	if len(values) == 0 {
		return nil
	}
	return s.DO.Save(values)
}

func (s systemDictDataDo) First() (*model.SystemDictData, error) {
	if result, err := s.DO.First(); err != nil {
		return nil, err
	} else {
		return result.(*model.SystemDictData), nil
	}
}

func (s systemDictDataDo) Take() (*model.SystemDictData, error) {
	if result, err := s.DO.Take(); err != nil {
		return nil, err
	} else {
		return result.(*model.SystemDictData), nil
	}
}

func (s systemDictDataDo) Last() (*model.SystemDictData, error) {
	if result, err := s.DO.Last(); err != nil {
		return nil, err
	} else {
		return result.(*model.SystemDictData), nil
	}
}

func (s systemDictDataDo) Find() ([]*model.SystemDictData, error) {
	result, err := s.DO.Find()
	return result.([]*model.SystemDictData), err
}

func (s systemDictDataDo) FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.SystemDictData, err error) {
	buf := make([]*model.SystemDictData, 0, batchSize)
	err = s.DO.FindInBatches(&buf, batchSize, func(tx gen.Dao, batch int) error {
		defer func() { results = append(results, buf...) }()
		return fc(tx, batch)
	})
	return results, err
}

func (s systemDictDataDo) FindInBatches(result *[]*model.SystemDictData, batchSize int, fc func(tx gen.Dao, batch int) error) error {
	return s.DO.FindInBatches(result, batchSize, fc)
}

func (s systemDictDataDo) Attrs(attrs ...field.AssignExpr) ISystemDictDataDo {
	return s.withDO(s.DO.Attrs(attrs...))
}

func (s systemDictDataDo) Assign(attrs ...field.AssignExpr) ISystemDictDataDo {
	return s.withDO(s.DO.Assign(attrs...))
}

func (s systemDictDataDo) Joins(fields ...field.RelationField) ISystemDictDataDo {
	for _, _f := range fields {
		s = *s.withDO(s.DO.Joins(_f))
	}
	return &s
}

func (s systemDictDataDo) Preload(fields ...field.RelationField) ISystemDictDataDo {
	for _, _f := range fields {
		s = *s.withDO(s.DO.Preload(_f))
	}
	return &s
}

func (s systemDictDataDo) FirstOrInit() (*model.SystemDictData, error) {
	if result, err := s.DO.FirstOrInit(); err != nil {
		return nil, err
	} else {
		return result.(*model.SystemDictData), nil
	}
}

func (s systemDictDataDo) FirstOrCreate() (*model.SystemDictData, error) {
	if result, err := s.DO.FirstOrCreate(); err != nil {
		return nil, err
	} else {
		return result.(*model.SystemDictData), nil
	}
}

func (s systemDictDataDo) FindByPage(offset int, limit int) (result []*model.SystemDictData, count int64, err error) {
	result, err = s.Offset(offset).Limit(limit).Find()
	if err != nil {
		return
	}

	if size := len(result); 0 < limit && 0 < size && size < limit {
		count = int64(size + offset)
		return
	}

	count, err = s.Offset(-1).Limit(-1).Count()
	return
}

func (s systemDictDataDo) ScanByPage(result interface{}, offset int, limit int) (count int64, err error) {
	count, err = s.Count()
	if err != nil {
		return
	}

	err = s.Offset(offset).Limit(limit).Scan(result)
	return
}

func (s systemDictDataDo) Scan(result interface{}) (err error) {
	return s.DO.Scan(result)
}

func (s systemDictDataDo) Delete(models ...*model.SystemDictData) (result gen.ResultInfo, err error) {
	return s.DO.Delete(models)
}

func (s *systemDictDataDo) withDO(do gen.Dao) *systemDictDataDo {
	s.DO = *do.(*gen.DO)
	return s
}
