// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package query

import (
	"context"
	"database/sql"

	"gorm.io/gorm"
	"gorm.io/gorm/clause"
	"gorm.io/gorm/schema"

	"gorm.io/gen"
	"gorm.io/gen/field"

	"gorm.io/plugin/dbresolver"

	"backend-go/internal/model"
)

func newSystemSmsLog(db *gorm.DB, opts ...gen.DOOption) systemSmsLog {
	_systemSmsLog := systemSmsLog{}

	_systemSmsLog.systemSmsLogDo.UseDB(db, opts...)
	_systemSmsLog.systemSmsLogDo.UseModel(&model.SystemSmsLog{})

	tableName := _systemSmsLog.systemSmsLogDo.TableName()
	_systemSmsLog.ALL = field.NewAsterisk(tableName)
	_systemSmsLog.ID = field.NewInt64(tableName, "id")
	_systemSmsLog.ChannelId = field.NewInt64(tableName, "channel_id")
	_systemSmsLog.ChannelCode = field.NewString(tableName, "channel_code")
	_systemSmsLog.TemplateId = field.NewInt64(tableName, "template_id")
	_systemSmsLog.TemplateCode = field.NewString(tableName, "template_code")
	_systemSmsLog.TemplateType = field.NewInt32(tableName, "template_type")
	_systemSmsLog.TemplateContent = field.NewString(tableName, "template_content")
	_systemSmsLog.TemplateParams = field.NewField(tableName, "template_params")
	_systemSmsLog.ApiTemplateId = field.NewString(tableName, "api_template_id")
	_systemSmsLog.Mobile = field.NewString(tableName, "mobile")
	_systemSmsLog.UserId = field.NewInt64(tableName, "user_id")
	_systemSmsLog.UserType = field.NewInt32(tableName, "user_type")
	_systemSmsLog.SendStatus = field.NewInt32(tableName, "send_status")
	_systemSmsLog.SendTime = field.NewTime(tableName, "send_time")
	_systemSmsLog.ApiSendCode = field.NewString(tableName, "api_send_code")
	_systemSmsLog.ApiSendMsg = field.NewString(tableName, "api_send_msg")
	_systemSmsLog.ApiRequestId = field.NewString(tableName, "api_request_id")
	_systemSmsLog.ApiSerialNo = field.NewString(tableName, "api_serial_no")
	_systemSmsLog.ReceiveStatus = field.NewInt32(tableName, "receive_status")
	_systemSmsLog.ReceiveTime = field.NewTime(tableName, "receive_time")
	_systemSmsLog.ApiReceiveCode = field.NewString(tableName, "api_receive_code")
	_systemSmsLog.ApiReceiveMsg = field.NewString(tableName, "api_receive_msg")
	_systemSmsLog.Creator = field.NewString(tableName, "creator")
	_systemSmsLog.Updater = field.NewString(tableName, "updater")
	_systemSmsLog.CreatedAt = field.NewTime(tableName, "create_time")
	_systemSmsLog.UpdatedAt = field.NewTime(tableName, "update_time")
	_systemSmsLog.Deleted = field.NewField(tableName, "deleted")

	_systemSmsLog.fillFieldMap()

	return _systemSmsLog
}

type systemSmsLog struct {
	systemSmsLogDo systemSmsLogDo

	ALL             field.Asterisk
	ID              field.Int64  // 自增编号
	ChannelId       field.Int64  // 短信渠道编号
	ChannelCode     field.String // 短信渠道编码
	TemplateId      field.Int64  // 模板编号
	TemplateCode    field.String // 模板编码
	TemplateType    field.Int32  // 短信类型
	TemplateContent field.String // 模板内容
	TemplateParams  field.Field  // 模板参数
	ApiTemplateId   field.String // 短信 API 的模板编号
	Mobile          field.String // 手机号
	UserId          field.Int64  // 用户编号
	UserType        field.Int32  // 用户类型
	SendStatus      field.Int32  // 发送状态
	SendTime        field.Time   // 发送时间
	ApiSendCode     field.String // 短信 API 发送结果的编码
	ApiSendMsg      field.String // 短信 API 发送失败的提示
	ApiRequestId    field.String // 短信 API 发送返回的唯一请求 ID
	ApiSerialNo     field.String // 短信 API 发送返回的序号
	ReceiveStatus   field.Int32  // 接收状态
	ReceiveTime     field.Time   // 接收时间
	ApiReceiveCode  field.String // 短信 API 接收结果的编码
	ApiReceiveMsg   field.String // 短信 API 接收结果的提示
	Creator         field.String // 创建者
	Updater         field.String // 更新者
	CreatedAt       field.Time   // 创建时间
	UpdatedAt       field.Time   // 更新时间
	Deleted         field.Field  // 是否删除

	fieldMap map[string]field.Expr
}

func (s systemSmsLog) Table(newTableName string) *systemSmsLog {
	s.systemSmsLogDo.UseTable(newTableName)
	return s.updateTableName(newTableName)
}

func (s systemSmsLog) As(alias string) *systemSmsLog {
	s.systemSmsLogDo.DO = *(s.systemSmsLogDo.As(alias).(*gen.DO))
	return s.updateTableName(alias)
}

func (s *systemSmsLog) updateTableName(table string) *systemSmsLog {
	s.ALL = field.NewAsterisk(table)
	s.ID = field.NewInt64(table, "id")
	s.ChannelId = field.NewInt64(table, "channel_id")
	s.ChannelCode = field.NewString(table, "channel_code")
	s.TemplateId = field.NewInt64(table, "template_id")
	s.TemplateCode = field.NewString(table, "template_code")
	s.TemplateType = field.NewInt32(table, "template_type")
	s.TemplateContent = field.NewString(table, "template_content")
	s.TemplateParams = field.NewField(table, "template_params")
	s.ApiTemplateId = field.NewString(table, "api_template_id")
	s.Mobile = field.NewString(table, "mobile")
	s.UserId = field.NewInt64(table, "user_id")
	s.UserType = field.NewInt32(table, "user_type")
	s.SendStatus = field.NewInt32(table, "send_status")
	s.SendTime = field.NewTime(table, "send_time")
	s.ApiSendCode = field.NewString(table, "api_send_code")
	s.ApiSendMsg = field.NewString(table, "api_send_msg")
	s.ApiRequestId = field.NewString(table, "api_request_id")
	s.ApiSerialNo = field.NewString(table, "api_serial_no")
	s.ReceiveStatus = field.NewInt32(table, "receive_status")
	s.ReceiveTime = field.NewTime(table, "receive_time")
	s.ApiReceiveCode = field.NewString(table, "api_receive_code")
	s.ApiReceiveMsg = field.NewString(table, "api_receive_msg")
	s.Creator = field.NewString(table, "creator")
	s.Updater = field.NewString(table, "updater")
	s.CreatedAt = field.NewTime(table, "create_time")
	s.UpdatedAt = field.NewTime(table, "update_time")
	s.Deleted = field.NewField(table, "deleted")

	s.fillFieldMap()

	return s
}

func (s *systemSmsLog) WithContext(ctx context.Context) ISystemSmsLogDo {
	return s.systemSmsLogDo.WithContext(ctx)
}

func (s systemSmsLog) TableName() string { return s.systemSmsLogDo.TableName() }

func (s systemSmsLog) Alias() string { return s.systemSmsLogDo.Alias() }

func (s systemSmsLog) Columns(cols ...field.Expr) gen.Columns {
	return s.systemSmsLogDo.Columns(cols...)
}

func (s *systemSmsLog) GetFieldByName(fieldName string) (field.OrderExpr, bool) {
	_f, ok := s.fieldMap[fieldName]
	if !ok || _f == nil {
		return nil, false
	}
	_oe, ok := _f.(field.OrderExpr)
	return _oe, ok
}

func (s *systemSmsLog) fillFieldMap() {
	s.fieldMap = make(map[string]field.Expr, 27)
	s.fieldMap["id"] = s.ID
	s.fieldMap["channel_id"] = s.ChannelId
	s.fieldMap["channel_code"] = s.ChannelCode
	s.fieldMap["template_id"] = s.TemplateId
	s.fieldMap["template_code"] = s.TemplateCode
	s.fieldMap["template_type"] = s.TemplateType
	s.fieldMap["template_content"] = s.TemplateContent
	s.fieldMap["template_params"] = s.TemplateParams
	s.fieldMap["api_template_id"] = s.ApiTemplateId
	s.fieldMap["mobile"] = s.Mobile
	s.fieldMap["user_id"] = s.UserId
	s.fieldMap["user_type"] = s.UserType
	s.fieldMap["send_status"] = s.SendStatus
	s.fieldMap["send_time"] = s.SendTime
	s.fieldMap["api_send_code"] = s.ApiSendCode
	s.fieldMap["api_send_msg"] = s.ApiSendMsg
	s.fieldMap["api_request_id"] = s.ApiRequestId
	s.fieldMap["api_serial_no"] = s.ApiSerialNo
	s.fieldMap["receive_status"] = s.ReceiveStatus
	s.fieldMap["receive_time"] = s.ReceiveTime
	s.fieldMap["api_receive_code"] = s.ApiReceiveCode
	s.fieldMap["api_receive_msg"] = s.ApiReceiveMsg
	s.fieldMap["creator"] = s.Creator
	s.fieldMap["updater"] = s.Updater
	s.fieldMap["create_time"] = s.CreatedAt
	s.fieldMap["update_time"] = s.UpdatedAt
	s.fieldMap["deleted"] = s.Deleted
}

func (s systemSmsLog) clone(db *gorm.DB) systemSmsLog {
	s.systemSmsLogDo.ReplaceConnPool(db.Statement.ConnPool)
	return s
}

func (s systemSmsLog) replaceDB(db *gorm.DB) systemSmsLog {
	s.systemSmsLogDo.ReplaceDB(db)
	return s
}

type systemSmsLogDo struct{ gen.DO }

type ISystemSmsLogDo interface {
	gen.SubQuery
	Debug() ISystemSmsLogDo
	WithContext(ctx context.Context) ISystemSmsLogDo
	WithResult(fc func(tx gen.Dao)) gen.ResultInfo
	ReplaceDB(db *gorm.DB)
	ReadDB() ISystemSmsLogDo
	WriteDB() ISystemSmsLogDo
	As(alias string) gen.Dao
	Session(config *gorm.Session) ISystemSmsLogDo
	Columns(cols ...field.Expr) gen.Columns
	Clauses(conds ...clause.Expression) ISystemSmsLogDo
	Not(conds ...gen.Condition) ISystemSmsLogDo
	Or(conds ...gen.Condition) ISystemSmsLogDo
	Select(conds ...field.Expr) ISystemSmsLogDo
	Where(conds ...gen.Condition) ISystemSmsLogDo
	Order(conds ...field.Expr) ISystemSmsLogDo
	Distinct(cols ...field.Expr) ISystemSmsLogDo
	Omit(cols ...field.Expr) ISystemSmsLogDo
	Join(table schema.Tabler, on ...field.Expr) ISystemSmsLogDo
	LeftJoin(table schema.Tabler, on ...field.Expr) ISystemSmsLogDo
	RightJoin(table schema.Tabler, on ...field.Expr) ISystemSmsLogDo
	Group(cols ...field.Expr) ISystemSmsLogDo
	Having(conds ...gen.Condition) ISystemSmsLogDo
	Limit(limit int) ISystemSmsLogDo
	Offset(offset int) ISystemSmsLogDo
	Count() (count int64, err error)
	Scopes(funcs ...func(gen.Dao) gen.Dao) ISystemSmsLogDo
	Unscoped() ISystemSmsLogDo
	Create(values ...*model.SystemSmsLog) error
	CreateInBatches(values []*model.SystemSmsLog, batchSize int) error
	Save(values ...*model.SystemSmsLog) error
	First() (*model.SystemSmsLog, error)
	Take() (*model.SystemSmsLog, error)
	Last() (*model.SystemSmsLog, error)
	Find() ([]*model.SystemSmsLog, error)
	FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.SystemSmsLog, err error)
	FindInBatches(result *[]*model.SystemSmsLog, batchSize int, fc func(tx gen.Dao, batch int) error) error
	Pluck(column field.Expr, dest interface{}) error
	Delete(...*model.SystemSmsLog) (info gen.ResultInfo, err error)
	Update(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	Updates(value interface{}) (info gen.ResultInfo, err error)
	UpdateColumn(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateColumnSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	UpdateColumns(value interface{}) (info gen.ResultInfo, err error)
	UpdateFrom(q gen.SubQuery) gen.Dao
	Attrs(attrs ...field.AssignExpr) ISystemSmsLogDo
	Assign(attrs ...field.AssignExpr) ISystemSmsLogDo
	Joins(fields ...field.RelationField) ISystemSmsLogDo
	Preload(fields ...field.RelationField) ISystemSmsLogDo
	FirstOrInit() (*model.SystemSmsLog, error)
	FirstOrCreate() (*model.SystemSmsLog, error)
	FindByPage(offset int, limit int) (result []*model.SystemSmsLog, count int64, err error)
	ScanByPage(result interface{}, offset int, limit int) (count int64, err error)
	Rows() (*sql.Rows, error)
	Row() *sql.Row
	Scan(result interface{}) (err error)
	Returning(value interface{}, columns ...string) ISystemSmsLogDo
	UnderlyingDB() *gorm.DB
	schema.Tabler
}

func (s systemSmsLogDo) Debug() ISystemSmsLogDo {
	return s.withDO(s.DO.Debug())
}

func (s systemSmsLogDo) WithContext(ctx context.Context) ISystemSmsLogDo {
	return s.withDO(s.DO.WithContext(ctx))
}

func (s systemSmsLogDo) ReadDB() ISystemSmsLogDo {
	return s.Clauses(dbresolver.Read)
}

func (s systemSmsLogDo) WriteDB() ISystemSmsLogDo {
	return s.Clauses(dbresolver.Write)
}

func (s systemSmsLogDo) Session(config *gorm.Session) ISystemSmsLogDo {
	return s.withDO(s.DO.Session(config))
}

func (s systemSmsLogDo) Clauses(conds ...clause.Expression) ISystemSmsLogDo {
	return s.withDO(s.DO.Clauses(conds...))
}

func (s systemSmsLogDo) Returning(value interface{}, columns ...string) ISystemSmsLogDo {
	return s.withDO(s.DO.Returning(value, columns...))
}

func (s systemSmsLogDo) Not(conds ...gen.Condition) ISystemSmsLogDo {
	return s.withDO(s.DO.Not(conds...))
}

func (s systemSmsLogDo) Or(conds ...gen.Condition) ISystemSmsLogDo {
	return s.withDO(s.DO.Or(conds...))
}

func (s systemSmsLogDo) Select(conds ...field.Expr) ISystemSmsLogDo {
	return s.withDO(s.DO.Select(conds...))
}

func (s systemSmsLogDo) Where(conds ...gen.Condition) ISystemSmsLogDo {
	return s.withDO(s.DO.Where(conds...))
}

func (s systemSmsLogDo) Order(conds ...field.Expr) ISystemSmsLogDo {
	return s.withDO(s.DO.Order(conds...))
}

func (s systemSmsLogDo) Distinct(cols ...field.Expr) ISystemSmsLogDo {
	return s.withDO(s.DO.Distinct(cols...))
}

func (s systemSmsLogDo) Omit(cols ...field.Expr) ISystemSmsLogDo {
	return s.withDO(s.DO.Omit(cols...))
}

func (s systemSmsLogDo) Join(table schema.Tabler, on ...field.Expr) ISystemSmsLogDo {
	return s.withDO(s.DO.Join(table, on...))
}

func (s systemSmsLogDo) LeftJoin(table schema.Tabler, on ...field.Expr) ISystemSmsLogDo {
	return s.withDO(s.DO.LeftJoin(table, on...))
}

func (s systemSmsLogDo) RightJoin(table schema.Tabler, on ...field.Expr) ISystemSmsLogDo {
	return s.withDO(s.DO.RightJoin(table, on...))
}

func (s systemSmsLogDo) Group(cols ...field.Expr) ISystemSmsLogDo {
	return s.withDO(s.DO.Group(cols...))
}

func (s systemSmsLogDo) Having(conds ...gen.Condition) ISystemSmsLogDo {
	return s.withDO(s.DO.Having(conds...))
}

func (s systemSmsLogDo) Limit(limit int) ISystemSmsLogDo {
	return s.withDO(s.DO.Limit(limit))
}

func (s systemSmsLogDo) Offset(offset int) ISystemSmsLogDo {
	return s.withDO(s.DO.Offset(offset))
}

func (s systemSmsLogDo) Scopes(funcs ...func(gen.Dao) gen.Dao) ISystemSmsLogDo {
	return s.withDO(s.DO.Scopes(funcs...))
}

func (s systemSmsLogDo) Unscoped() ISystemSmsLogDo {
	return s.withDO(s.DO.Unscoped())
}

func (s systemSmsLogDo) Create(values ...*model.SystemSmsLog) error {
	if len(values) == 0 {
		return nil
	}
	return s.DO.Create(values)
}

func (s systemSmsLogDo) CreateInBatches(values []*model.SystemSmsLog, batchSize int) error {
	return s.DO.CreateInBatches(values, batchSize)
}

// Save : !!! underlying implementation is different with GORM
// The method is equivalent to executing the statement: db.Clauses(clause.OnConflict{UpdateAll: true}).Create(values)
func (s systemSmsLogDo) Save(values ...*model.SystemSmsLog) error {
	if len(values) == 0 {
		return nil
	}
	return s.DO.Save(values)
}

func (s systemSmsLogDo) First() (*model.SystemSmsLog, error) {
	if result, err := s.DO.First(); err != nil {
		return nil, err
	} else {
		return result.(*model.SystemSmsLog), nil
	}
}

func (s systemSmsLogDo) Take() (*model.SystemSmsLog, error) {
	if result, err := s.DO.Take(); err != nil {
		return nil, err
	} else {
		return result.(*model.SystemSmsLog), nil
	}
}

func (s systemSmsLogDo) Last() (*model.SystemSmsLog, error) {
	if result, err := s.DO.Last(); err != nil {
		return nil, err
	} else {
		return result.(*model.SystemSmsLog), nil
	}
}

func (s systemSmsLogDo) Find() ([]*model.SystemSmsLog, error) {
	result, err := s.DO.Find()
	return result.([]*model.SystemSmsLog), err
}

func (s systemSmsLogDo) FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.SystemSmsLog, err error) {
	buf := make([]*model.SystemSmsLog, 0, batchSize)
	err = s.DO.FindInBatches(&buf, batchSize, func(tx gen.Dao, batch int) error {
		defer func() { results = append(results, buf...) }()
		return fc(tx, batch)
	})
	return results, err
}

func (s systemSmsLogDo) FindInBatches(result *[]*model.SystemSmsLog, batchSize int, fc func(tx gen.Dao, batch int) error) error {
	return s.DO.FindInBatches(result, batchSize, fc)
}

func (s systemSmsLogDo) Attrs(attrs ...field.AssignExpr) ISystemSmsLogDo {
	return s.withDO(s.DO.Attrs(attrs...))
}

func (s systemSmsLogDo) Assign(attrs ...field.AssignExpr) ISystemSmsLogDo {
	return s.withDO(s.DO.Assign(attrs...))
}

func (s systemSmsLogDo) Joins(fields ...field.RelationField) ISystemSmsLogDo {
	for _, _f := range fields {
		s = *s.withDO(s.DO.Joins(_f))
	}
	return &s
}

func (s systemSmsLogDo) Preload(fields ...field.RelationField) ISystemSmsLogDo {
	for _, _f := range fields {
		s = *s.withDO(s.DO.Preload(_f))
	}
	return &s
}

func (s systemSmsLogDo) FirstOrInit() (*model.SystemSmsLog, error) {
	if result, err := s.DO.FirstOrInit(); err != nil {
		return nil, err
	} else {
		return result.(*model.SystemSmsLog), nil
	}
}

func (s systemSmsLogDo) FirstOrCreate() (*model.SystemSmsLog, error) {
	if result, err := s.DO.FirstOrCreate(); err != nil {
		return nil, err
	} else {
		return result.(*model.SystemSmsLog), nil
	}
}

func (s systemSmsLogDo) FindByPage(offset int, limit int) (result []*model.SystemSmsLog, count int64, err error) {
	result, err = s.Offset(offset).Limit(limit).Find()
	if err != nil {
		return
	}

	if size := len(result); 0 < limit && 0 < size && size < limit {
		count = int64(size + offset)
		return
	}

	count, err = s.Offset(-1).Limit(-1).Count()
	return
}

func (s systemSmsLogDo) ScanByPage(result interface{}, offset int, limit int) (count int64, err error) {
	count, err = s.Count()
	if err != nil {
		return
	}

	err = s.Offset(offset).Limit(limit).Scan(result)
	return
}

func (s systemSmsLogDo) Scan(result interface{}) (err error) {
	return s.DO.Scan(result)
}

func (s systemSmsLogDo) Delete(models ...*model.SystemSmsLog) (result gen.ResultInfo, err error) {
	return s.DO.Delete(models)
}

func (s *systemSmsLogDo) withDO(do gen.Dao) *systemSmsLogDo {
	s.DO = *do.(*gen.DO)
	return s
}
