// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package query

import (
	"context"
	"database/sql"

	"gorm.io/gorm"
	"gorm.io/gorm/clause"
	"gorm.io/gorm/schema"

	"gorm.io/gen"
	"gorm.io/gen/field"

	"gorm.io/plugin/dbresolver"

	"backend-go/internal/model"
)

func newSystemSmsChannel(db *gorm.DB, opts ...gen.DOOption) systemSmsChannel {
	_systemSmsChannel := systemSmsChannel{}

	_systemSmsChannel.systemSmsChannelDo.UseDB(db, opts...)
	_systemSmsChannel.systemSmsChannelDo.UseModel(&model.SystemSmsChannel{})

	tableName := _systemSmsChannel.systemSmsChannelDo.TableName()
	_systemSmsChannel.ALL = field.NewAsterisk(tableName)
	_systemSmsChannel.ID = field.NewInt64(tableName, "id")
	_systemSmsChannel.Signature = field.NewString(tableName, "signature")
	_systemSmsChannel.Code = field.NewString(tableName, "code")
	_systemSmsChannel.Status = field.NewInt32(tableName, "status")
	_systemSmsChannel.Remark = field.NewString(tableName, "remark")
	_systemSmsChannel.ApiKey = field.NewString(tableName, "api_key")
	_systemSmsChannel.ApiSecret = field.NewString(tableName, "api_secret")
	_systemSmsChannel.CallbackUrl = field.NewString(tableName, "callback_url")
	_systemSmsChannel.Creator = field.NewString(tableName, "creator")
	_systemSmsChannel.Updater = field.NewString(tableName, "updater")
	_systemSmsChannel.CreatedAt = field.NewTime(tableName, "create_time")
	_systemSmsChannel.UpdatedAt = field.NewTime(tableName, "update_time")
	_systemSmsChannel.Deleted = field.NewField(tableName, "deleted")

	_systemSmsChannel.fillFieldMap()

	return _systemSmsChannel
}

type systemSmsChannel struct {
	systemSmsChannelDo systemSmsChannelDo

	ALL         field.Asterisk
	ID          field.Int64  // 渠道编号
	Signature   field.String // 短信签名
	Code        field.String // 渠道编码
	Status      field.Int32  // 启用状态
	Remark      field.String // 备注
	ApiKey      field.String // 短信 API 的账号
	ApiSecret   field.String // 短信 API 的密钥
	CallbackUrl field.String // 短信发送回调 URL
	Creator     field.String // 创建者
	Updater     field.String // 更新者
	CreatedAt   field.Time   // 创建时间
	UpdatedAt   field.Time   // 更新时间
	Deleted     field.Field  // 是否删除

	fieldMap map[string]field.Expr
}

func (s systemSmsChannel) Table(newTableName string) *systemSmsChannel {
	s.systemSmsChannelDo.UseTable(newTableName)
	return s.updateTableName(newTableName)
}

func (s systemSmsChannel) As(alias string) *systemSmsChannel {
	s.systemSmsChannelDo.DO = *(s.systemSmsChannelDo.As(alias).(*gen.DO))
	return s.updateTableName(alias)
}

func (s *systemSmsChannel) updateTableName(table string) *systemSmsChannel {
	s.ALL = field.NewAsterisk(table)
	s.ID = field.NewInt64(table, "id")
	s.Signature = field.NewString(table, "signature")
	s.Code = field.NewString(table, "code")
	s.Status = field.NewInt32(table, "status")
	s.Remark = field.NewString(table, "remark")
	s.ApiKey = field.NewString(table, "api_key")
	s.ApiSecret = field.NewString(table, "api_secret")
	s.CallbackUrl = field.NewString(table, "callback_url")
	s.Creator = field.NewString(table, "creator")
	s.Updater = field.NewString(table, "updater")
	s.CreatedAt = field.NewTime(table, "create_time")
	s.UpdatedAt = field.NewTime(table, "update_time")
	s.Deleted = field.NewField(table, "deleted")

	s.fillFieldMap()

	return s
}

func (s *systemSmsChannel) WithContext(ctx context.Context) ISystemSmsChannelDo {
	return s.systemSmsChannelDo.WithContext(ctx)
}

func (s systemSmsChannel) TableName() string { return s.systemSmsChannelDo.TableName() }

func (s systemSmsChannel) Alias() string { return s.systemSmsChannelDo.Alias() }

func (s systemSmsChannel) Columns(cols ...field.Expr) gen.Columns {
	return s.systemSmsChannelDo.Columns(cols...)
}

func (s *systemSmsChannel) GetFieldByName(fieldName string) (field.OrderExpr, bool) {
	_f, ok := s.fieldMap[fieldName]
	if !ok || _f == nil {
		return nil, false
	}
	_oe, ok := _f.(field.OrderExpr)
	return _oe, ok
}

func (s *systemSmsChannel) fillFieldMap() {
	s.fieldMap = make(map[string]field.Expr, 13)
	s.fieldMap["id"] = s.ID
	s.fieldMap["signature"] = s.Signature
	s.fieldMap["code"] = s.Code
	s.fieldMap["status"] = s.Status
	s.fieldMap["remark"] = s.Remark
	s.fieldMap["api_key"] = s.ApiKey
	s.fieldMap["api_secret"] = s.ApiSecret
	s.fieldMap["callback_url"] = s.CallbackUrl
	s.fieldMap["creator"] = s.Creator
	s.fieldMap["updater"] = s.Updater
	s.fieldMap["create_time"] = s.CreatedAt
	s.fieldMap["update_time"] = s.UpdatedAt
	s.fieldMap["deleted"] = s.Deleted
}

func (s systemSmsChannel) clone(db *gorm.DB) systemSmsChannel {
	s.systemSmsChannelDo.ReplaceConnPool(db.Statement.ConnPool)
	return s
}

func (s systemSmsChannel) replaceDB(db *gorm.DB) systemSmsChannel {
	s.systemSmsChannelDo.ReplaceDB(db)
	return s
}

type systemSmsChannelDo struct{ gen.DO }

type ISystemSmsChannelDo interface {
	gen.SubQuery
	Debug() ISystemSmsChannelDo
	WithContext(ctx context.Context) ISystemSmsChannelDo
	WithResult(fc func(tx gen.Dao)) gen.ResultInfo
	ReplaceDB(db *gorm.DB)
	ReadDB() ISystemSmsChannelDo
	WriteDB() ISystemSmsChannelDo
	As(alias string) gen.Dao
	Session(config *gorm.Session) ISystemSmsChannelDo
	Columns(cols ...field.Expr) gen.Columns
	Clauses(conds ...clause.Expression) ISystemSmsChannelDo
	Not(conds ...gen.Condition) ISystemSmsChannelDo
	Or(conds ...gen.Condition) ISystemSmsChannelDo
	Select(conds ...field.Expr) ISystemSmsChannelDo
	Where(conds ...gen.Condition) ISystemSmsChannelDo
	Order(conds ...field.Expr) ISystemSmsChannelDo
	Distinct(cols ...field.Expr) ISystemSmsChannelDo
	Omit(cols ...field.Expr) ISystemSmsChannelDo
	Join(table schema.Tabler, on ...field.Expr) ISystemSmsChannelDo
	LeftJoin(table schema.Tabler, on ...field.Expr) ISystemSmsChannelDo
	RightJoin(table schema.Tabler, on ...field.Expr) ISystemSmsChannelDo
	Group(cols ...field.Expr) ISystemSmsChannelDo
	Having(conds ...gen.Condition) ISystemSmsChannelDo
	Limit(limit int) ISystemSmsChannelDo
	Offset(offset int) ISystemSmsChannelDo
	Count() (count int64, err error)
	Scopes(funcs ...func(gen.Dao) gen.Dao) ISystemSmsChannelDo
	Unscoped() ISystemSmsChannelDo
	Create(values ...*model.SystemSmsChannel) error
	CreateInBatches(values []*model.SystemSmsChannel, batchSize int) error
	Save(values ...*model.SystemSmsChannel) error
	First() (*model.SystemSmsChannel, error)
	Take() (*model.SystemSmsChannel, error)
	Last() (*model.SystemSmsChannel, error)
	Find() ([]*model.SystemSmsChannel, error)
	FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.SystemSmsChannel, err error)
	FindInBatches(result *[]*model.SystemSmsChannel, batchSize int, fc func(tx gen.Dao, batch int) error) error
	Pluck(column field.Expr, dest interface{}) error
	Delete(...*model.SystemSmsChannel) (info gen.ResultInfo, err error)
	Update(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	Updates(value interface{}) (info gen.ResultInfo, err error)
	UpdateColumn(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateColumnSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	UpdateColumns(value interface{}) (info gen.ResultInfo, err error)
	UpdateFrom(q gen.SubQuery) gen.Dao
	Attrs(attrs ...field.AssignExpr) ISystemSmsChannelDo
	Assign(attrs ...field.AssignExpr) ISystemSmsChannelDo
	Joins(fields ...field.RelationField) ISystemSmsChannelDo
	Preload(fields ...field.RelationField) ISystemSmsChannelDo
	FirstOrInit() (*model.SystemSmsChannel, error)
	FirstOrCreate() (*model.SystemSmsChannel, error)
	FindByPage(offset int, limit int) (result []*model.SystemSmsChannel, count int64, err error)
	ScanByPage(result interface{}, offset int, limit int) (count int64, err error)
	Rows() (*sql.Rows, error)
	Row() *sql.Row
	Scan(result interface{}) (err error)
	Returning(value interface{}, columns ...string) ISystemSmsChannelDo
	UnderlyingDB() *gorm.DB
	schema.Tabler
}

func (s systemSmsChannelDo) Debug() ISystemSmsChannelDo {
	return s.withDO(s.DO.Debug())
}

func (s systemSmsChannelDo) WithContext(ctx context.Context) ISystemSmsChannelDo {
	return s.withDO(s.DO.WithContext(ctx))
}

func (s systemSmsChannelDo) ReadDB() ISystemSmsChannelDo {
	return s.Clauses(dbresolver.Read)
}

func (s systemSmsChannelDo) WriteDB() ISystemSmsChannelDo {
	return s.Clauses(dbresolver.Write)
}

func (s systemSmsChannelDo) Session(config *gorm.Session) ISystemSmsChannelDo {
	return s.withDO(s.DO.Session(config))
}

func (s systemSmsChannelDo) Clauses(conds ...clause.Expression) ISystemSmsChannelDo {
	return s.withDO(s.DO.Clauses(conds...))
}

func (s systemSmsChannelDo) Returning(value interface{}, columns ...string) ISystemSmsChannelDo {
	return s.withDO(s.DO.Returning(value, columns...))
}

func (s systemSmsChannelDo) Not(conds ...gen.Condition) ISystemSmsChannelDo {
	return s.withDO(s.DO.Not(conds...))
}

func (s systemSmsChannelDo) Or(conds ...gen.Condition) ISystemSmsChannelDo {
	return s.withDO(s.DO.Or(conds...))
}

func (s systemSmsChannelDo) Select(conds ...field.Expr) ISystemSmsChannelDo {
	return s.withDO(s.DO.Select(conds...))
}

func (s systemSmsChannelDo) Where(conds ...gen.Condition) ISystemSmsChannelDo {
	return s.withDO(s.DO.Where(conds...))
}

func (s systemSmsChannelDo) Order(conds ...field.Expr) ISystemSmsChannelDo {
	return s.withDO(s.DO.Order(conds...))
}

func (s systemSmsChannelDo) Distinct(cols ...field.Expr) ISystemSmsChannelDo {
	return s.withDO(s.DO.Distinct(cols...))
}

func (s systemSmsChannelDo) Omit(cols ...field.Expr) ISystemSmsChannelDo {
	return s.withDO(s.DO.Omit(cols...))
}

func (s systemSmsChannelDo) Join(table schema.Tabler, on ...field.Expr) ISystemSmsChannelDo {
	return s.withDO(s.DO.Join(table, on...))
}

func (s systemSmsChannelDo) LeftJoin(table schema.Tabler, on ...field.Expr) ISystemSmsChannelDo {
	return s.withDO(s.DO.LeftJoin(table, on...))
}

func (s systemSmsChannelDo) RightJoin(table schema.Tabler, on ...field.Expr) ISystemSmsChannelDo {
	return s.withDO(s.DO.RightJoin(table, on...))
}

func (s systemSmsChannelDo) Group(cols ...field.Expr) ISystemSmsChannelDo {
	return s.withDO(s.DO.Group(cols...))
}

func (s systemSmsChannelDo) Having(conds ...gen.Condition) ISystemSmsChannelDo {
	return s.withDO(s.DO.Having(conds...))
}

func (s systemSmsChannelDo) Limit(limit int) ISystemSmsChannelDo {
	return s.withDO(s.DO.Limit(limit))
}

func (s systemSmsChannelDo) Offset(offset int) ISystemSmsChannelDo {
	return s.withDO(s.DO.Offset(offset))
}

func (s systemSmsChannelDo) Scopes(funcs ...func(gen.Dao) gen.Dao) ISystemSmsChannelDo {
	return s.withDO(s.DO.Scopes(funcs...))
}

func (s systemSmsChannelDo) Unscoped() ISystemSmsChannelDo {
	return s.withDO(s.DO.Unscoped())
}

func (s systemSmsChannelDo) Create(values ...*model.SystemSmsChannel) error {
	if len(values) == 0 {
		return nil
	}
	return s.DO.Create(values)
}

func (s systemSmsChannelDo) CreateInBatches(values []*model.SystemSmsChannel, batchSize int) error {
	return s.DO.CreateInBatches(values, batchSize)
}

// Save : !!! underlying implementation is different with GORM
// The method is equivalent to executing the statement: db.Clauses(clause.OnConflict{UpdateAll: true}).Create(values)
func (s systemSmsChannelDo) Save(values ...*model.SystemSmsChannel) error {
	if len(values) == 0 {
		return nil
	}
	return s.DO.Save(values)
}

func (s systemSmsChannelDo) First() (*model.SystemSmsChannel, error) {
	if result, err := s.DO.First(); err != nil {
		return nil, err
	} else {
		return result.(*model.SystemSmsChannel), nil
	}
}

func (s systemSmsChannelDo) Take() (*model.SystemSmsChannel, error) {
	if result, err := s.DO.Take(); err != nil {
		return nil, err
	} else {
		return result.(*model.SystemSmsChannel), nil
	}
}

func (s systemSmsChannelDo) Last() (*model.SystemSmsChannel, error) {
	if result, err := s.DO.Last(); err != nil {
		return nil, err
	} else {
		return result.(*model.SystemSmsChannel), nil
	}
}

func (s systemSmsChannelDo) Find() ([]*model.SystemSmsChannel, error) {
	result, err := s.DO.Find()
	return result.([]*model.SystemSmsChannel), err
}

func (s systemSmsChannelDo) FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.SystemSmsChannel, err error) {
	buf := make([]*model.SystemSmsChannel, 0, batchSize)
	err = s.DO.FindInBatches(&buf, batchSize, func(tx gen.Dao, batch int) error {
		defer func() { results = append(results, buf...) }()
		return fc(tx, batch)
	})
	return results, err
}

func (s systemSmsChannelDo) FindInBatches(result *[]*model.SystemSmsChannel, batchSize int, fc func(tx gen.Dao, batch int) error) error {
	return s.DO.FindInBatches(result, batchSize, fc)
}

func (s systemSmsChannelDo) Attrs(attrs ...field.AssignExpr) ISystemSmsChannelDo {
	return s.withDO(s.DO.Attrs(attrs...))
}

func (s systemSmsChannelDo) Assign(attrs ...field.AssignExpr) ISystemSmsChannelDo {
	return s.withDO(s.DO.Assign(attrs...))
}

func (s systemSmsChannelDo) Joins(fields ...field.RelationField) ISystemSmsChannelDo {
	for _, _f := range fields {
		s = *s.withDO(s.DO.Joins(_f))
	}
	return &s
}

func (s systemSmsChannelDo) Preload(fields ...field.RelationField) ISystemSmsChannelDo {
	for _, _f := range fields {
		s = *s.withDO(s.DO.Preload(_f))
	}
	return &s
}

func (s systemSmsChannelDo) FirstOrInit() (*model.SystemSmsChannel, error) {
	if result, err := s.DO.FirstOrInit(); err != nil {
		return nil, err
	} else {
		return result.(*model.SystemSmsChannel), nil
	}
}

func (s systemSmsChannelDo) FirstOrCreate() (*model.SystemSmsChannel, error) {
	if result, err := s.DO.FirstOrCreate(); err != nil {
		return nil, err
	} else {
		return result.(*model.SystemSmsChannel), nil
	}
}

func (s systemSmsChannelDo) FindByPage(offset int, limit int) (result []*model.SystemSmsChannel, count int64, err error) {
	result, err = s.Offset(offset).Limit(limit).Find()
	if err != nil {
		return
	}

	if size := len(result); 0 < limit && 0 < size && size < limit {
		count = int64(size + offset)
		return
	}

	count, err = s.Offset(-1).Limit(-1).Count()
	return
}

func (s systemSmsChannelDo) ScanByPage(result interface{}, offset int, limit int) (count int64, err error) {
	count, err = s.Count()
	if err != nil {
		return
	}

	err = s.Offset(offset).Limit(limit).Scan(result)
	return
}

func (s systemSmsChannelDo) Scan(result interface{}) (err error) {
	return s.DO.Scan(result)
}

func (s systemSmsChannelDo) Delete(models ...*model.SystemSmsChannel) (result gen.ResultInfo, err error) {
	return s.DO.Delete(models)
}

func (s *systemSmsChannelDo) withDO(do gen.Dao) *systemSmsChannelDo {
	s.DO = *do.(*gen.DO)
	return s
}
