// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package query

import (
	"context"
	"database/sql"

	"gorm.io/gorm"
	"gorm.io/gorm/clause"
	"gorm.io/gorm/schema"

	"gorm.io/gen"
	"gorm.io/gen/field"

	"gorm.io/plugin/dbresolver"

	"backend-go/internal/model"
)

func newSystemSmsTemplate(db *gorm.DB, opts ...gen.DOOption) systemSmsTemplate {
	_systemSmsTemplate := systemSmsTemplate{}

	_systemSmsTemplate.systemSmsTemplateDo.UseDB(db, opts...)
	_systemSmsTemplate.systemSmsTemplateDo.UseModel(&model.SystemSmsTemplate{})

	tableName := _systemSmsTemplate.systemSmsTemplateDo.TableName()
	_systemSmsTemplate.ALL = field.NewAsterisk(tableName)
	_systemSmsTemplate.ID = field.NewInt64(tableName, "id")
	_systemSmsTemplate.Type = field.NewInt32(tableName, "type")
	_systemSmsTemplate.Status = field.NewInt32(tableName, "status")
	_systemSmsTemplate.Code = field.NewString(tableName, "code")
	_systemSmsTemplate.Name = field.NewString(tableName, "name")
	_systemSmsTemplate.Content = field.NewString(tableName, "content")
	_systemSmsTemplate.Params = field.NewField(tableName, "params")
	_systemSmsTemplate.Remark = field.NewString(tableName, "remark")
	_systemSmsTemplate.ApiTemplateId = field.NewString(tableName, "api_template_id")
	_systemSmsTemplate.ChannelId = field.NewInt64(tableName, "channel_id")
	_systemSmsTemplate.ChannelCode = field.NewString(tableName, "channel_code")
	_systemSmsTemplate.Creator = field.NewString(tableName, "creator")
	_systemSmsTemplate.Updater = field.NewString(tableName, "updater")
	_systemSmsTemplate.CreatedAt = field.NewTime(tableName, "create_time")
	_systemSmsTemplate.UpdatedAt = field.NewTime(tableName, "update_time")
	_systemSmsTemplate.Deleted = field.NewField(tableName, "deleted")

	_systemSmsTemplate.fillFieldMap()

	return _systemSmsTemplate
}

type systemSmsTemplate struct {
	systemSmsTemplateDo systemSmsTemplateDo

	ALL           field.Asterisk
	ID            field.Int64  // 自增编号
	Type          field.Int32  // 短信类型
	Status        field.Int32  // 启用状态
	Code          field.String // 模板编码
	Name          field.String // 模板名称
	Content       field.String // 模板内容
	Params        field.Field  // 参数数组
	Remark        field.String // 备注
	ApiTemplateId field.String // 短信 API 的模板编号
	ChannelId     field.Int64  // 短信渠道编号
	ChannelCode   field.String // 短信渠道编码
	Creator       field.String // 创建者
	Updater       field.String // 更新者
	CreatedAt     field.Time   // 创建时间
	UpdatedAt     field.Time   // 更新时间
	Deleted       field.Field  // 是否删除

	fieldMap map[string]field.Expr
}

func (s systemSmsTemplate) Table(newTableName string) *systemSmsTemplate {
	s.systemSmsTemplateDo.UseTable(newTableName)
	return s.updateTableName(newTableName)
}

func (s systemSmsTemplate) As(alias string) *systemSmsTemplate {
	s.systemSmsTemplateDo.DO = *(s.systemSmsTemplateDo.As(alias).(*gen.DO))
	return s.updateTableName(alias)
}

func (s *systemSmsTemplate) updateTableName(table string) *systemSmsTemplate {
	s.ALL = field.NewAsterisk(table)
	s.ID = field.NewInt64(table, "id")
	s.Type = field.NewInt32(table, "type")
	s.Status = field.NewInt32(table, "status")
	s.Code = field.NewString(table, "code")
	s.Name = field.NewString(table, "name")
	s.Content = field.NewString(table, "content")
	s.Params = field.NewField(table, "params")
	s.Remark = field.NewString(table, "remark")
	s.ApiTemplateId = field.NewString(table, "api_template_id")
	s.ChannelId = field.NewInt64(table, "channel_id")
	s.ChannelCode = field.NewString(table, "channel_code")
	s.Creator = field.NewString(table, "creator")
	s.Updater = field.NewString(table, "updater")
	s.CreatedAt = field.NewTime(table, "create_time")
	s.UpdatedAt = field.NewTime(table, "update_time")
	s.Deleted = field.NewField(table, "deleted")

	s.fillFieldMap()

	return s
}

func (s *systemSmsTemplate) WithContext(ctx context.Context) ISystemSmsTemplateDo {
	return s.systemSmsTemplateDo.WithContext(ctx)
}

func (s systemSmsTemplate) TableName() string { return s.systemSmsTemplateDo.TableName() }

func (s systemSmsTemplate) Alias() string { return s.systemSmsTemplateDo.Alias() }

func (s systemSmsTemplate) Columns(cols ...field.Expr) gen.Columns {
	return s.systemSmsTemplateDo.Columns(cols...)
}

func (s *systemSmsTemplate) GetFieldByName(fieldName string) (field.OrderExpr, bool) {
	_f, ok := s.fieldMap[fieldName]
	if !ok || _f == nil {
		return nil, false
	}
	_oe, ok := _f.(field.OrderExpr)
	return _oe, ok
}

func (s *systemSmsTemplate) fillFieldMap() {
	s.fieldMap = make(map[string]field.Expr, 16)
	s.fieldMap["id"] = s.ID
	s.fieldMap["type"] = s.Type
	s.fieldMap["status"] = s.Status
	s.fieldMap["code"] = s.Code
	s.fieldMap["name"] = s.Name
	s.fieldMap["content"] = s.Content
	s.fieldMap["params"] = s.Params
	s.fieldMap["remark"] = s.Remark
	s.fieldMap["api_template_id"] = s.ApiTemplateId
	s.fieldMap["channel_id"] = s.ChannelId
	s.fieldMap["channel_code"] = s.ChannelCode
	s.fieldMap["creator"] = s.Creator
	s.fieldMap["updater"] = s.Updater
	s.fieldMap["create_time"] = s.CreatedAt
	s.fieldMap["update_time"] = s.UpdatedAt
	s.fieldMap["deleted"] = s.Deleted
}

func (s systemSmsTemplate) clone(db *gorm.DB) systemSmsTemplate {
	s.systemSmsTemplateDo.ReplaceConnPool(db.Statement.ConnPool)
	return s
}

func (s systemSmsTemplate) replaceDB(db *gorm.DB) systemSmsTemplate {
	s.systemSmsTemplateDo.ReplaceDB(db)
	return s
}

type systemSmsTemplateDo struct{ gen.DO }

type ISystemSmsTemplateDo interface {
	gen.SubQuery
	Debug() ISystemSmsTemplateDo
	WithContext(ctx context.Context) ISystemSmsTemplateDo
	WithResult(fc func(tx gen.Dao)) gen.ResultInfo
	ReplaceDB(db *gorm.DB)
	ReadDB() ISystemSmsTemplateDo
	WriteDB() ISystemSmsTemplateDo
	As(alias string) gen.Dao
	Session(config *gorm.Session) ISystemSmsTemplateDo
	Columns(cols ...field.Expr) gen.Columns
	Clauses(conds ...clause.Expression) ISystemSmsTemplateDo
	Not(conds ...gen.Condition) ISystemSmsTemplateDo
	Or(conds ...gen.Condition) ISystemSmsTemplateDo
	Select(conds ...field.Expr) ISystemSmsTemplateDo
	Where(conds ...gen.Condition) ISystemSmsTemplateDo
	Order(conds ...field.Expr) ISystemSmsTemplateDo
	Distinct(cols ...field.Expr) ISystemSmsTemplateDo
	Omit(cols ...field.Expr) ISystemSmsTemplateDo
	Join(table schema.Tabler, on ...field.Expr) ISystemSmsTemplateDo
	LeftJoin(table schema.Tabler, on ...field.Expr) ISystemSmsTemplateDo
	RightJoin(table schema.Tabler, on ...field.Expr) ISystemSmsTemplateDo
	Group(cols ...field.Expr) ISystemSmsTemplateDo
	Having(conds ...gen.Condition) ISystemSmsTemplateDo
	Limit(limit int) ISystemSmsTemplateDo
	Offset(offset int) ISystemSmsTemplateDo
	Count() (count int64, err error)
	Scopes(funcs ...func(gen.Dao) gen.Dao) ISystemSmsTemplateDo
	Unscoped() ISystemSmsTemplateDo
	Create(values ...*model.SystemSmsTemplate) error
	CreateInBatches(values []*model.SystemSmsTemplate, batchSize int) error
	Save(values ...*model.SystemSmsTemplate) error
	First() (*model.SystemSmsTemplate, error)
	Take() (*model.SystemSmsTemplate, error)
	Last() (*model.SystemSmsTemplate, error)
	Find() ([]*model.SystemSmsTemplate, error)
	FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.SystemSmsTemplate, err error)
	FindInBatches(result *[]*model.SystemSmsTemplate, batchSize int, fc func(tx gen.Dao, batch int) error) error
	Pluck(column field.Expr, dest interface{}) error
	Delete(...*model.SystemSmsTemplate) (info gen.ResultInfo, err error)
	Update(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	Updates(value interface{}) (info gen.ResultInfo, err error)
	UpdateColumn(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateColumnSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	UpdateColumns(value interface{}) (info gen.ResultInfo, err error)
	UpdateFrom(q gen.SubQuery) gen.Dao
	Attrs(attrs ...field.AssignExpr) ISystemSmsTemplateDo
	Assign(attrs ...field.AssignExpr) ISystemSmsTemplateDo
	Joins(fields ...field.RelationField) ISystemSmsTemplateDo
	Preload(fields ...field.RelationField) ISystemSmsTemplateDo
	FirstOrInit() (*model.SystemSmsTemplate, error)
	FirstOrCreate() (*model.SystemSmsTemplate, error)
	FindByPage(offset int, limit int) (result []*model.SystemSmsTemplate, count int64, err error)
	ScanByPage(result interface{}, offset int, limit int) (count int64, err error)
	Rows() (*sql.Rows, error)
	Row() *sql.Row
	Scan(result interface{}) (err error)
	Returning(value interface{}, columns ...string) ISystemSmsTemplateDo
	UnderlyingDB() *gorm.DB
	schema.Tabler
}

func (s systemSmsTemplateDo) Debug() ISystemSmsTemplateDo {
	return s.withDO(s.DO.Debug())
}

func (s systemSmsTemplateDo) WithContext(ctx context.Context) ISystemSmsTemplateDo {
	return s.withDO(s.DO.WithContext(ctx))
}

func (s systemSmsTemplateDo) ReadDB() ISystemSmsTemplateDo {
	return s.Clauses(dbresolver.Read)
}

func (s systemSmsTemplateDo) WriteDB() ISystemSmsTemplateDo {
	return s.Clauses(dbresolver.Write)
}

func (s systemSmsTemplateDo) Session(config *gorm.Session) ISystemSmsTemplateDo {
	return s.withDO(s.DO.Session(config))
}

func (s systemSmsTemplateDo) Clauses(conds ...clause.Expression) ISystemSmsTemplateDo {
	return s.withDO(s.DO.Clauses(conds...))
}

func (s systemSmsTemplateDo) Returning(value interface{}, columns ...string) ISystemSmsTemplateDo {
	return s.withDO(s.DO.Returning(value, columns...))
}

func (s systemSmsTemplateDo) Not(conds ...gen.Condition) ISystemSmsTemplateDo {
	return s.withDO(s.DO.Not(conds...))
}

func (s systemSmsTemplateDo) Or(conds ...gen.Condition) ISystemSmsTemplateDo {
	return s.withDO(s.DO.Or(conds...))
}

func (s systemSmsTemplateDo) Select(conds ...field.Expr) ISystemSmsTemplateDo {
	return s.withDO(s.DO.Select(conds...))
}

func (s systemSmsTemplateDo) Where(conds ...gen.Condition) ISystemSmsTemplateDo {
	return s.withDO(s.DO.Where(conds...))
}

func (s systemSmsTemplateDo) Order(conds ...field.Expr) ISystemSmsTemplateDo {
	return s.withDO(s.DO.Order(conds...))
}

func (s systemSmsTemplateDo) Distinct(cols ...field.Expr) ISystemSmsTemplateDo {
	return s.withDO(s.DO.Distinct(cols...))
}

func (s systemSmsTemplateDo) Omit(cols ...field.Expr) ISystemSmsTemplateDo {
	return s.withDO(s.DO.Omit(cols...))
}

func (s systemSmsTemplateDo) Join(table schema.Tabler, on ...field.Expr) ISystemSmsTemplateDo {
	return s.withDO(s.DO.Join(table, on...))
}

func (s systemSmsTemplateDo) LeftJoin(table schema.Tabler, on ...field.Expr) ISystemSmsTemplateDo {
	return s.withDO(s.DO.LeftJoin(table, on...))
}

func (s systemSmsTemplateDo) RightJoin(table schema.Tabler, on ...field.Expr) ISystemSmsTemplateDo {
	return s.withDO(s.DO.RightJoin(table, on...))
}

func (s systemSmsTemplateDo) Group(cols ...field.Expr) ISystemSmsTemplateDo {
	return s.withDO(s.DO.Group(cols...))
}

func (s systemSmsTemplateDo) Having(conds ...gen.Condition) ISystemSmsTemplateDo {
	return s.withDO(s.DO.Having(conds...))
}

func (s systemSmsTemplateDo) Limit(limit int) ISystemSmsTemplateDo {
	return s.withDO(s.DO.Limit(limit))
}

func (s systemSmsTemplateDo) Offset(offset int) ISystemSmsTemplateDo {
	return s.withDO(s.DO.Offset(offset))
}

func (s systemSmsTemplateDo) Scopes(funcs ...func(gen.Dao) gen.Dao) ISystemSmsTemplateDo {
	return s.withDO(s.DO.Scopes(funcs...))
}

func (s systemSmsTemplateDo) Unscoped() ISystemSmsTemplateDo {
	return s.withDO(s.DO.Unscoped())
}

func (s systemSmsTemplateDo) Create(values ...*model.SystemSmsTemplate) error {
	if len(values) == 0 {
		return nil
	}
	return s.DO.Create(values)
}

func (s systemSmsTemplateDo) CreateInBatches(values []*model.SystemSmsTemplate, batchSize int) error {
	return s.DO.CreateInBatches(values, batchSize)
}

// Save : !!! underlying implementation is different with GORM
// The method is equivalent to executing the statement: db.Clauses(clause.OnConflict{UpdateAll: true}).Create(values)
func (s systemSmsTemplateDo) Save(values ...*model.SystemSmsTemplate) error {
	if len(values) == 0 {
		return nil
	}
	return s.DO.Save(values)
}

func (s systemSmsTemplateDo) First() (*model.SystemSmsTemplate, error) {
	if result, err := s.DO.First(); err != nil {
		return nil, err
	} else {
		return result.(*model.SystemSmsTemplate), nil
	}
}

func (s systemSmsTemplateDo) Take() (*model.SystemSmsTemplate, error) {
	if result, err := s.DO.Take(); err != nil {
		return nil, err
	} else {
		return result.(*model.SystemSmsTemplate), nil
	}
}

func (s systemSmsTemplateDo) Last() (*model.SystemSmsTemplate, error) {
	if result, err := s.DO.Last(); err != nil {
		return nil, err
	} else {
		return result.(*model.SystemSmsTemplate), nil
	}
}

func (s systemSmsTemplateDo) Find() ([]*model.SystemSmsTemplate, error) {
	result, err := s.DO.Find()
	return result.([]*model.SystemSmsTemplate), err
}

func (s systemSmsTemplateDo) FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.SystemSmsTemplate, err error) {
	buf := make([]*model.SystemSmsTemplate, 0, batchSize)
	err = s.DO.FindInBatches(&buf, batchSize, func(tx gen.Dao, batch int) error {
		defer func() { results = append(results, buf...) }()
		return fc(tx, batch)
	})
	return results, err
}

func (s systemSmsTemplateDo) FindInBatches(result *[]*model.SystemSmsTemplate, batchSize int, fc func(tx gen.Dao, batch int) error) error {
	return s.DO.FindInBatches(result, batchSize, fc)
}

func (s systemSmsTemplateDo) Attrs(attrs ...field.AssignExpr) ISystemSmsTemplateDo {
	return s.withDO(s.DO.Attrs(attrs...))
}

func (s systemSmsTemplateDo) Assign(attrs ...field.AssignExpr) ISystemSmsTemplateDo {
	return s.withDO(s.DO.Assign(attrs...))
}

func (s systemSmsTemplateDo) Joins(fields ...field.RelationField) ISystemSmsTemplateDo {
	for _, _f := range fields {
		s = *s.withDO(s.DO.Joins(_f))
	}
	return &s
}

func (s systemSmsTemplateDo) Preload(fields ...field.RelationField) ISystemSmsTemplateDo {
	for _, _f := range fields {
		s = *s.withDO(s.DO.Preload(_f))
	}
	return &s
}

func (s systemSmsTemplateDo) FirstOrInit() (*model.SystemSmsTemplate, error) {
	if result, err := s.DO.FirstOrInit(); err != nil {
		return nil, err
	} else {
		return result.(*model.SystemSmsTemplate), nil
	}
}

func (s systemSmsTemplateDo) FirstOrCreate() (*model.SystemSmsTemplate, error) {
	if result, err := s.DO.FirstOrCreate(); err != nil {
		return nil, err
	} else {
		return result.(*model.SystemSmsTemplate), nil
	}
}

func (s systemSmsTemplateDo) FindByPage(offset int, limit int) (result []*model.SystemSmsTemplate, count int64, err error) {
	result, err = s.Offset(offset).Limit(limit).Find()
	if err != nil {
		return
	}

	if size := len(result); 0 < limit && 0 < size && size < limit {
		count = int64(size + offset)
		return
	}

	count, err = s.Offset(-1).Limit(-1).Count()
	return
}

func (s systemSmsTemplateDo) ScanByPage(result interface{}, offset int, limit int) (count int64, err error) {
	count, err = s.Count()
	if err != nil {
		return
	}

	err = s.Offset(offset).Limit(limit).Scan(result)
	return
}

func (s systemSmsTemplateDo) Scan(result interface{}) (err error) {
	return s.DO.Scan(result)
}

func (s systemSmsTemplateDo) Delete(models ...*model.SystemSmsTemplate) (result gen.ResultInfo, err error) {
	return s.DO.Delete(models)
}

func (s *systemSmsTemplateDo) withDO(do gen.Dao) *systemSmsTemplateDo {
	s.DO = *do.(*gen.DO)
	return s
}
